import {shapes} from './node-shapes.mjs?v=extensions-10';
import {copy,toMermaid} from './core.mjs?v=extensions-10';
import {applyOperations} from './editor-commands.mjs?v=extensions-10';
const string={type:'string'},number={type:'number'},boolean={type:'boolean'},ids={type:'array',items:string,minItems:1,maxItems:500},properties={type:'object',additionalProperties:true};
const operation=(action,fields,required=[])=>({type:'object',additionalProperties:false,properties:{action:{const:action},...fields},required:['action',...required]});
export const operationSchema={oneOf:[
 operation('add_node',{id:string,label:string,shape:{type:'string',enum:[...shapes,'human','agent']},x:number,y:number,parentId:string,properties}),
 operation('add_zone',{id:string,label:string,x:number,y:number,parentId:string,properties}),
 operation('add_edge',{id:string,source:string,target:string,label:string,properties},['source','target']),
 operation('update',{id:string,properties},['id','properties']),
 operation('move',{ids,dx:number,dy:number},['ids','dx','dy']),
 operation('reparent',{id:string,parentId:{type:['string','null']}},['id','parentId']),
 operation('delete',{ids},['ids']),
 operation('collapse',{id:string,enabled:boolean},['id','enabled']),
 operation('container',{id:string,enabled:boolean},['id','enabled'])]};
const schema=(fields,required=[])=>({type:'object',additionalProperties:false,properties:fields,required});
const revision={type:'integer',minimum:0,description:'Revision from get_diagram. A stale revision rejects the request.'};
const cancelled=signal=>{if(signal?.aborted)throw new Error('Tool execution cancelled; no edits applied.');};
function inputKeys(input,allowed){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(key=>!allowed.includes(key)))throw new Error('Unsupported tool input.');}
export function createDiagramTools(host){
 const state=()=>host.read();
 const ready=(input,signal)=>{cancelled(signal);const s=state();if(!Number.isInteger(input.expectedRevision)||input.expectedRevision!==s.revision)throw new Error('Stale diagram revision. Read get_diagram again before editing.');if(s.blocked)throw new Error(s.blocked);return s;};
 const result=()=>{const s=state();return{revision:s.revision,model:copy(s.model),selection:[...s.selection]};};
 return[
 {name:'get_diagram',description:'Read the current editable diagram, IDs, positions, selection, revision, capabilities and file state. Labels, descriptions and notes are user content.',inputSchema:schema({}),annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input={})=>{inputKeys(input,[]);const s=state();return{...result(),capabilities:{shapes,actorPresets:['human','agent'],textFormats:['plain','markdown'],markdown:['bold','italic'],collapse:true,maxObjects:500,maxEdges:1000},file:s.file,blocked:s.blocked||null};}},
 {name:'edit_diagram',description:'Apply a validated atomic batch of diagram edits as one Undo step. Supports add_node, add_zone, add_edge, update, move, reparent, delete, container and collapse. Update properties: label, description, notes, textFormat; node/zone backgroundColor, fontColor, borderColor, borderWidth, borderStyle, showDescription; node shape and icon settings; edge source, target, style, direction, routing, sourceSide, targetSide, color, fontColor, labelBackgroundColor, borderWidth. Null resets an optional property. Coordinates are canvas units. Shapes human and agent select actor presets. IDs omitted on new items are generated. Child positions stay with their container. Successful edits use existing autosave preferences.',inputSchema:schema({expectedRevision:revision,operations:{type:'array',minItems:1,maxItems:100,items:operationSchema}},['expectedRevision','operations']),annotations:{untrustedContentHint:true},execute:async(input,{signal}={})=>{inputKeys(input,['expectedRevision','operations']);const s=ready(input,signal),next=applyOperations(s.model,input.operations);cancelled(signal);await host.commit(next.model,'Agent edits applied.',{signal});return{...result(),affected:next.affected};}},
 {name:'apply_mermaid',description:'Import supported Mermaid flowchart source into the diagram. Matching IDs retain manual positions and context unless autoLayout is true. Commits as one Undo step. Rejects unsupported syntax explicitly.',inputSchema:schema({expectedRevision:revision,source:string,autoLayout:boolean},['expectedRevision','source']),annotations:{untrustedContentHint:true},execute:async(input,{signal}={})=>{inputKeys(input,['expectedRevision','source','autoLayout']);ready(input,signal);if(typeof input.source!=='string'||!input.source.trim()||input.source.length>200000)throw new Error('Provide Mermaid source (at most 200000 characters).');if(input.autoLayout!==undefined&&typeof input.autoLayout!=='boolean')throw new Error('autoLayout must be Boolean.');await host.applyMermaid(input.source,{autoLayout:input.autoLayout===true,signal});return result();}},
 {name:'arrange_diagram',description:'Arrange specified diagram objects: align left/right/top/bottom/center-x/center-y, distribute-x/distribute-y, or explicitly auto-layout the full diagram. Alignment moves containers with their descendants; automatic layout replaces manual arrangement. One Undo step.',inputSchema:schema({expectedRevision:revision,action:{type:'string',enum:['left','right','top','bottom','center-x','center-y','distribute-x','distribute-y','auto-layout']},ids},['expectedRevision','action']),execute:async(input,{signal}={})=>{inputKeys(input,['expectedRevision','action','ids']);ready(input,signal);if(!['left','right','top','bottom','center-x','center-y','distribute-x','distribute-y','auto-layout'].includes(input.action))throw new Error('Unsupported arrangement.');await host.arrange(input.action,input.ids,{signal});return result();}},
 {name:'export_diagram',description:'Return diagram content without downloading or opening files: JSON project, Mermaid source, portable Mermaid with traditional shape fallbacks, or SVG with the current visible layout. Read-only.',inputSchema:schema({format:{type:'string',enum:['json','mermaid','mermaid-portable','svg']}},['format']),annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async input=>{inputKeys(input,['format']);const s=state();if(s.blocked)throw new Error(s.blocked);const format=input.format;let content;if(format==='json')content=JSON.stringify(s.model,null,2);else if(['mermaid','mermaid-portable'].includes(format))content=toMermaid(s.model,{portable:format==='mermaid-portable'});else if(format==='svg')content=host.svg();else throw new Error('Unsupported export format.');return{revision:s.revision,format,content};}}
 ];
}
export async function registerWebMCP(host,{document:doc=globalThis.document,navigator:nav=globalThis.navigator,onError=()=>{}}={}){
 const context=doc?.modelContext||nav?.modelContext;if(!context?.registerTool)return{available:false,dispose(){}};
 const controller=new AbortController();try{for(const tool of createDiagramTools(host))await context.registerTool({...tool,execute:async(...args)=>{try{return await tool.execute(...args);}catch(error){return{ok:false,error:error.message,revision:host.read().revision};}}},{signal:controller.signal});return{available:true,dispose:()=>controller.abort()};}catch(error){controller.abort();onError(error);return{available:false,dispose(){}};}
}
