import {initializeMermaid,importMermaid,mergeSource,layoutModel} from '../mermaid-adapter.mjs?v=whole-words';import{copy,toMermaid,validateModel,emptyModel,containerContentBox,resizeNode,nodeMetrics}from'../core.mjs?v=whole-words';import{AvoidLib}from'../vendor/libavoid/dist/index.js';import{DiagramRouter}from'../routing.mjs?v=whole-words';import{exportSvg,createScene}from'../scene.mjs?v=whole-words';
const out=document.getElementById('results'),results=[];
function assert(condition,message){if(!condition)throw new Error(message);}
async function test(name,fn){try{await fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}out.textContent=JSON.stringify(results,null,2);}
initializeMermaid();await AvoidLib.load(new URL('../vendor/libavoid/dist/libavoid.wasm',import.meta.url).href);const router=new DiagramRouter(AvoidLib.getInstance());let model;
await test('starter import preserves nested memberships and all connections',async()=>{const source=await(await fetch('../diagrams/zones-and-subzones.mmd')).text();model=await importMermaid(source);assert(model.nodes.length===9,'nine nodes');assert(model.edges.length===9,'nine edges');assert(model.zones.length===6,'six zones');assert(model.nodes.find(n=>n.id==='Api').parentId==='AppSubnet','API belongs to subnet');assert(model.zones.find(z=>z.id==='AppSubnet').parentId==='AppZone','subnet belongs to zone');router.route(model);});
await test('all five shapes, styles, arrow directions, loops, parallel and explicit IDs roundtrip',async()=>{
 const source='flowchart LR\n subgraph G[Group]\n A[Rectangle]\n B(Rounded)\n C{Decision}\n end\n D((Circle))\n E[(Database)]\n A first@-->|first| B\n A second@-.->|second| B\n B both@<==>|both| C\n C open@--- D\n D loop@--> D\n D custom@--> E';
 const m=await importMermaid(source);assert(new Set(m.nodes.map(n=>n.shape)).size===5,'five shapes');assert(m.edges.find(e=>e.id==='both').direction==='both','both arrows');assert(m.edges.find(e=>e.id==='open').direction==='none','undirected');assert(m.edges.find(e=>e.id==='second').style==='dashed','dashed');const r=router.route(m);assert(r.get('loop').length>=4,'actual loop');const next=await importMermaid(toMermaid(m));assert(JSON.stringify(m.nodes.map(n=>[n.id,n.label,n.shape,n.parentId]))===JSON.stringify(next.nodes.map(n=>[n.id,n.label,n.shape,n.parentId])),'node roundtrip');assert(JSON.stringify(m.edges.map(e=>[e.id,e.source,e.target,e.label,e.style,e.direction]))===JSON.stringify(next.edges.map(e=>[e.id,e.source,e.target,e.label,e.style,e.direction])),'edge roundtrip');
});
await test('quoted, entity, unicode and multiline labels roundtrip without corruption',async()=>{const m=copy(model);m.nodes[0].label='"Quoted" & # < >\n中文 🚀';m.edges[0].label='"edge" & #';const next=await importMermaid(toMermaid(m));assert(next.nodes.find(n=>n.id===m.nodes[0].id).label===m.nodes[0].label,`node special characters: expected ${JSON.stringify(m.nodes[0].label)}, got ${JSON.stringify(next.nodes.find(n=>n.id===m.nodes[0].id).label)}`);assert(next.edges[0].label===m.edges[0].label,'edge special characters');});
await test('empty and entity-like text, including zone titles, roundtrips once',async()=>{const m=copy(model);m.nodes[0].label='';m.nodes[1].label='Literal &amp; #quot; <br/>';m.zones[0].label='"Zone" & 中文 #';const next=await importMermaid(toMermaid(m));for(const item of [...m.nodes,...m.zones])assert([...next.nodes,...next.zones].find(n=>n.id===item.id).label===item.label,`exact label for ${item.id}`);});
await test('source application retains manual positions and private route settings',async()=>{const before=copy(model),api=before.nodes.find(n=>n.id==='Api');api.x+=175;api.y-=75;before.edges[0].routing='straight';const next=mergeSource(before,await importMermaid(toMermaid(before)));const result=next.nodes.find(n=>n.id==='Api');assert(Math.abs((api.x+api.width/2)-(result.x+result.width/2))<.01,'preserve x centre');assert(Math.abs((api.y+api.height/2)-(result.y+result.height/2))<.01,'preserve y centre');assert(next.edges[0].routing==='straight','preserve routing');});
await test('unsupported definitions, styling, callbacks, arrowheads and shapes fail explicitly',async()=>{for(const source of ['sequenceDiagram\n A->>B: Hi','flowchart TD\n A-->B\nclassDef red fill:red','flowchart TD\n A-->B\nclick A "https://example.com"','flowchart TD\n A-->B\nstyle A fill:red','flowchart TD\n A>Unsupported]-->B','flowchart TD\n A --x B','flowchart TD; A-->B; click A call callback()','flowchart TD; A-->B; linkStyle 0 stroke:red','flowchart TD\n A["`**bold**`"]-->B','flowchart TD\n accTitle: Diagram title\n A-->B']){let failed=false;try{await importMermaid(source);}catch{failed=true;}assert(failed,`must reject ${source}`);}});
await test('both layouts work for all supplied architecture shapes and mixed connections',async()=>{const source=await(await fetch('../diagrams/architecture.mmd')).text();const m=await importMermaid(source);assert(m.nodes.length>15,'architecture imported');router.route(m);m.settings.direction='LR';m.settings.layout='hierarchical';await layoutModel(m);router.route(m);validateModel(m);});
await test('exported SVG is standalone, contains full arrangement, and excludes editor controls',async()=>{const routes=router.route(model),svg=exportSvg(model,routes);assert(svg.text.includes('<style>'),'inline export styling');assert(!svg.text.includes('editor-only'),'no controls');assert(!svg.text.includes('selected'),'no selection');assert(!svg.text.includes('http://127.0.0.1'),'no runtime links');const parsed=new DOMParser().parseFromString(svg.text,'image/svg+xml');assert(!parsed.querySelector('parsererror'),'valid XML');assert(parsed.querySelectorAll('.diagram-node').length===model.nodes.length,'all nodes');assert(parsed.querySelectorAll('.diagram-zone').length===model.zones.length,'all zones');const url=URL.createObjectURL(new Blob([svg.text],{type:'image/svg+xml'}));const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=100;canvas.height=100;canvas.getContext('2d').drawImage(image,0,0,100,100);assert(await new Promise(resolve=>canvas.toBlob(resolve)),'PNG render');URL.revokeObjectURL(url);});
await test('zone titles overlay crossing routes with translucent backing in the scene and exported image',async()=>{
 const m=emptyModel();m.nodes=[{id:'A',label:'A',shape:'rectangle',x:0,y:0,width:120,height:70,parentId:null},{id:'B',label:'B',shape:'rectangle',x:520,y:0,width:120,height:70,parentId:null}];
 m.zones=[{id:'Zone',label:'Title',x:220,y:20,width:180,height:160,parentId:null}];m.edges=[{id:'crossing',source:'A',target:'B',label:'',direction:'forward',style:'normal',routing:'orthogonal',sourceSide:null,targetSide:null}];
 const routes=router.route(m),scene=createScene(m,routes),line=scene.querySelector('.edge-line'),title=scene.querySelector('.zone-title');
 assert(routes.get('crossing').every(p=>p.y===35),'route goes directly through the title band');
 assert(Boolean(line.compareDocumentPosition(title)&Node.DOCUMENT_POSITION_FOLLOWING),'title painted after edge');
 assert(title.dataset.objectId==='Zone'&&title.dataset.zoneHeader==='Zone','title retains zone drag target');
 const exported=exportSvg(m,routes),parsed=new DOMParser().parseFromString(exported.text,'image/svg+xml');
 assert(Boolean(parsed.querySelector('.edge-line').compareDocumentPosition(parsed.querySelector('.zone-title'))&Node.DOCUMENT_POSITION_FOLLOWING),'export preserves title layer order');
 const url=URL.createObjectURL(new Blob([exported.text],{type:'image/svg+xml'}));
 try {
  const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=exported.width*4;canvas.height=exported.height*4;const ctx=canvas.getContext('2d');ctx.drawImage(image,0,0,canvas.width,canvas.height);
  const [vx,vy]=parsed.documentElement.getAttribute('viewBox').split(' ').map(Number),backing=parsed.querySelector('.zone-label-backing');
  const sample=(x,y)=>ctx.getImageData(Math.round((x-vx)*4),Math.round((y-vy)*4),1,1).data[0];
  const x=Number(backing.getAttribute('x'))+2,underTitle=sample(x,35),uncovered=sample(250,35),background=sample(x,27);
  assert(underTitle>uncovered+30,'crossing edge is visibly subdued under the title');
  assert(underTitle<background-10,'crossing edge stays visible through the backing');
  assert(await new Promise(resolve=>canvas.toBlob(resolve)),'PNG rendering works with title overlay');
 }finally{URL.revokeObjectURL(url);}
});
await test('parallel long labels remain distinct in the scene and standalone SVG/PNG',async()=>{
 const m=await importMermaid('flowchart LR\n A[Source]\n B[(Destination)]\n A first@-->|Read configuration| B\n A second@-->|Update configuration| B\n A third@-->|Validate configuration| B');
 const routes=router.route(m),exported=exportSvg(m,routes),parsed=new DOMParser().parseFromString(exported.text,'image/svg+xml');
 const labels=[...parsed.querySelectorAll('.edge-label')].map(g=>{const [x,y]=g.getAttribute('transform').match(/[-\d.]+/g).map(Number),r=g.querySelector('rect');return{x:x+Number(r.getAttribute('x')),y:y+Number(r.getAttribute('y')),width:Number(r.getAttribute('width')),height:Number(r.getAttribute('height'))};});
 assert(labels.length===3,'all three labels exported');
 for(let i=0;i<labels.length;i++)for(let j=i+1;j<labels.length;j++){const a=labels[i],b=labels[j];assert(a.x+a.width<=b.x||b.x+b.width<=a.x||a.y+a.height<=b.y||b.y+b.height<=a.y,'parallel labels do not overlap');}
 assert(parsed.querySelectorAll('line.edge-label-leader').length>0,'displaced labels identify their own connection');for(const leader of parsed.querySelectorAll('line.edge-label-leader'))assert(leader.getAttribute('stroke-width')==='1.4'&&leader.getAttribute('vector-effect')==='non-scaling-stroke','leader stays stronger on export');
 const [x,y,w,h]=parsed.documentElement.getAttribute('viewBox').split(' ').map(Number);for(const b of labels)assert(b.x>=x&&b.y>=y&&b.x+b.width<=x+w&&b.y+b.height<=y+h,'export bounds include every label');
 const url=URL.createObjectURL(new Blob([exported.text],{type:'image/svg+xml'}));try{const image=new Image();image.src=url;await image.decode();assert(Math.abs(image.naturalWidth-exported.width)<1&&Math.abs(image.naturalHeight-exported.height)<1,'standalone image renders at full bounds');const canvas=document.createElement('canvas');canvas.width=Math.ceil(exported.width);canvas.height=Math.ceil(exported.height);canvas.getContext('2d').drawImage(image,0,0);const png=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));assert(png?.size>0,'labeled parallel connections render into PNG');}finally{URL.revokeObjectURL(url);}
});
await test('crossing bridges survive standalone SVG and PNG rendering without changing routing',async()=>{
 const m=emptyModel();m.nodes=[{id:'A',label:'A',shape:'rectangle',x:0,y:0,width:120,height:54,parentId:null},{id:'B',label:'B',shape:'rectangle',x:360,y:240,width:120,height:54,parentId:null},{id:'C',label:'C',shape:'rectangle',x:0,y:240,width:120,height:54,parentId:null},{id:'D',label:'D',shape:'rectangle',x:360,y:0,width:120,height:54,parentId:null}];m.edges=[['A','B'],['C','D']].map(([source,target],i)=>({id:'Edge'+i,source,target,label:'',style:'normal',direction:'forward',routing:'straight',sourceSide:'east',targetSide:'west'}));
 const routes=router.route(m),before=JSON.stringify([...routes]),exported=exportSvg(m,routes),parsed=new DOMParser().parseFromString(exported.text,'image/svg+xml');assert(parsed.querySelector('[data-bridge-count="1"]'),'crossing bridge exported');assert(parsed.querySelector('.edge-bridge-halo'),'bridge separation backing exported');assert(JSON.stringify([...routes])===before,'routing untouched');const url=URL.createObjectURL(new Blob([exported.text],{type:'image/svg+xml'}));try{const image=new Image();image.src=url;await image.decode();const c=document.createElement('canvas');c.width=exported.width;c.height=exported.height;c.getContext('2d').drawImage(image,0,0);assert((await new Promise(r=>c.toBlob(r)))?.size>0,'bridged PNG renders');}finally{URL.revokeObjectURL(url);}
});
await test('both initial layouts maintain node clearance after the editor resizes shapes',async()=>{
 const clear=m=>{for(let i=0;i<m.nodes.length;i++)for(let j=i+1;j<m.nodes.length;j++){const a=m.nodes[i],b=m.nodes[j];assert(a.x+a.width+24<=b.x+.001||b.x+b.width+24<=a.x+.001||a.y+a.height+24<=b.y+.001||b.y+b.height+24<=a.y+.001,`${a.id} and ${b.id} have a gap`);}};
 for(const name of ['zones-and-subzones','architecture']){const source=await(await fetch(`../diagrams/${name}.mmd`)).text();const m=await importMermaid(source);clear(m);m.settings.layout='hierarchical';await layoutModel(m);clear(m);}
});
await test('matching source IDs retain node and zone descriptions and notes',async()=>{const m=copy(model);for(const n of [...m.nodes,...m.zones]){n.description='Purpose '+n.id;n.notes='Owner: team\n中文';}const next=mergeSource(m,await importMermaid(toMermaid(m)));for(const n of [...next.nodes,...next.zones])assert(n.description==='Purpose '+n.id&&n.notes==='Owner: team\n中文','context retained for '+n.id);});
await test('project JSON restores geometry and settings without automatic layout',()=>{const saved=JSON.stringify(model);assert(JSON.stringify(validateModel(JSON.parse(saved)))===saved,'exact saved model');});
await test('novel diagrams retain manual dimensions, colors, font and edge context through source and both layouts',async()=>{
 const m=await importMermaid('flowchart LR\n subgraph Lab[Materials workshop]\n A[Collect samples]\n B(Prepare samples)\n C{Quality check}\n end\n D((Ready))\n E[(Archive)]\n A handoff@-->|Batch notes| B\n B check@--> C\n C pass@--> D\n D store@--> E');m.settings.fontSize=32;m.settings.guides=false;m.nodes[0].manualSize={width:280,height:120};m.nodes[0].backgroundColor='#134e4a';m.nodes[0].fontColor='#ffffff';m.zones[0].backgroundColor='#e0e7ff';m.zones[0].fontColor='#3730a3';m.edges[0].description='Chain of custody';m.edges[0].notes='Owner: research\n中文 🚀';
 const next=mergeSource(m,await importMermaid(toMermaid(m)));assert(next.settings.fontSize===32&&next.settings.guides===false,'source preserves text preference');assert(next.nodes[0].manualSize.width===280&&next.nodes[0].fontColor==='#ffffff','source preserves node size and color');assert(next.zones[0].backgroundColor==='#e0e7ff'&&next.edges[0].description==='Chain of custody'&&next.edges[0].notes.includes('中文'),'zone color and edge context retained');
 for(const layout of ['adaptive','hierarchical']){next.settings.layout=layout;await layoutModel(next);validateModel(next);assert(next.nodes[0].width===280,'manual width retained in '+layout);for(const n of next.nodes){const measured=createScene(next,router.route(next),new Set(),{controls:false});const host=document.createElementNS('http://www.w3.org/2000/svg','svg');host.append(measured);document.body.append(host);const group=host.querySelector(`.diagram-node[data-object-id="${n.id}"]`),shape=group.querySelector('.node-shape').getBBox(),text=group.querySelector('text').getBBox();assert(text.x>=shape.x&&text.y>=shape.y&&text.x+text.width<=shape.x+shape.width&&text.y+text.height<=shape.y+shape.height,'large text fits '+n.shape);host.remove();}}
});
await test('large-font colored SVG and PNG include all label bounds and preserve pixels',async()=>{
 const m=await importMermaid('flowchart LR\n subgraph Z[Incident response]\n A[Review 中文]\n B[(Archive)]\n end\n A signal@-->|Evidence transfer| B');m.settings.fontSize=48;m.nodes[0].manualSize={width:360,height:180};m.nodes[0].backgroundColor='#134e4a';m.nodes[0].fontColor='#ffffff';m.zones[0].backgroundColor='#e0e7ff';m.zones[0].fontColor='#3730a3';await layoutModel(m);const exported=exportSvg(m,router.route(m)),parsed=new DOMParser().parseFromString(exported.text,'image/svg+xml');assert(!parsed.querySelector('.editor-only,.resize-handle,.alignment-guides'),'clean export');assert([...parsed.querySelectorAll('.diagram-node text,.zone-label,.edge-label text')].every(t=>t.getAttribute('style').includes('font-size:48px')),'all font sizes exported');
 const url=URL.createObjectURL(new Blob([exported.text],{type:'image/svg+xml'}));try{const image=new Image();image.src=url;await image.decode();const c=document.createElement('canvas');c.width=Math.ceil(exported.width);c.height=Math.ceil(exported.height);const ctx=c.getContext('2d');ctx.drawImage(image,0,0);const [vx,vy]=parsed.documentElement.getAttribute('viewBox').split(' ').map(Number),n=m.nodes[0],pixel=ctx.getImageData(Math.round(n.x+8-vx),Math.round(n.y+30-vy),1,1).data;assert(Math.abs(pixel[0]-19)<3&&Math.abs(pixel[1]-78)<3&&Math.abs(pixel[2]-74)<3,'custom fill reaches image pixels');assert((await new Promise(r=>c.toBlob(r,'image/png')))?.size>1000,'large-font PNG renders');}finally{URL.revokeObjectURL(url);}
});
await test('automatic layouts leave clearance between expanded zones and unrelated root nodes in every direction',async()=>{
 const source=await(await fetch('../diagrams/zones-and-subzones.mmd')).text();const m=await importMermaid(source);
 for(const layout of ['adaptive','hierarchical'])for(const direction of ['LR','RL','TD','BT']){m.settings.layout=layout;m.settings.direction=direction;await layoutModel(m);validateModel(m);for(const a of [...m.nodes,...m.zones].filter(n=>!n.parentId))for(const b of [...m.nodes,...m.zones].filter(n=>!n.parentId&&n!==a))assert(a.x+a.width+24<=b.x+.01||b.x+b.width+24<=a.x+.01||a.y+a.height+24<=b.y+.01||b.y+b.height+24<=a.y+.01,`${layout} ${direction}: ${a.id} clears ${b.id}`);router.route(m);}
});
await test('node containers roundtrip all shapes, nested zones, empty containers and parent connections through both layout engines',async()=>{
 for(const shape of ['rectangle','rounded','circle','diamond','cylinder']){const m=await importMermaid(`flowchart LR\n %% diagram-studio-container {"id":"P","shape":"${shape}"}\n subgraph Z[Platform]\n subgraph P[Delivery service]\n subgraph Inner[Worker pool]\n A[Receive]\n B[(Archive)]\n end\n end\n end\n C[Client]\n C incoming@--> A\n A stored@--> B\n P health@--> C`);assert(m.nodes.find(n=>n.id==='P').container&&m.nodes.find(n=>n.id==='P').shape===shape,'parent shape imported');assert(m.zones.find(n=>n.id==='Inner').parentId==='P','zone inside node');for(const layout of ['adaptive','hierarchical']){m.settings.layout=layout;await layoutModel(m);validateModel(m);const p=m.nodes.find(n=>n.id==='P'),inner=m.zones.find(n=>n.id==='Inner'),b=containerContentBox(m,p);assert(inner.x>=b.x-.01&&inner.y>=b.y-.01&&inner.x+inner.width<=b.x+b.width+.01&&inner.y+inner.height<=b.y+b.height+.01,'inner zone fits '+shape);router.route(m);}const next=await importMermaid(toMermaid(m));assert(next.nodes.find(n=>n.id==='P').shape===shape&&next.nodes.find(n=>n.id==='A').parentId==='Inner','shape and nested memberships roundtrip');}
 const empty=await importMermaid('flowchart TD\n %% diagram-studio-container {"id":"P","shape":"circle"}\n subgraph P[Empty service]\n end\n C[Client]\n P link@--> C');assert(empty.nodes.find(n=>n.id==='P').container,'empty node container roundtrip');router.route(empty);
});
await test('malformed or contradictory container annotations fail explicitly',async()=>{
 for(const annotation of ['{bad}','{"id":"Missing","shape":"circle"}','{"id":"Z","shape":"star"}','{"id":"Z","shape":"circle"}\n %% diagram-studio-container {"id":"Z","shape":"rounded"}']){let failed=false;try{await importMermaid(`flowchart LR\n %% diagram-studio-container ${annotation}\n subgraph Z[Group]\n A[Child]\n end`);}catch{failed=true;}assert(failed,'reject annotation '+annotation);}
});
await test('live label metrics fit circle and diamond outlines at browser-measured font sizes and unwrap short labels',async()=>{
 for(const shape of ['circle','diamond'])for(const font of [10,13,28,48])for(const label of ['New Node','中文 🚀\nReview response','LongWordWithoutSpaces']){const m=emptyModel();m.settings.fontSize=font;const n={id:'N',label,shape,parentId:null,x:50,y:50,width:100,height:180,manualSize:{width:shape==='circle'?90:100,height:shape==='circle'?90:180}};m.nodes=[n];resizeNode(n,font);const host=document.createElementNS('http://www.w3.org/2000/svg','svg');host.append(createScene(m,new Map(),new Set(),{controls:false}));document.body.append(host);try{const text=host.querySelector('.diagram-node text').getBBox();for(const x of [text.x,text.x+text.width])for(const y of [text.y,text.y+text.height]){const dx=Math.abs(x-n.width/2),dy=Math.abs(y-n.height/2);assert(shape==='circle'?Math.hypot(dx,dy)<n.width/2:dx/(n.width/2)+dy/(n.height/2)<1,'text rectangle fits actual '+shape+' at '+font);}}finally{host.remove();}if(label==='New Node'&&font===13){assert(nodeMetrics(n,font).lines.length>1,'short label wraps');n.manualSize={width:300,height:300};assert(nodeMetrics(n,font).lines.length===1,'short label unwraps');}}
});
await test('parent-node titles and colors survive standalone SVG and PNG',async()=>{
 const m=await importMermaid('flowchart LR\n %% diagram-studio-container {"id":"P","shape":"rounded"}\n subgraph Z[Platform]\n subgraph P[Notification service]\n A[Inbox]\n B[Worker]\n end\n end\n C[Client]\n C incoming@-->|New notification| A\n C retry@-->|Retry notification| A\n A dispatch@--> B\n P health@--> C');m.zones[0].backgroundColor='#e0e7ff';m.nodes.find(n=>n.id==='P').backgroundColor='#dbeafe';const routes=router.route(m),exported=exportSvg(m,routes),parsed=new DOMParser().parseFromString(exported.text,'image/svg+xml');assert(!parsed.querySelector('parsererror'),'valid parent export');const parent=parsed.querySelector('.container-node'),title=parsed.querySelector('.node-container-title'),edge=parsed.querySelector('.edge-line'),leaf=parsed.querySelector('.diagram-node[data-object-id="A"]');assert(parent&&title&&leaf,'container layers exported');assert(title.getAttribute('clip-path')?.includes('container-outline-P')&&parsed.querySelector('#container-outline-P'),'title clipped to rounded shape');assert(Boolean(parent.compareDocumentPosition(edge)&Node.DOCUMENT_POSITION_FOLLOWING)&&Boolean(edge.compareDocumentPosition(title)&Node.DOCUMENT_POSITION_FOLLOWING),'title over routes, routes over parent body');assert(Boolean(parent.compareDocumentPosition(leaf)&Node.DOCUMENT_POSITION_FOLLOWING),'child painted above parent');
 const url=URL.createObjectURL(new Blob([exported.text],{type:'image/svg+xml'}));try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=exported.width;canvas.height=exported.height;canvas.getContext('2d').drawImage(image,0,0);assert((await new Promise(r=>canvas.toBlob(r,'image/png')))?.size>1000,'container PNG renders');}finally{URL.revokeObjectURL(url);}
});
await test('zone connection border approaches survive standalone SVG and PNG exports',async()=>{
 const m=emptyModel();m.zones=[{id:'Left',label:'Source zone',x:50,y:80,width:280,height:180,parentId:null},{id:'Right',label:'Target zone',x:620,y:110,width:280,height:180,parentId:null}];m.nodes=[{id:'N',label:'Worker',shape:'rectangle',x:120,y:380,width:120,height:54,parentId:null}];m.edges=[['Left','Right'],['N','Right']].map(([source,target],i)=>({id:'E'+i,source,target,label:'',direction:'forward',style:'normal',routing:'orthogonal',sourceSide:null,targetSide:null}));
 const routes=router.route(m);for(const p of routes.values()){assert(Math.abs(p.at(-1).y-p.at(-2).y)<.001&&p.at(-2).x<p.at(-1).x&&p.at(-1).x===620,'arrow points into west border');}const svg=exportSvg(m,routes),parsed=new DOMParser().parseFromString(svg.text,'image/svg+xml');assert(parsed.querySelector('#arrowhead').getAttribute('orient')==='auto-start-reverse','marker follows final route segment');for(const e of m.edges){const p=routes.get(e.id),line=parsed.querySelector(`[data-edge-id="${e.id}"]`);assert(line.getAttribute('d').endsWith(`L${p.at(-1).x},${p.at(-1).y}`)&&line.getAttribute('marker-end')==='url(#arrowhead)','export retains arrow and border endpoint');}
 const url=URL.createObjectURL(new Blob([svg.text],{type:'image/svg+xml'}));try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=svg.width;canvas.height=svg.height;canvas.getContext('2d').drawImage(image,0,0);assert((await new Promise(r=>canvas.toBlob(r,'image/png')))?.size>1000,'zone connection PNG renders');}finally{URL.revokeObjectURL(url);}
});
await test('whole words fit every shape and remain intact in standalone SVG and PNG',async()=>{
 for(const shape of ['rectangle','rounded','circle','diamond','cylinder'])for(const label of ['Customer Browser','CustomerBrowserIdentifier','中文没有空格','e\u0301tiquette 👨‍👩‍👧‍👦']){
  const m=emptyModel();m.settings.fontSize=20;const n={id:'N',label,shape,parentId:null,x:50,y:50,width:150,height:150,manualSize:{width:150,height:150}};m.nodes=[n];resizeNode(n,20);
  const host=document.createElementNS('http://www.w3.org/2000/svg','svg');host.append(createScene(m,new Map(),new Set(),{controls:false}));document.body.append(host);
  try{const text=host.querySelector('.diagram-node text'),lines=[...text.querySelectorAll('tspan')].map(t=>t.textContent),b=text.getBBox();assert(lines.join(' ')===label,'only whitespace breaks for '+shape);for(const x of [b.x,b.x+b.width])for(const y of [b.y,b.y+b.height]){const dx=Math.abs(x-n.width/2),dy=Math.abs(y-n.height/2);assert(shape==='circle'?Math.hypot(dx,dy)<n.width/2:shape==='diamond'?dx/(n.width/2)+dy/(n.height/2)<1:x>=0&&x<=n.width&&y>=0&&y<=n.height,'whole words fit actual '+shape);}if(shape==='circle'&&label==='Customer Browser')assert(JSON.stringify(lines)===JSON.stringify(['Customer','Browser']),'screenshot circle wraps between words');}finally{host.remove();}
 }
 const m=emptyModel();m.settings.fontSize=20;m.nodes=[{id:'N',label:'Customer Browser',shape:'circle',parentId:null,x:50,y:50,width:150,height:150,manualSize:{width:150,height:150}}];resizeNode(m.nodes[0],20);const svg=exportSvg(m,new Map()),parsed=new DOMParser().parseFromString(svg.text,'image/svg+xml');assert(JSON.stringify([...parsed.querySelectorAll('.diagram-node text tspan')].map(t=>t.textContent))===JSON.stringify(['Customer','Browser']),'export retains whole-word wrapping');const url=URL.createObjectURL(new Blob([svg.text],{type:'image/svg+xml'}));try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=svg.width;canvas.height=svg.height;canvas.getContext('2d').drawImage(image,0,0);assert((await new Promise(resolve=>canvas.toBlob(resolve,'image/png')))?.size>1000,'whole-word PNG renders');}finally{URL.revokeObjectURL(url);}
});
await test('Auto layout and source application preserve manual route coordinates and forced sides',async()=>{
 const m=await importMermaid('flowchart LR\n subgraph Z[Stage]\n A[Start]\n B[Finish]\n end\n A path@--> B');m.edges[0].waypoints=[{x:850,y:500},{x:850,y:-150}];m.edges[0].sourceSide='south';m.edges[0].targetSide='north';const points=JSON.stringify(m.edges[0].waypoints);
 for(const layout of ['adaptive','hierarchical']){m.settings.layout=layout;await layoutModel(m);assert(JSON.stringify(m.edges[0].waypoints)===points,'layout preserves corridor');assert(m.edges[0].sourceSide==='south'&&m.edges[0].targetSide==='north','layout preserves sides');router.route(m);}
 const next=mergeSource(m,await importMermaid(toMermaid(m)));assert(JSON.stringify(next.edges[0].waypoints)===points,'source preserves waypoints with matching endpoints');const changed=await importMermaid('flowchart LR\n A[Start]\n B[Finish]\n C[New]\n A path@--> C');assert(!mergeSource(m,changed).edges[0].waypoints,'changed endpoint does not inherit an unrelated corridor');
});
await test('manual route SVG and PNG preserve path geometry and omit editing handles',async()=>{
 const m=emptyModel();m.nodes=[{id:'A',label:'Start',shape:'rounded',x:0,y:0,width:120,height:54,parentId:null},{id:'B',label:'Finish',shape:'circle',x:600,y:50,width:120,height:120,parentId:null}];m.edges=[{id:'E',source:'A',target:'B',label:'Outside route',style:'normal',direction:'forward',routing:'orthogonal',sourceSide:'south',targetSide:'south',waypoints:[{x:180,y:350},{x:800,y:350}]}];const routes=router.route(m),scene=createScene(m,routes,new Set(['E']));assert(scene.querySelectorAll('.waypoint-handle').length===2,'editor shows manual points');const svg=exportSvg(m,routes),parsed=new DOMParser().parseFromString(svg.text,'image/svg+xml');assert(!parsed.querySelector('.waypoint-handle,.route-segment-handle,.editor-only'),'no handles in export');assert(parsed.querySelector('.edge-line').getAttribute('d')===scene.querySelector('.edge-line').getAttribute('d'),'same path in export');assert(svg.width>800&&svg.height>350,'export includes the outside corridor');const url=URL.createObjectURL(new Blob([svg.text],{type:'image/svg+xml'}));try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=svg.width;canvas.height=svg.height;canvas.getContext('2d').drawImage(image,0,0);assert((await new Promise(resolve=>canvas.toBlob(resolve,'image/png')))?.size>1000,'manual route PNG renders');}finally{URL.revokeObjectURL(url);}
});

await test('manual label positions survive all layouts and matching source edits',async()=>{
 const m=await importMermaid('flowchart LR\n subgraph Z[Orbital depot]\n A[Scout]\n B[Dock]\n end\n A link@-->|Docking clearance| B');m.edges[0].labelPosition={fraction:.4,offsetAlong:0,offsetNormal:90};const position=JSON.stringify(m.edges[0].labelPosition);for(const layout of ['adaptive','hierarchical'])for(const direction of ['LR','TD','RL','BT']){m.settings.layout=layout;m.settings.direction=direction;await layoutModel(m);assert(JSON.stringify(m.edges[0].labelPosition)===position,'layout retains manual preference');const scene=createScene(m,router.route(m));assert(scene.querySelector('.manual-label .edge-label-leader'),'off-route leader survives layout');}const next=mergeSource(m,await importMermaid(toMermaid(m)));assert(JSON.stringify(next.edges[0].labelPosition)===position,'source retains preference');const changed=await importMermaid('flowchart LR\n A[Scout]\n C[New dock]\n A link@-->|Docking clearance| C');assert(!mergeSource(m,changed).edges[0].labelPosition,'unrelated replacement edge uses automatic placement');
});
await test('manual labels and leaders appear identically in SVG and render into PNG export bounds',async()=>{
 const m=emptyModel();m.nodes=[{id:'A',label:'Scout',shape:'circle',x:0,y:0,width:100,height:100,parentId:null},{id:'B',label:'Dock',shape:'cylinder',x:500,y:0,width:120,height:80,parentId:null}];m.edges=[{id:'E',source:'A',target:'B',label:'Docking clearance\n授权',direction:'forward',style:'dashed',routing:'orthogonal',labelPosition:{fraction:.5,offsetAlong:0,offsetNormal:300}}];const routes=router.route(m);m.edges[0].labelPosition=(await import('../labels.mjs?v=whole-words')).manualLabelPosition(routes.get('E'),{x:400,y:350});const scene=createScene(m,routes),svg=exportSvg(m,routes),parsed=new DOMParser().parseFromString(svg.text,'image/svg+xml');assert(scene.querySelector('.manual-label').getAttribute('transform')===parsed.querySelector('.manual-label').getAttribute('transform'),'same placement');const leader=parsed.querySelector('.manual-label line.edge-label-leader');assert(leader&&leader.getAttribute('stroke-width')==='1.4'&&leader.getAttribute('vector-effect')==='non-scaling-stroke','existing leader styling preserved');assert(svg.height>330,'manual label included in image bounds');const url=URL.createObjectURL(new Blob([svg.text],{type:'image/svg+xml'}));try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=svg.width;canvas.height=svg.height;canvas.getContext('2d').drawImage(image,0,0);assert((await new Promise(resolve=>canvas.toBlob(resolve,'image/png')))?.size>1000,'PNG renders');}finally{URL.revokeObjectURL(url);}
});

await test('repaired waypoint joins preserve the saved lunar arrangement and standalone SVG/PNG geometry',async()=>{
 const m=await(await fetch('artifacts/f2-lunar-rescue.mermaid-project.json')).json();m.edges.find(e=>e.id==='Edge5').labelPosition.offsetNormal=140;const before=JSON.stringify(m),routes=router.route(m,{optimize:false}),path=routes.get('Edge5');
 for(let i=1;i<path.length-1;i++){const a=path[i-1],b=path[i],c=path[i+1];assert(!((b.x-a.x)*(c.x-b.x)+(b.y-a.y)*(c.y-b.y)<0&&Math.abs((b.x-a.x)*(c.y-b.y)-(b.y-a.y)*(c.x-b.x))<.001),'dispatch has no retracing corner');}
 assert(JSON.stringify(m)===before,'diagram coordinates and label preferences untouched');const scene=createScene(m,routes),svg=exportSvg(m,routes),parsed=new DOMParser().parseFromString(svg.text,'image/svg+xml');
 assert(scene.querySelector('[data-edge-id=Edge5]').getAttribute('d')===parsed.querySelector('[data-edge-id=Edge5]').getAttribute('d'),'identical repaired path in export');assert(Number(parsed.querySelector('[data-edge-id=Edge7]').getAttribute('data-bridge-count'))>0,'crossing at the radar waypoint retains its bridge');assert(scene.querySelector('.edge-label[data-object-id=Edge5]').getAttribute('transform')===parsed.querySelector('.edge-label[data-object-id=Edge5]').getAttribute('transform'),'identical route-following label');assert(parsed.querySelector('.edge-label[data-object-id=Edge5] .edge-label-leader'),'leader preserved');assert(!parsed.querySelector('.editor-only,.waypoint-handle,.route-segment-handle'),'controls excluded');
 const url=URL.createObjectURL(new Blob([svg.text],{type:'image/svg+xml'}));try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=svg.width;canvas.height=svg.height;canvas.getContext('2d').drawImage(image,0,0);assert((await new Promise(resolve=>canvas.toBlob(resolve,'image/png')))?.size>1000,'repaired SVG renders to PNG');}finally{URL.revokeObjectURL(url);}
});
await test('attachment preferences survive layouts and matching source edits and prune replaced endpoints',async()=>{
 const m=await importMermaid('flowchart LR\n A[Launch]\n B[Storm]\n C[Plan]\n A radar@-.-> B\n C plan@--> A');m.edges[0].sourceSide='west';m.edges[1].targetSide='west';m.nodes.find(n=>n.id==='A').attachmentOrder={west:['plan:target','radar:source']};
 const next=mergeSource(m,await importMermaid(toMermaid(m)));assert(JSON.stringify(next.nodes.find(n=>n.id==='A').attachmentOrder)===JSON.stringify(m.nodes.find(n=>n.id==='A').attachmentOrder),'matching source retains stack');validateModel(next);
 for(const layout of ['adaptive','hierarchical']){next.settings.layout=layout;await layoutModel(next);assert(next.nodes.find(n=>n.id==='A').attachmentOrder.west.join(',')==='plan:target,radar:source','layout retains manual order');router.route(next);}
 const changed=mergeSource(m,await importMermaid('flowchart LR\n A[Launch]\n B[Storm]\n C[Plan]\n B radar@-.-> C\n C plan@--> A'));assert(changed.nodes.find(n=>n.id==='A').attachmentOrder.west.join(',')==='plan:target','replaced endpoint pruned');validateModel(changed);
});
await test('automatic attachment swaps remove the radar bridge and retain labels and exported geometry',async()=>{
 const m=await(await fetch('artifacts/f2-lunar-rescue.mermaid-project.json')).json(),before=JSON.stringify(m),routes=router.route(m),scene=createScene(m,routes),exported=exportSvg(m,routes),parsed=new DOMParser().parseFromString(exported.text,'image/svg+xml');
 assert(routes.get('Edge7')[0].y>routes.get('Edge5').at(-1).y,'dotted attachment is below solid');assert(Number(parsed.querySelector('[data-edge-id=Edge7]').dataset.bridgeCount)===0,'crossing eliminated');assert(JSON.stringify(m)===before,'manual geometry intact');assert(scene.querySelector('[data-edge-id=Edge7]').getAttribute('d')===parsed.querySelector('[data-edge-id=Edge7]').getAttribute('d'),'same path exported');assert(parsed.querySelectorAll('.edge-label-leader').length>=8,'leaders preserved');
});
router.dispose();out.dataset.complete='true';out.dataset.passed=String(results.every(r=>r.pass));out.textContent=JSON.stringify({passed:results.filter(r=>r.pass).length,total:results.length,results},null,2);
