import test from 'node:test';import assert from 'node:assert/strict';
import {emptyModel,copy,History,moveSelection,groupSelection,deleteSelection,reparent,arrange,toMermaid,resizeNode,validateModel} from '../core.mjs';
const node=(id,x,y,parentId=null)=>({id,label:id,shape:'rectangle',x,y,width:120,height:54,parentId});
function fixture(){const m=emptyModel();m.zones=[{id:'Outer',label:'Outer',x:0,y:0,width:500,height:400,parentId:null},{id:'Inner',label:'Inner',x:20,y:50,width:350,height:250,parentId:'Outer'}];m.nodes=[node('A',50,100,'Inner'),node('B',200,180,'Inner'),node('C',600,200)];m.edges=[{id:'e1',source:'A',target:'C',label:'test',direction:'forward',style:'normal',routing:'orthogonal'}];return m;}
test('moving an ancestor and a selected descendant moves each object once',()=>{const m=fixture();moveSelection(m,new Set(['Outer','Inner','A']),30,40);assert.equal(m.nodes[0].x,80);assert.equal(m.nodes[0].y,140);assert.equal(m.zones[1].x,50);assert.equal(m.nodes[2].x,600);});
test('moving children expands nested parents without changing membership',()=>{const m=fixture();moveSelection(m,new Set(['A']),-180,-160);assert.equal(m.nodes[0].parentId,'Inner');assert.ok(m.zones[1].x<=m.nodes[0].x-20);assert.ok(m.zones[0].x<=m.zones[1].x-20);});
test('ungroup retains children and deleting a node removes incident edges',()=>{const m=fixture();deleteSelection(m,new Set(['Inner']));assert.equal(m.nodes[0].parentId,'Outer');assert.equal(m.nodes.length,3);deleteSelection(m,new Set(['A']));assert.equal(m.edges.length,0);});
test('grouping and reparenting preserve a valid hierarchy',()=>{const m=fixture();const zone=groupSelection(m,new Set(['A','B']));assert.equal(zone.parentId,'Inner');assert.equal(m.nodes[0].parentId,zone.id);assert.throws(()=>reparent(m,'Outer',zone.id));assert.doesNotThrow(()=>validateModel(m));});
test('alignment and distribution do not move unrelated objects',()=>{const m=fixture();m.nodes[0].parentId=null;m.nodes[1].parentId=null;const before=copy(m);arrange(m,new Set(['A','B']),'top');assert.equal(m.nodes[0].y,m.nodes[1].y);assert.deepEqual(m.nodes[2],before.nodes[2]);arrange(m,new Set(['A','B','C']),'distribute-x');const gap1=m.nodes[1].x-m.nodes[0].x-m.nodes[0].width,gap2=m.nodes[2].x-m.nodes[1].x-m.nodes[1].width;assert.equal(gap1,gap2);});
test('shape changes keep centre and ID',()=>{const n=node('A',50,50),cx=n.x+n.width/2,cy=n.y+n.height/2;n.shape='diamond';resizeNode(n);assert.equal(n.id,'A');assert.equal(n.x+n.width/2,cx);assert.equal(n.y+n.height/2,cy);});
test('source serializes supported structure and safely encodes special labels',()=>{const m=fixture();m.nodes[0].label='a "quote" & # < >\nnext';m.edges[0].style='dashed';m.edges[0].direction='both';const source=toMermaid(m);assert.match(source,/#quot;quote#quot;/);assert.match(source,/#38; #35; #60; #62;/);assert.match(source,/e1@<-\.->/);assert.match(source,/<br\/>next/);});
test('history captures a whole gesture and clears redo after a new action',()=>{const h=new History(),before=fixture(),after=copy(before);moveSelection(after,new Set(['A']),10,10);h.record(before,after);assert.deepEqual(h.undo(after),before);assert.deepEqual(h.redo(before),after);h.undo(after);const next=copy(before);next.nodes[0].label='Changed';h.record(before,next);assert.equal(h.future.length,0);assert.equal(h.past.length,1);});
test('project validation catches corrupt geometry, hierarchy, endpoints and versions',()=>{const valid=fixture();assert.deepEqual(validateModel(JSON.parse(JSON.stringify(valid))),valid);for(const change of [m=>m.version=2,m=>m.nodes[0].width=-1,m=>m.zones[0].parentId='Inner',m=>m.edges[0].target='missing',m=>m.nodes[0].shape='unknown',m=>m.nodes[0].x=Infinity]){const m=copy(valid);change(m);assert.throws(()=>validateModel(m));}});
test('grouping objects from different zones uses their common ancestor and preserves positions',()=>{const m=fixture(),before=copy(m.nodes);const zone=groupSelection(m,new Set(['A','C']));assert.equal(zone.parentId,null);assert.equal(m.nodes[0].parentId,zone.id);assert.equal(m.nodes[2].parentId,zone.id);for(let i=0;i<m.nodes.length;i++){assert.equal(m.nodes[i].x,before[i].x);assert.equal(m.nodes[i].y,before[i].y);}assert.doesNotThrow(()=>validateModel(m));});
