import test from 'node:test';import assert from 'node:assert/strict';
import {emptyModel,copy,validateModel,object,items,nodeMetrics,resizeNode,toMermaid,moveSelection,arrange,containingParent,setNodeContainer} from '../core.mjs?v=icons-3';
import {shapes,chooseShape,shapeParts,cloudIntersection,iconFrame} from '../node-shapes.mjs';
import {parseText,lineRuns} from '../rich-text.mjs';import {presentationModel} from '../presentation.mjs';import {importStyles,classStyles} from '../appearance.mjs';import {applyOperations} from '../editor-commands.mjs';import {createDiagramTools,registerWebMCP} from '../webmcp.mjs';
import {AvoidLib} from '../vendor/libavoid/dist/index-node.mjs';import {DiagramRouter,sidePoint} from '../routing.mjs?v=icons-3';
await AvoidLib.load(new URL('../vendor/libavoid/dist/libavoid.wasm',import.meta.url).pathname);const router=new DiagramRouter(AvoidLib.getInstance());
const node=(id,x=0,y=0)=>({id,label:id,shape:'rectangle',parentId:null,x,y,width:120,height:54});
const edge=(id,source,target)=>({id,source,target,label:'',direction:'forward',style:'normal',routing:'orthogonal',sourceSide:null,targetSide:null});
function fixture(){const m=emptyModel();m.zones=[{id:'Outer',label:'Outer',parentId:null,x:0,y:0,width:600,height:400},{id:'Inner',label:'Inner',parentId:'Outer',x:20,y:60,width:300,height:250}];m.nodes=[{...node('A',50,120),parentId:'Inner'},{...node('B',50,220),parentId:'Inner'},node('C',850,120)];m.edges=[edge('internal','A','B'),edge('one','A','C'),edge('two','B','C')];return m;}
for(const shape of shapes)test(`shape ${shape} sizes, ports and libavoid routes stay finite after a move`,()=>{const m=emptyModel(),n=node('A');chooseShape(n,shape);resizeNode(n);m.nodes=[n,node('B',500,150)];m.edges=[edge('flow','A','B')];validateModel(m);assert(n.width>0&&n.height>0);assert(shapeParts(n).length||shape==='icon');for(const side of ['north','south','west','east'])for(const t of [.2,.35,.5,.65,.8])assert(Object.values(sidePoint(n,side,t)).every(Number.isFinite));const first=router.route(m).get('flow');n.y+=150;const moved=router.route(m).get('flow');assert.notDeepEqual(first,moved);for(let i=1;i<moved.length;i++)assert(Math.abs(moved[i].x-moved[i-1].x)<.01||Math.abs(moved[i].y-moved[i-1].y)<.01);});
test('actor presets retain identity and choose local icons',()=>{const n=node('Actor');chooseShape(n,'agent');assert.equal(n.id,'Actor');assert.equal(n.icon,'studio:agent');assert.equal(n.shape,'icon');chooseShape(n,'human');assert.equal(n.icon,'studio:human');});
test('cloud ports match cubic outline and icon ports match the symbol frame',()=>{assert(Math.abs(cloudIntersection('north',.5))<1e-8);assert(Math.abs(cloudIntersection('west',.5))<1e-8);assert(cloudIntersection('north',.1)>.2);const n=node('Actor');chooseShape(n,'agent');resizeNode(n);const f=iconFrame(n),p=sidePoint(n,'east');assert.equal(p.x,n.x+f.x+f.width);assert.equal(p.y,n.y+f.y+f.height/2);});
test('plain labels remain literal; Markdown supports nested and combined emphasis',()=>{assert.equal(parseText('**literal**').text,'**literal**');const p=parseText('**bold *nested* text** and ***both***','markdown');assert.equal(p.text,'bold nested text and both');assert(p.runs.find(r=>r.text==='nested').bold&&p.runs.find(r=>r.text==='nested').italic);assert(p.runs.at(-1).bold&&p.runs.at(-1).italic);assert.equal(parseText('field_name_value','markdown').text,'field_name_value');assert.equal(parseText('\\*literal\\*','markdown').text,'*literal*');assert.equal(parseText('**unfinished','markdown').text,'**unfinished');});
test('formatted lines keep emphasis after wrapping at repeated spaces and newlines',()=>{const n={label:'**Alpha**   *Beta*\n***Gamma***',textFormat:'markdown'};const a=lineRuns(n,'Alpha Beta');assert(a.runs.find(r=>r.text==='Alpha').bold);assert(a.runs.find(r=>r.text==='Beta').italic);const b=lineRuns(n,'Gamma',a.end);assert(b.runs[0].bold&&b.runs[0].italic);});
test('escaped closing markers do not consume unmatched opening markers',()=>{assert.equal(parseText('*literal\\*','markdown').text,'*literal*');assert.equal(parseText('**literal\\*\\*','markdown').text,'**literal**');const p=parseText('*one\\* two*','markdown');assert.equal(p.text,'one* two');assert(p.runs.every(r=>r.italic));});
test('unsupported Markdown and invalid icon/style/collapse values reject',()=>{for(const properties of [{textFormat:'html'},{textFormat:'markdown',label:'[link](url)'},{shape:'icon',icon:'bad url'},{borderWidth:20},{borderColor:'red'},{collapsed:true}]){const m=emptyModel();m.nodes=[{...node('A'),...properties}];assert.throws(()=>validateModel(m));}});
test('class styles resolve before object overrides; unsupported CSS rejects',()=>{const classes=new Map([['green',{styles:['fill:#abc','stroke:green'],textStyles:['color:white']}]]);const styles=importStyles(classStyles({classes:['green'],styles:['fill:#123456']},classes));assert.equal(styles.backgroundColor,'#123456');assert.equal(styles.borderColor,'#008000');assert.equal(styles.fontColor,'#ffffff');assert.throws(()=>importStyles(['opacity:.5']),/Unsupported/);assert.throws(()=>importStyles(['fill:url(example)']));assert.deepEqual(importStyles(['stroke:#123456','fill:none'],true),{color:'#123456'});});
test('native export emits chosen colors and metadata; portable export avoids new syntax',()=>{const m=fixture();chooseShape(m.nodes[0],'agent');m.nodes[0].backgroundColor='#abcdef';m.nodes[0].textFormat='markdown';m.nodes[0].label='**Agent**';m.zones[0].collapsed=true;const native=toMermaid(m),portable=toMermaid(m,{portable:true});assert(native.includes('icon: "studio:agent"')&&native.includes('fill:#abcdef')&&native.includes('view: collapsed'));assert(!portable.includes('@{')&&!portable.includes('one@-->'));assert(portable.includes('diagram-studio-edge'));assert(!toMermaid(m,{layout:true}).includes('view: collapsed'));});
test('outermost collapse projection preserves all data and nested preferences',()=>{const m=fixture();m.zones[0].collapsed=true;m.zones[1].collapsed=true;const before=copy(m),p=presentationModel(m);assert.equal(p.nodes.length,1);assert.deepEqual(p.edges.map(e=>e.source),['Outer','Outer']);assert.equal(m.edges[1].source,'A');assert.deepEqual(m,before);m.zones[0].collapsed=false;const nested=presentationModel(m);assert(nested.zones.some(z=>z.id==='Inner'));assert(!nested.nodes.some(n=>n.id==='A'));});
test('collapse routes distinct external edges to proxy, hides internal edges and restores',()=>{const m=fixture();m.zones[0].collapsed=true;const original=copy(m),routes=router.route(m);assert(!routes.has('internal'));assert.notDeepEqual(routes.get('one'),routes.get('two'));const p=presentationModel(m),proxy=p.zones[0];assert(routes.get('one')[0].x<=proxy.x+proxy.width+.01);m.zones[0].collapsed=false;router.route(m);assert.deepEqual(m.nodes,original.nodes);assert.deepEqual(m.edges,original.edges);});
test('collapsed group movement translates contents once and alignment uses compact frames',()=>{const m=fixture();m.zones[0].collapsed=true;const before=copy(m);moveSelection(m,new Set(['Outer','A']),30,20,{expand:false});assert.equal(object(m,'A').x,object(before,'A').x+30);assert.equal(object(m,'Inner').y,object(before,'Inner').y+20);arrange(m,new Set(['Outer','C']),'right');const visible=presentationModel(m);assert(Math.abs(visible.zones[0].x+visible.zones[0].width-visible.nodes[0].x-visible.nodes[0].width)<.01);});
test('collapsed groups reject drag containment and disabling node container clears collapse',()=>{const m=fixture();m.zones[0].collapsed=true;assert.equal(containingParent(m,node('New',10,80),new Set(),[m.zones[0]]),null);const n=m.nodes[2];setNodeContainer(m,n.id,true);n.collapsed=true;setNodeContainer(m,n.id,false);assert.equal(n.collapsed,undefined);});
test('semantic operations are atomic and use containment/shape helpers',()=>{const m=emptyModel(),before=copy(m),result=applyOperations(m,[{action:'add_node',id:'Agent',shape:'agent'},{action:'container',id:'Agent',enabled:true},{action:'add_node',id:'Child',parentId:'Agent'},{action:'add_edge',source:'Child',target:'Agent'}]);assert.deepEqual(m,before);assert.equal(object(result.model,'Child').parentId,'Agent');assert.equal(object(result.model,'Agent').icon,'studio:agent');assert.throws(()=>applyOperations(m,[{action:'add_node',id:'A'},{action:'add_edge',source:'A',target:'missing'}]));assert.deepEqual(m,before);assert.throws(()=>applyOperations(m,[{action:'update',id:'A',properties:{javascript:'bad'}}]));});
function host(){let model=emptyModel(),revision=1,commits=0;return{read:()=>({model,revision,selection:new Set(),file:{name:'Untitled'},blocked:null}),commit:next=>{model=next;revision++;commits++;},get commits(){return commits;},svg:()=>'<svg/>'};}
test('WebMCP batches commit once; stale/cancelled/invalid requests leave model intact',async()=>{const h=host(),tools=createDiagramTools(h),edit=tools.find(t=>t.name==='edit_diagram');await edit.execute({expectedRevision:1,operations:[{action:'add_node',id:'A'},{action:'add_node',id:'B',x:200},{action:'add_edge',source:'A',target:'B'}]});assert.equal(h.commits,1);const before=copy(h.read().model);await assert.rejects(edit.execute({expectedRevision:1,operations:[{action:'delete',ids:['A']}]}),/Stale/);const controller=new AbortController();controller.abort();await assert.rejects(edit.execute({expectedRevision:2,operations:[{action:'delete',ids:['A']}]},{signal:controller.signal}),/cancelled/);await assert.rejects(edit.execute({expectedRevision:2,operations:[{action:'add_edge',source:'A',target:'missing'}]}));assert.deepEqual(h.read().model,before);assert.equal(h.commits,1);});
test('WebMCP read results are copies and exports reject unknown formats',async()=>{const h=host(),tools=createDiagramTools(h),get=tools.find(t=>t.name==='get_diagram');const result=await get.execute({});result.model.nodes.push(node('bad'));assert.equal(h.read().model.nodes.length,0);assert.equal(get.annotations.readOnlyHint,true);assert((await tools.find(t=>t.name==='export_diagram').execute({format:'mermaid-portable'})).content.startsWith('flowchart'));await assert.rejects(tools.find(t=>t.name==='export_diagram').execute({format:'js'}));});
test('registration uses document API and lifecycle signal; absence/failure stays optional',async()=>{const registrations=[],context={registerTool:async(tool,options)=>registrations.push({tool,options})};const registration=await registerWebMCP(host(),{document:{modelContext:context},navigator:{}});assert(registration.available);assert.equal(registrations.length,5);registration.dispose();assert(registrations.every(r=>r.options.signal.aborted));assert(!(await registerWebMCP(host(),{document:{},navigator:{}})).available);let warned=false;const failed=await registerWebMCP(host(),{document:{modelContext:{registerTool:async()=>{throw new Error('unsupported');}}},navigator:{},onError:()=>warned=true});assert(!failed.available&&warned);});
test.after(()=>router.dispose());
