import {initializeMermaid,importMermaid,mergeSource,layoutModel} from '../mermaid-adapter.mjs?v=icons-3';
import {toMermaid,copy,emptyModel,object,items,moveSelection} from '../core.mjs?v=icons-3';
import {presentationModel} from '../presentation.mjs';
import {createScene,exportSvg} from '../scene.mjs?v=icons-3';
import {AvoidLib} from '../vendor/libavoid/dist/index.js';
import {DiagramRouter} from '../routing.mjs?v=icons-3';
const out=document.getElementById('results'),results=[];
function assert(condition,message){if(!condition)throw new Error(message);}
async function test(name,fn){try{await fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});}out.textContent=JSON.stringify(results,null,2);}
initializeMermaid();await AvoidLib.load(new URL('../vendor/libavoid/dist/libavoid.wasm',import.meta.url).href);const router=new DiagramRouter(AvoidLib.getInstance());
let model;
const source='flowchart LR\n subgraph Team["`**Team**`"]\n Human@{ icon: "studio:human", label: "Human" }\n Agent@{ icon: "studio:agent", label: "**Agent**", form: "rounded" }\n end\n Document@{ shape: doc, label: "Document" }\n Cloud@{ shape: cloud, label: "Cloud" }\n Person@{ shape: person, label: "Person" }\n Hex@{ shape: hex, label: "Hexagon" }\n Stadium([Stadium])\n Human request@-->|"`*requests*`"| Agent\n Agent writes@--> Document\n Document sync@--> Cloud\n Person uses@--> Hex\n Hex ends@--> Stadium\n classDef green fill:#d8f4df,color:#174a2b,stroke:#287b45,stroke-width:2px\n class Agent,Cloud green';
await test('standard shapes, icon pack, Markdown, class and explicit styles import',async()=>{model=await importMermaid(source);assert(model.nodes.length===7,'seven nodes');assert(object(model,'Agent').icon==='studio:agent','agent icon');assert(object(model,'Cloud').backgroundColor==='#d8f4df','class fill');assert(object(model,'Cloud').borderWidth===2,'class stroke');router.route(model);});
await test('all supported fields roundtrip through native Mermaid',async()=>{const next=await importMermaid(toMermaid(model));for(const n of items(model)){const actual=object(next,n.id);for(const k of ['label','shape','icon','textFormat','backgroundColor','fontColor','borderColor','borderWidth'])assert(actual[k]===n[k],`${n.id}.${k}: ${actual[k]} vs ${n[k]}`);}for(const edge of model.edges){const actual=object(next,edge.id);assert(actual.label===edge.label&&actual.textFormat===edge.textFormat,'edge text roundtrip');}});
await test('portable export renders with traditional shapes and restores editor metadata',async()=>{const source=toMermaid(model,{portable:true});assert(!source.includes('@{')&&!source.includes('@-->'),'traditional syntax');const {svg}=await mermaid.render('portable-render',source);assert(svg.includes('Human')&&svg.includes('Agent'),'labels render');const next=await importMermaid(source);assert(object(next,'Agent').shape==='icon'&&object(next,'Document').shape==='document','shapes restored');assert(next.edges[0].id==='request','edge IDs restored');});
await test('unknown icon pack renders a native fallback and keeps node/edge',async()=>{const m=await importMermaid('flowchart LR\n A@{ icon: "missing:agent", label: "Unknown actor" }\n A --> B[Target]');const scene=createScene(m,router.route(m));assert(scene.querySelector('.actor-icon').children.length>0,'canvas question mark');const {svg}=await mermaid.render('missing-render',toMermaid(m));assert(svg.includes('Unknown actor')&&svg.includes('Target'),'Mermaid labels survive');});
await test('styled text is visible in canvas SVG and PNG rasterizes without assets',async()=>{const svg=exportSvg(model,router.route(model));assert(svg.text.includes('font-weight="700"')&&svg.text.includes('font-style="italic"'),'emphasis retained');assert(!svg.text.includes('>**Agent**<'),'no raw emphasis markers');const blob=new Blob([svg.text],{type:'image/svg+xml'}),url=URL.createObjectURL(blob);try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=500;canvas.height=300;canvas.getContext('2d').drawImage(image,0,0,500,300);assert((await new Promise(r=>canvas.toBlob(r))).size>1000,'PNG pixels generated');}finally{URL.revokeObjectURL(url);}});
await test('nested collapse hides internal edges, retains endpoint identities and geometry',async()=>{const m=copy(model);object(m,'Team').collapsed=true;const original=copy(m),visible=presentationModel(m),routes=router.route(m),scene=createScene(m,routes);assert(!scene.querySelector('[data-object-id="Human"]')&&!routes.has('request'),'hidden nodes/internal edges');assert(routes.has('writes')&&visible.edges.find(e=>e.id==='writes').source==='Team','external edge remapped');assert(JSON.stringify(m)===JSON.stringify(original),'presentation immutable');const next=await importMermaid(toMermaid(m));assert(object(next,'Team').collapsed,'native collapse restored');assert(next.nodes.length===7&&next.edges.length===5,'all hidden objects retained');moveSelection(m,new Set(['Team']),30,40,{expand:false});assert(object(m,'Agent').x===object(original,'Agent').x+30,'descendant moves once');object(m,'Team').collapsed=false;assert(presentationModel(m)===m,'expanded model direct');});
await test('styles override matching prior colors without losing manual positions',async()=>{const old=copy(model),cloud=object(old,'Cloud');cloud.x+=40;const incoming=await importMermaid(toMermaid(old).replace('style Cloud fill:#d8f4df','style Cloud fill:#00aa00'));const merged=mergeSource(old,incoming);assert(object(merged,'Cloud').backgroundColor==='#00aa00','explicit style wins');assert(Math.abs(object(merged,'Cloud').x+object(merged,'Cloud').width/2-cloud.x-cloud.width/2)<.01,'manual center retained');});
await test('unsupported CSS and rich text are rejected clearly',async()=>{for(const source of ['flowchart TD\n A[A]\n style A opacity:0.5','flowchart TD\n A["`[link](https://example.com)`"]','flowchart TD\n A@{ shape: tri, label: "Unsupported" }']){let rejected=false;try{await importMermaid(source);}catch{rejected=true;}assert(rejected,source);}});
await test('plain modern-shape and icon labels stay literal in native exports and reimports',async()=>{const m=emptyModel();for(const [i,shape]of ['icon','person','cloud','document','hexagon'].entries())m.nodes.push({id:'Literal'+i,label:'**Literal** _name_ \\*',shape,icon:'studio:agent',textFormat:'plain',parentId:null,x:i*220,y:0,width:160,height:100});const source=toMermaid(m),next=await importMermaid(source);for(const n of m.nodes)assert(object(next,n.id).label===n.label&&object(next,n.id).textFormat==='plain','literal '+n.id);const {svg}=await mermaid.render('literal-render',source);const parsed=new DOMParser().parseFromString(svg,'image/svg+xml');assert(!parsed.querySelector('strong,em'),'plain export has no emphasis');});
await test('source changes to a displayed description survive editor annotations',async()=>{const m=emptyModel();m.nodes.push({id:'A',label:'Identity label',description:'Original description',showDescription:true,parentId:null,shape:'rectangle',x:0,y:0,width:200,height:60});const source=toMermaid(m).replace('A["Original description"]','A["Updated description"]'),next=await importMermaid(source);assert(next.nodes[0].label==='Identity label','identity label preserved');assert(next.nodes[0].description==='Updated description','source description updated');});
await test('explicit edge dash styles and bold text sizing survive real rendering',async()=>{const dashed=await importMermaid('flowchart TD\n A[A]-->B[B]\n linkStyle 0 stroke-dasharray:6 4');assert(dashed.edges[0].style==='dashed','imported dash style');for(const shape of ['circle','diamond']){const m=emptyModel();m.settings.fontSize=48;m.nodes.push({id:'N',label:'**Large bold word**',textFormat:'markdown',shape,parentId:null,x:0,y:0,width:120,height:80,manualSize:{width:120,height:80}});const {resizeNode}=await import('../core.mjs?v=icons-3');resizeNode(m.nodes[0],48);const host=document.createElementNS('http://www.w3.org/2000/svg','svg');host.append(createScene(m,new Map(),new Set(),{controls:false}));document.body.append(host);try{const b=host.querySelector('text').getBBox(),n=m.nodes[0];for(const x of [b.x,b.x+b.width])for(const y of [b.y,b.y+b.height])assert(shape==='circle'?Math.hypot(x-n.width/2,y-n.height/2)<n.width/2:Math.abs(x-n.width/2)/(n.width/2)+Math.abs(y-n.height/2)/(n.height/2)<1,'bold fits '+shape);}finally{host.remove();}}});
document.body.dataset.complete='true';document.body.dataset.passed=String(results.filter(r=>r.pass).length);document.body.dataset.failed=String(results.filter(r=>!r.pass).length);router.dispose();
