const frame=document.getElementById('app'),out=document.getElementById('results'),results=[];
const wait=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn){for(let i=0;i<500;i++){if(fn())return;await wait(20);}throw new Error('Timed out waiting for editor');}
await until(()=>frame.contentDocument?.getElementById('loading')?.hidden);const win=frame.contentWindow,doc=frame.contentDocument,$=id=>doc.getElementById(id),viewport=$('viewport');
viewport.setPointerCapture=()=>{};viewport.hasPointerCapture=()=>false;win.showOpenFilePicker=undefined;win.showSaveFilePicker=undefined;
let blobs=[];const create=win.URL.createObjectURL.bind(win.URL);win.URL.createObjectURL=blob=>{blobs.push(blob);return create(blob);};win.HTMLAnchorElement.prototype.click=function(){};
const assert=(ok,msg)=>{if(!ok)throw new Error(msg);};async function test(name,fn){try{await fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});}out.textContent=JSON.stringify(results,null,2);}
const input=(id,value)=>{const el=$(id);el.value=value;el.dispatchEvent(new win.Event('input',{bubbles:true}));el.dispatchEvent(new win.Event('change',{bubbles:true}));};
const pointer=(type,x,y,target=viewport)=>target.dispatchEvent(new win.PointerEvent(type,{bubbles:true,isPrimary:true,button:0,pointerId:4,clientX:x,clientY:y}));
function pick(id){const target=doc.querySelector(`.diagram-node[data-object-id="${id}"],.zone-title[data-object-id="${id}"],.diagram-edge[data-object-id="${id}"]`),b=target.getBoundingClientRect();pointer('pointerdown',b.x+b.width/2,b.y+b.height/2,target);pointer('pointerup',b.x+b.width/2,b.y+b.height/2);}
async function saved(){blobs=[];$('btn-save').click();await until(()=>blobs.length);return JSON.parse(await blobs.at(-1).text());}
async function apply(source){input('editor',source);$('btn-apply').click();await until(()=>$('loading').hidden);assert($('error-banner').hidden,$('error-message').textContent);}
const source='flowchart LR\n subgraph Team["`**Team**`"]\n Human@{ icon: "studio:human", label: "Human" }\n Agent@{ icon: "studio:agent", label: "**Agent**", form: "rounded" }\n end\n Doc@{ shape: doc, label: "Document" }\n Human request@-->|"`*requests*`"| Agent\n Agent writes@--> Doc\n classDef green fill:#d8f4df,color:#174a2b,stroke:#287b45,stroke-width:2px\n class Agent green';
await test('startup is blank and source panel has no examples',async()=>{assert(doc.querySelectorAll('.diagram-node,.diagram-zone').length===0,'blank canvas');assert(!doc.querySelector('.examples'),'examples removed');});
await test('actors, styled labels and compact icon properties are editable',async()=>{await apply(source);pick('Agent');assert($('property-icon-reference').value==='studio:agent','icon property');assert($('property-text-format').value==='markdown','Markdown imported');assert(doc.querySelector('.diagram-node[data-object-id="Agent"] .actor-icon'),'actor glyph');input('property-icon-reference','studio:server');assert((await saved()).nodes.find(n=>n.id==='Agent').icon==='studio:server','icon changed');$('btn-undo').click();assert((await saved()).nodes.find(n=>n.id==='Agent').icon==='studio:agent','icon undo');});
await test('shape flyout shows every new shape preview and switches presets',async()=>{pick('Agent');const shape=doc.querySelector('#selection-bar [data-command="shape"]');shape.click();assert(doc.querySelectorAll('.menu-popover [data-command="set-shape"] .menu-shape-preview').length===13,'shape previews');doc.querySelector('.menu-popover [data-command="set-shape"][aria-label="Human actor"]').click();assert((await saved()).nodes.find(n=>n.id==='Agent').icon==='studio:human','preset changed');$('btn-undo').click();});
await test('Markdown properties render emphasis and preserve description headers',async()=>{pick('Human');input('property-text-format','markdown');input('property-label','***Human***\n*requester*');const group=doc.querySelector('.diagram-node[data-object-id="Human"]');assert(group.querySelector('[font-weight="700"][font-style="italic"]'),'combined emphasis');input('property-description','**A person** using the service');$('property-show-description').click();assert(doc.querySelector('.diagram-node[data-object-id="Human"]').textContent.includes('A person'),'description displayed');const m=await saved();assert(m.nodes.find(n=>n.id==='Human').label==='***Human***\n*requester*','label intact');});
await test('collapsing a zone preserves contents and reroutes external edge; Undo restores',async()=>{pick('Team');const before=await saved();$('btn-collapse').click();assert(!doc.querySelector('.diagram-node[data-object-id="Agent"]'),'child hidden');assert(!doc.querySelector('[data-edge-id="request"]'),'internal edge hidden');assert(doc.querySelector('[data-edge-id="writes"]'),'external edge visible');const collapsed=await saved();assert(collapsed.edges.find(e=>e.id==='writes').source==='Agent','real endpoint retained');assert(JSON.stringify(collapsed.nodes)===JSON.stringify(before.nodes),'node geometry untouched');$('btn-undo').click();assert(doc.querySelector('.diagram-node[data-object-id="Agent"]'),'Undo expanded');});
await test('canvas collapse button, movement, expand and Hierarchy selection preserve children',async()=>{pick('Team');const button=doc.querySelector('[data-collapse="Team"]'),b=button.getBoundingClientRect();pointer('pointerdown',b.x+b.width/2,b.y+b.height/2,button);const before=await saved(),body=doc.querySelector('.diagram-zone[data-object-id="Team"] rect'),box=body.getBoundingClientRect(),scale=before.settings.view.scale;pointer('pointerdown',box.x+30,box.y+45,body);pointer('pointermove',box.x+60,box.y+65);await wait(40);pointer('pointerup',box.x+60,box.y+65);const after=await saved(),parent=after.zones[0],old=before.zones[0];for(const child of before.nodes.filter(n=>n.parentId==='Team')){const moved=after.nodes.find(n=>n.id===child.id);assert(Math.abs(moved.x-child.x-(parent.x-old.x))<.01&&Math.abs(moved.y-child.y-(parent.y-old.y))<.01,'child moved once');}doc.querySelector('.tree-row[data-tree-id="Agent"] .tree-object').click();assert(doc.querySelector('.diagram-node[data-object-id="Agent"]'),'ancestor expanded to reveal');assert(!(await saved()).zones[0].collapsed,'collapse state expanded');});
await test('actor container places icon and formatted description in header above children',async()=>{pick('Agent');$('property-container-node').click();input('property-description','**Agent coordinator**');$('property-show-description').click();const before=await saved(),a=before.nodes.find(n=>n.id==='Agent');const title=doc.querySelector('.node-container-title[data-object-id="Agent"]'),glyph=doc.querySelector('.container-node[data-object-id="Agent"] .actor-icon');assert(title&&glyph,'title and icon');assert(title.textContent==='Agent coordinator','formatted title text');pick('Human');input('property-parent-zone','Agent');const m=await saved(),child=m.nodes.find(n=>n.id==='Human'),parent=m.nodes.find(n=>n.id==='Agent');assert(child.parentId==='Agent'&&child.y>parent.y+40,'child below title');});
await test('new fields survive JSON open and nested clipboard paste',async()=>{const before=await saved(),json=JSON.stringify(before),file=new win.File([json],'extensions.json',{type:'application/json'}),transfer=new win.DataTransfer();transfer.items.add(file);$('file-input').files=transfer.files;$('file-input').dispatchEvent(new win.Event('change',{bubbles:true}));await until(()=>$('file-info').textContent.includes('extensions.json')&&$('loading').hidden);pick('Agent');const data=new win.DataTransfer(),copyEvent=new win.ClipboardEvent('copy',{bubbles:true,clipboardData:data});viewport.dispatchEvent(copyEvent);const copied=data.getData('text/plain');assert(copied.includes('studio:agent'),'actor included');viewport.dispatchEvent(new win.ClipboardEvent('paste',{bubbles:true,clipboardData:data}));const pasted=await saved();assert(pasted.nodes.length>before.nodes.length,'nested actor copied');assert(pasted.nodes.filter(n=>n.icon==='studio:agent').length===2,'icon persisted');});
const context=doc.modelContext||win.navigator.modelContext;let registered=[];
if(context?.getTools&&context?.executeTool){await until(()=>doc.body.dataset.webmcp==='available');registered=await context.getTools();}
async function call(name,input){const tool=registered.find(t=>t.name===name);assert(tool,`native tool ${name}`);const result=await context.executeTool(tool,input);return typeof result==='string'?JSON.parse(result):result;}
await test('native WebMCP registers five tools and reports stable diagram/file context',async()=>{assert(registered.length===5,'five native tools');const read=await call('get_diagram',{});assert(read.revision>=1&&read.model.nodes.length>0,'model context');assert(!JSON.stringify(read).includes('createWritable'),'no file handle exposed');});
await test('native agent batch creates connected actors with one-step Undo/Redo',async()=>{const before=await call('get_diagram',{}),result=await call('edit_diagram',{expectedRevision:before.revision,operations:[{action:'add_node',id:'ToolHuman',shape:'human',x:1200,y:100},{action:'add_node',id:'ToolAgent',shape:'agent',x:1450,y:100},{action:'add_edge',id:'ToolLink',source:'ToolHuman',target:'ToolAgent',label:'**works**',properties:{textFormat:'markdown'}}]});assert(!result.error,result.error);assert(doc.querySelector('.diagram-node[data-object-id="ToolAgent"]'),'agent visible');$('btn-undo').click();assert(!doc.querySelector('[data-object-id="ToolHuman"]')&&!doc.querySelector('[data-object-id="ToolAgent"]'),'single Undo removes batch');$('btn-redo').click();assert(doc.querySelector('[data-edge-id="ToolLink"]'),'single Redo restores batch');});
await test('native stale/invalid requests and source drafts reject without partial edits',async()=>{const before=await call('get_diagram',{}),stale=await call('edit_diagram',{expectedRevision:before.revision-1,operations:[{action:'delete',ids:['ToolAgent']}]});assert(stale.ok===false&&stale.error.includes('Stale'),'stale rejection');const invalid=await call('edit_diagram',{expectedRevision:before.revision,operations:[{action:'add_node',id:'Partial'},{action:'add_edge',source:'Partial',target:'missing'}]});assert(invalid.ok===false,'invalid rejection');assert(!(await call('get_diagram',{})).model.nodes.some(n=>n.id==='Partial'),'no partial node');input('editor','flowchart TD\n Draft[Draft]');const blocked=await call('edit_diagram',{expectedRevision:before.revision,operations:[{action:'delete',ids:['ToolAgent']}]});assert(blocked.ok===false&&blocked.error.includes('draft'),'draft respected');$('btn-discard').click();});
await test('native arrangement, apply source and read-only exports share the real editor',async()=>{let read=await call('get_diagram',{});const arranged=await call('arrange_diagram',{expectedRevision:read.revision,action:'top',ids:['ToolHuman','ToolAgent']});assert(!arranged.error,'arrangement');const a=arranged.model.nodes.find(n=>n.id==='ToolHuman'),b=arranged.model.nodes.find(n=>n.id==='ToolAgent');assert(Math.abs(a.y-b.y)<.01,'aligned');const exported=await call('export_diagram',{format:'mermaid-portable'});assert(exported.content.includes('ToolHuman')&&!exported.content.includes('@{'),'portable source');const svg=await call('export_diagram',{format:'svg'});assert(svg.content.includes('actor-icon'),'SVG actors');const next=await call('apply_mermaid',{expectedRevision:arranged.revision,source:exported.content});assert(!next.error&&next.model.nodes.find(n=>n.id==='ToolAgent').icon==='studio:agent','source restored');});
await test('SVG and PNG download handlers render current styled actor layout',async()=>{blobs=[];$('export-format').value='svg';$('btn-export').click();await until(()=>blobs.length);assert((await blobs.at(-1).text()).includes('actor-icon'),'SVG actor');blobs=[];$('export-format').value='png';$('btn-export').click();await until(()=>blobs.some(b=>b.type==='image/png'));assert(blobs.at(-1).size>1000,'PNG downloaded');});
await test('opening identical content as a new file invalidates the previous agent revision',async()=>{await saved();const before=await call('get_diagram',{}),file=new win.File([JSON.stringify(before.model)],'same-content.json',{type:'application/json'}),transfer=new win.DataTransfer();transfer.items.add(file);$('file-input').files=transfer.files;$('file-input').dispatchEvent(new win.Event('change',{bubbles:true}));await until(()=>$('file-info').textContent.includes('same-content.json')&&$('loading').hidden);const opened=await call('get_diagram',{});assert(opened.revision>before.revision,'new document advances revision');const stale=await call('edit_diagram',{expectedRevision:before.revision,operations:[{action:'delete',ids:['ToolAgent']}]});assert(stale.ok===false&&stale.error.includes('Stale'),'request for previous document rejected');assert((await call('get_diagram',{})).model.nodes.some(n=>n.id==='ToolAgent'),'new file untouched');});
out.dataset.complete='true';out.dataset.passed=String(results.filter(r=>r.pass).length);out.dataset.failed=String(results.filter(r=>!r.pass).length);out.textContent=JSON.stringify({passed:results.filter(r=>r.pass).length,total:results.length,results},null,2);await saved();
