import test from 'node:test';
import assert from 'node:assert/strict';
import {createFileSession,createRecoveryStore} from '../files.mjs';
import {readFile,writeFile,mkdtemp,rm,rename} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};};
function handle(name='diagram.json',initial='old'){let disk=initial,grant='granted',fail=null,wait=null;const writes=[];return{name,writes,setDisk:text=>disk=text,setGrant:g=>grant=g,setFailure:e=>fail=e,setWait:w=>wait=w,disk:()=>disk,queryPermission:async()=>grant,requestPermission:async()=>grant,getFile:async()=>({text:async()=>disk}),async createWritable(){let pending;return{async write(text){writes.push(text);if(wait)await wait.promise;if(fail)throw fail;pending=text;},async close(){if(fail)throw fail;disk=pending;},async abort(){pending=null;}};}};}
function fixture(opts={}){const timers=new Map();let id=0;const errors=[];const s=createFileSession({onError:e=>errors.push(e),setTimer:fn=>{timers.set(++id,fn);return id;},clearTimer:i=>timers.delete(i),...opts});return{s,timers,errors,tick:async()=>{const f=[...timers.values()];timers.clear();f.forEach(fn=>fn());await s.settle();}};}
test('writes close successfully before advancing the saved checkpoint',async()=>{const h=handle(),f=fixture();f.s.setDocument({content:'old',handle:h,baseline:'old',saved:true});f.s.update('edited');const wait=deferred();h.setWait(wait);const write=f.s.save();await new Promise(r=>setTimeout(r,0));assert.equal(f.s.state().saving,true);assert.equal(f.s.state().dirty,true);assert.equal(h.disk(),'old');wait.resolve();assert.equal(await write,true);assert.equal(h.disk(),'edited');assert.equal(f.s.state().dirty,false);assert.equal(f.s.state().label,'Saved');});
test('edits during a save remain dirty and serialize after the first write',async()=>{const h=handle(),f=fixture();f.s.setDocument({content:'old',handle:h,baseline:'old',saved:true});const wait=deferred();h.setWait(wait);f.s.update('first');const first=f.s.save();f.s.update('second');const second=f.s.save();wait.resolve();await first;assert.equal(f.s.state().dirty,true);await second;assert.equal(h.disk(),'second');assert.equal(f.s.state().dirty,false);assert.deepEqual(h.writes,['first','second']);});
test('optional autosave debounces changes and respects undo back to the disk checkpoint',async()=>{const h=handle(),f=fixture();f.s.setDocument({content:'old',handle:h,baseline:'old',saved:true});f.s.update('first');assert.equal(f.timers.size,0);f.s.setAutosave(true);f.s.update('second');f.s.update('third');assert.equal(f.timers.size,1);await f.tick();assert.deepEqual(h.writes,['third']);f.s.update('fourth');f.s.update('third');assert.equal(f.timers.size,0);assert.equal(f.s.state().dirty,false);});
test('turning autosave off cancels a pending timer',async()=>{const h=handle(),f=fixture();f.s.setDocument({content:'old',handle:h,baseline:'old',saved:true});f.s.setAutosave(true);f.s.update('edited');f.s.setAutosave(false);await f.tick();assert.equal(h.disk(),'old');});
test('external content changes pause saves even with identical metadata',async()=>{const h=handle(),f=fixture();f.s.setDocument({content:'old',handle:h,baseline:'old',saved:true});f.s.setAutosave(true);h.setDisk('external');f.s.update('mine');await f.tick();assert.equal(h.disk(),'external');assert.equal(f.s.state().paused,'conflict');assert.equal(f.errors[0].name,'FileConflict');assert.equal(f.s.state().dirty,true);f.s.update('still mine');assert.equal(f.timers.size,0);await f.s.save({overwrite:true});assert.equal(h.disk(),'still mine');assert.equal(f.s.state().paused,null);});
test('autosave never prompts for permission and a manual retry reconnects',async()=>{const h=handle(),f=fixture();let requests=0;h.requestPermission=async()=>{requests++;h.setGrant('granted');return'granted';};f.s.setDocument({content:'old',handle:h,baseline:'old',saved:true});f.s.setAutosave(true);h.setGrant('prompt');f.s.update('edit');await f.tick();assert.equal(requests,0);assert.equal(f.s.state().paused,'permission');assert.equal(h.disk(),'old');await f.s.save();assert.equal(requests,1);assert.equal(h.disk(),'edit');});
test('failed writes preserve checkpoint, edits and connection and pause repeated retries',async()=>{const h=handle(),f=fixture();f.s.setDocument({content:'old',handle:h,baseline:'old',saved:true});f.s.setAutosave(true);h.setFailure(new Error('Disk full'));f.s.update('edited');await f.tick();assert.equal(f.s.state().dirty,true);assert.equal(f.s.state().paused,'write');assert.equal(h.disk(),'old');assert.equal(f.s.state().handle,h);f.s.update('more');assert.equal(f.timers.size,0);h.setFailure(null);await f.s.save();assert.equal(h.disk(),'more');});
test('Save as binds a new file only after success and preserves the old connection on failure',async()=>{const original=handle(),next=handle('next.json',''),f=fixture();f.s.setDocument({content:'old',handle:original,baseline:'old',saved:true});f.s.update('edited');next.setFailure(new Error('Disk full'));assert.equal(await f.s.save({handle:next,baseline:''}),false);assert.equal(f.s.state().handle,original);assert.equal(original.disk(),'old');next.setFailure(null);await f.s.save({handle:next,baseline:''});assert.equal(f.s.state().handle,next);assert.equal(f.s.state().name,'next.json');assert.equal(next.disk(),'edited');f.s.update('later');await f.s.save();assert.equal(next.disk(),'later');assert.equal(original.disk(),'old');});
test('switching documents cancels queued writes without ever using the new handle for old text',async()=>{const h=handle(),other=handle('other.json','other'),f=fixture(),wait=deferred();h.setWait(wait);f.s.setDocument({content:'old',handle:h,baseline:'old',saved:true});f.s.update('first');const a=f.s.save();await new Promise(r=>setTimeout(r,0));f.s.update('queued');const b=f.s.save();f.s.setDocument({content:'other',handle:other,baseline:'other',saved:true});wait.resolve();await a;assert.equal(await b,false);assert.equal(other.disk(),'other');assert.equal(f.s.state().text,'other');assert.equal(f.s.state().dirty,false);});
test('settling a document transition cancels its autosave timer and waits for the old write',async()=>{const h=handle(),f=fixture(),wait=deferred();h.setWait(wait);f.s.setDocument({content:'old',handle:h,baseline:'old',saved:true});f.s.setAutosave(true);f.s.update('edit');const write=f.s.save();let settled=false;const settling=f.s.settle().then(()=>settled=true);await new Promise(r=>setTimeout(r,0));assert.equal(settled,false);wait.resolve();await write;await settling;assert.equal(settled,true);assert.equal(f.timers.size,0);});
test('autosave preference survives New and recovery while disconnected documents cannot write',()=>{const f=fixture();f.s.setAutosave(true);f.s.setDocument({content:'recovered',filename:'original.json'});assert.equal(f.s.state().connected,false);assert.equal(f.s.state().dirty,true);assert.equal(f.s.state().autosave,true);assert.equal(f.timers.size,0);const h=handle();f.s.setDocument({content:'edit',handle:h,baseline:'old'});assert.equal(f.s.state().autosave,true);assert.equal(f.timers.size,1);});
test('download fallback identifies a copy rather than claiming a verified disk save',()=>{const f=fixture();f.s.setDocument({content:'edit'});f.s.markDownloaded('edit');assert.equal(f.s.state().label,'Downloaded copy');assert.equal(f.s.state().connected,false);f.s.update('newer');assert.equal(f.s.state().dirty,true);});
test('per-tab recovery preserves other tabs, prefers current-tab refresh and ignores invalid entries',()=>{const map=new Map(),storage={setItem:(k,v)=>map.set(k,v),getItem:k=>map.get(k),removeItem:k=>map.delete(k),get length(){return map.size;},key:i=>[...map.keys()][i]};const a=createRecoveryStore(storage,'a'),b=createRecoveryStore(storage,'b');a.write({content:'mine',filename:'a.json'});b.write({content:'other'});assert.equal(a.find().content,'mine');a.clear();assert.equal(b.find().content,'other');map.set('diagram-studio.recovery.v1.bad','not JSON');assert.equal(b.find().content,'other');b.remove(b.find());assert.equal(b.find(),null);});
test('real disk adapter writes JSON atomically and detects an external edit',async()=>{const dir=await mkdtemp(join(tmpdir(),'diagram-studio-files-')),path=join(dir,'working.json');try{await writeFile(path,'{"version":1}');const h={name:'working.json',getFile:async()=>({text:()=>readFile(path,'utf8')}),async createWritable(){const temp=path+'.tmp';return{write:content=>writeFile(temp,content),close:()=>rename(temp,path),abort:()=>rm(temp,{force:true})};}};const f=fixture();f.s.setDocument({content:'{"version":1}',handle:h,baseline:'{"version":1}',saved:true});f.s.update('{"version":1,"notes":"中文 🚀"}');assert.equal(await f.s.save(),true);assert.equal(await readFile(path,'utf8'),f.s.state().text);await writeFile(path,'{"external":true}');f.s.update('{"mine":true}');assert.equal(await f.s.save(),false);assert.equal(await readFile(path,'utf8'),'{"external":true}');}finally{await rm(dir,{recursive:true,force:true});}});
test('an automatic snapshot superseded while queued is skipped instead of briefly reverting the disk',async()=>{const h=handle(),f=fixture(),wait=deferred();h.setWait(wait);f.s.setDocument({content:'old',handle:h,baseline:'old',saved:true});f.s.update('first');const first=f.s.save();await new Promise(r=>setTimeout(r,0));f.s.update('second');const second=f.s.save({automatic:true});f.s.update('first');wait.resolve();await first;assert.equal(await second,false);assert.equal(h.disk(),'first');assert.deepEqual(h.writes,['first']);assert.equal(f.s.state().dirty,false);});
test('a new generation does not claim Saving for an old generation that is finishing',async()=>{const h=handle(),f=fixture(),wait=deferred();h.setWait(wait);f.s.setDocument({content:'old',handle:h,baseline:'old',saved:true});f.s.update('first');const first=f.s.save();await new Promise(r=>setTimeout(r,0));f.s.setDocument({content:'new',saved:true});assert.equal(f.s.state().saving,false);wait.resolve();await first;assert.equal(f.s.state().saving,false);});
test('startup recovery can stay in its own tab while explicit recovery discovery retains other records',()=>{const map=new Map(),storage={setItem:(k,v)=>map.set(k,v),getItem:k=>map.get(k),removeItem:k=>map.delete(k),get length(){return map.size;},key:i=>[...map.keys()][i]};const a=createRecoveryStore(storage,'a'),b=createRecoveryStore(storage,'b');a.write({content:'active tab'});assert.equal(b.find({ownOnly:true}),null);const other=b.find();assert.equal(other.content,'active tab');assert.equal(b.owns(other),false);assert.equal(a.owns(other),true);});
