import {initializeMermaid,importMermaid} from '../mermaid-adapter.mjs?v=icons-3';
import {toMermaid} from '../core.mjs?v=icons-3';
import {createScene,exportSvg} from '../scene.mjs?v=icons-3';
import {iconData} from '../icons.mjs?v=icons-3';
const frame=document.getElementById('app'),out=document.getElementById('results'),results=[];
const wait=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn){for(let i=0;i<600;i++){if(fn())return;await wait(20);}throw new Error('Timed out waiting for editor');}
const assert=(ok,message)=>{if(!ok)throw new Error(message);};async function test(name,fn){try{await fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});}out.textContent=JSON.stringify(results,null,2);}
initializeMermaid();
const samples=['tabler:ai-agent','lucide:bot','carbon:ai-agent-invocation','ph:robot-duotone','fluent-color:agents-24','logos:google'];
const source='flowchart LR\n'+samples.map((ref,i)=>` N${i}@{ icon: "${ref}", label: "${ref}", h: 48 }`).join('\n');let model;
await test('all six packs import through real Mermaid using local loaders',async()=>{model=await importMermaid(source);assert(model.nodes.length===6,'six nodes');for(const ref of samples)assert(iconData(ref).available,ref);const scene=createScene(model,new Map());assert(scene.querySelectorAll('.actor-icon[data-icon]').length===6,'canvas glyphs');assert(scene.querySelector('[data-icon="logos:google"]').getAttribute('viewBox').split(' ')[2]>100,'wide logo view box');});
await test('native Mermaid roundtrip retains every pack reference',async()=>{const next=await importMermaid(toMermaid(model));assert(samples.every((ref,i)=>next.nodes.find(n=>n.id==='N'+i).icon===ref),'icon references roundtrip');});
await test('portable Mermaid renders fallback shapes and restores icon metadata',async()=>{const source=toMermaid(model,{portable:true});assert(!source.includes('@{'),'traditional shape syntax');const rendered=await mermaid.render('all-packs-portable',source);assert(rendered.svg.includes('fluent-color:agents-24'),'readable labels');const next=await importMermaid(source);assert(next.nodes.every(n=>n.shape==='icon'),'icon shape restored');assert(samples.every((ref,i)=>next.nodes.find(n=>n.id==='N'+i).icon===ref),'pack references restored');});
await test('SVG and PNG embed wide logos and repeated gradient icons without outside assets',async()=>{const extra={...model.nodes.find(n=>n.id==='N4'),id:'SecondFluent',x:0,y:200};const exported=exportSvg({...model,nodes:[...model.nodes,extra]},new Map());const svg=new DOMParser().parseFromString(exported.text,'image/svg+xml');assert(!svg.querySelector('parsererror'),'valid standalone SVG');const ids=[...svg.querySelectorAll('[id]')].map(n=>n.id);assert(new Set(ids).size===ids.length,'unique SVG IDs');assert(!svg.querySelector('image,script,foreignObject'),'embedded artwork');const url=URL.createObjectURL(new Blob([exported.text],{type:'image/svg+xml'}));try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=800;canvas.height=400;canvas.getContext('2d').drawImage(image,0,0,800,400);assert((await new Promise(r=>canvas.toBlob(r))).size>1000,'PNG renders');}finally{URL.revokeObjectURL(url);}});
await until(()=>frame.contentDocument?.getElementById('loading')?.hidden);const win=frame.contentWindow,doc=frame.contentDocument,$=id=>doc.getElementById(id),viewport=$('viewport');
viewport.setPointerCapture=()=>{};viewport.hasPointerCapture=()=>false;win.showOpenFilePicker=undefined;win.showSaveFilePicker=undefined;
let blobs=[];const create=win.URL.createObjectURL.bind(win.URL);win.URL.createObjectURL=blob=>{blobs.push(blob);return create(blob);};win.HTMLAnchorElement.prototype.click=function(){};
const input=(id,value)=>{const el=$(id);el.value=value;el.dispatchEvent(new win.Event('input',{bubbles:true}));el.dispatchEvent(new win.Event('change',{bubbles:true}));};
async function saved(){blobs=[];$('btn-save').click();await until(()=>blobs.length);return JSON.parse(await blobs.at(-1).text());}
function pick(id){const target=doc.querySelector(`.diagram-node[data-object-id="${id}"]`),b=target.getBoundingClientRect(),data={bubbles:true,isPrimary:true,button:0,pointerId:4,clientX:b.x+b.width/2,clientY:b.y+b.height/2};target.dispatchEvent(new win.PointerEvent('pointerdown',data));viewport.dispatchEvent(new win.PointerEvent('pointerup',data));}
async function open(){ $('property-icon').click();await until(()=>$('icon-picker-results').getAttribute('aria-busy')==='false');assert($('icon-picker').open,'dialog open'); }
async function search(value,pack=''){input('icon-picker-search',value);input('icon-picker-pack',pack);await until(()=>$('icon-picker-results').getAttribute('aria-busy')==='false');}
await test('editor source imports local packs with correct canvas view boxes',async()=>{input('editor',source);$('btn-apply').click();await until(()=>$('loading').hidden);assert($('error-banner').hidden,$('error-message').textContent);assert(doc.querySelectorAll('.actor-icon').length===6,'all glyphs');pick('N0');assert($('property-icon-reference').value===samples[0],'editable reference');});
await test('picker offers all seven packs, useful starter icons and bounded first page',async()=>{await open();assert($('icon-picker-pack').options.length===8,'all filter options');assert(doc.querySelectorAll('.icon-picker-card').length===96,'bounded DOM');for(const prefix of ['studio','tabler','lucide','carbon','ph','fluent-color','logos'])assert(doc.querySelector(`[data-icon^="${prefix}:"]`),'starter '+prefix);assert($('icon-picker-search')===doc.activeElement,'search focused');});
await test('human/agent synonyms find actual actors and exclude bottom/bottles',async()=>{await search('agent');const refs=[...doc.querySelectorAll('.icon-picker-card')].map(c=>c.dataset.icon);assert(refs.includes('tabler:ai-agent')&&refs.includes('lucide:bot'),'actors found');assert(!refs.some(ref=>/bottom|bottle/.test(ref)),'no bot substring false positives');});
await test('pack filter and multiple search words restrict visible matches',async()=>{await search('ai agent','tabler');const cards=[...doc.querySelectorAll('.icon-picker-card')];assert(cards.length>0,'results');assert(cards.every(c=>c.dataset.icon.startsWith('tabler:')),'filtered pack');assert(cards.some(c=>c.dataset.icon==='tabler:ai-agent'),'exact result');});
await test('rapid search changes discard older results',async()=>{input('icon-picker-search','database');input('icon-picker-search','redis');input('icon-picker-pack','logos');await until(()=>$('icon-picker-results').getAttribute('aria-busy')==='false');assert(doc.querySelector('[data-icon="logos:redis"]'),'latest search rendered');assert([...doc.querySelectorAll('.icon-picker-card')].every(c=>c.dataset.icon.includes('redis')),'no stale database results');});
await test('empty search is clear and cancellation preserves icon and Undo state',async()=>{await search('xyz-no-such-icon');assert(!doc.querySelector('.icon-picker-card'),'no matches');assert($('icon-picker-status').textContent.includes('No matching'),'empty state');$('icon-picker-cancel').click();assert(!$('icon-picker').open,'cancel closes');assert((await saved()).nodes.find(n=>n.id==='N0').icon===samples[0],'no mutation');assert(doc.activeElement===$('property-icon'),'focus returned');});
for(const ref of samples)await test('picker selects '+ref+' with one Undo/Redo step',async()=>{pick('N0');const previous=(await saved()).nodes.find(n=>n.id==='N0').icon;await open();await search(ref);const card=doc.querySelector(`.icon-picker-card[data-icon="${ref}"]`);assert(card,'icon exists');card.click();assert(!$('icon-picker').open,'selection closes');assert((await saved()).nodes.find(n=>n.id==='N0').icon===ref,'selection applied');if(previous!==ref){$('btn-undo').click();assert((await saved()).nodes.find(n=>n.id==='N0').icon===previous,'one undo restores');$('btn-redo').click();assert((await saved()).nodes.find(n=>n.id==='N0').icon===ref,'redo restores');}});
await test('keyboard arrows navigate cards; Escape closes without clearing the selection',async()=>{await open();await search('robot','tabler');const cards=[...doc.querySelectorAll('.icon-picker-card')];assert(cards.length>1,'navigation results');cards[0].focus();cards[0].dispatchEvent(new win.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));assert(doc.activeElement===cards[1],'arrow focus');cards[1].dispatchEvent(new win.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert(!$('icon-picker').open,'escaped dialog');assert($('property-icon-reference'),'node still selected');});
await test('Show more expands browsing without losing search or pack filter',async()=>{await open();await search('','logos');$('icon-picker-more').click();await until(()=>$('icon-picker-results').getAttribute('aria-busy')==='false');assert(doc.querySelectorAll('.icon-picker-card').length===192,'more icons');assert($('icon-picker-pack').value==='logos','filter retained');$('icon-picker-cancel').click();});
await test('JSON reopen prepares packs and SVG export contains actual artwork',async()=>{const project=await saved();$('btn-open').click();const dialog=$('file-dialog');if(dialog.open)[...$('file-dialog-actions').querySelectorAll('button')].find(b=>b.textContent==='Discard changes')?.click();const transfer=new win.DataTransfer();transfer.items.add(new win.File([JSON.stringify(project)],'icon-packs.json',{type:'application/json'}));$('file-input').files=transfer.files;$('file-input').dispatchEvent(new win.Event('change',{bubbles:true}));await until(()=>$('loading').hidden&&$('file-name').textContent==='icon-packs.json');assert($('error-banner').hidden,'file opened');blobs=[];input('export-format','svg');$('btn-export').click();await until(()=>blobs.length);const text=await blobs[0].text();assert(text.includes('data-icon="logos:google"')&&text.includes('linearGradient'),'glyphs exported');});
await test('runtime pack requests are exclusively same-origin app assets',async()=>{for(const page of [window,win]){const assets=page.performance.getEntriesByType('resource').filter(e=>/vendor\/icons\//.test(e.name));assert(assets.length>0,'local pack resources observed');assert(assets.every(e=>new URL(e.name).origin===location.origin),'all packs same-origin');}assert(doc.querySelector('meta[http-equiv="Content-Security-Policy"]').content.includes("connect-src 'self'"),'remote requests blocked by CSP');});
await test('narrow-screen picker stays within the viewport without horizontal overflow',async()=>{frame.style.width='390px';await until(()=>win.innerWidth===390);pick('N0');await open();await search('agent');const box=$('icon-picker').getBoundingClientRect(),grid=$('icon-picker-results');assert(box.left>=0&&box.right<=win.innerWidth,'dialog fits width');assert(box.top>=0&&box.bottom<=win.innerHeight,'dialog fits height');assert(grid.scrollWidth<=grid.clientWidth,'grid does not overflow horizontally');assert($('icon-picker-search').getBoundingClientRect().height>=44,'touch-size search field');$('icon-picker-cancel').click();frame.style.width='1280px';});
document.body.dataset.complete='true';document.body.dataset.passed=String(results.filter(r=>r.pass).length);document.body.dataset.failed=String(results.filter(r=>!r.pass).length);
