import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {iconPacks,loadIconPack,ensureIconPacks,iconData,iconBody,iconCatalog,searchIcons,mermaidIconPacks,needsIconPack} from '../icons.mjs?v=icons-3';
import {emptyModel,validateModel,toMermaid} from '../core.mjs';

const root=new URL('../',import.meta.url),calls=[];
globalThis.fetch=async url=>{assert.equal(url.protocol,'file:');assert(url.pathname.startsWith(new URL('vendor/icons/',root).pathname));calls.push(url.pathname);return new Response(await readFile(url),{headers:{'Content-Type':'application/json'}});};
const samples=['tabler:ai-agent','lucide:bot','carbon:ai-agent-invocation','ph:robot-duotone','fluent-color:agents-24','logos:redis'];
test('all six full packs have pinned data, catalog entries, license files and verified hashes',async()=>{
 const manifest=JSON.parse(await readFile(new URL('vendor/icons/manifest.json',root))),catalog=await iconCatalog();
 assert.equal(manifest.length,6);assert.equal(catalog.length,7);
 for(const entry of manifest){const bytes=await readFile(new URL(`vendor/icons/${entry.prefix}.json`,root)),data=JSON.parse(bytes);assert.equal(createHash('sha256').update(bytes).digest('hex'),entry.sha256);assert.equal(catalog.find(p=>p.prefix===entry.prefix).names.length,Object.keys(data.icons).length+Object.keys(data.aliases||{}).length);assert((await readFile(new URL(`vendor/icons/${entry.prefix}-LICENSE.txt`,root),'utf8')).length>500);}
});
test('known packs load from bundled files and concurrent requests share one read',async()=>{assert(needsIconPack('tabler:ai-agent'));const before=calls.length;const [a,b]=await Promise.all([loadIconPack('tabler'),loadIconPack('tabler')]);assert.equal(a,b);assert.equal(calls.length,before+1);assert(!needsIconPack('tabler:ai-agent'));assert.equal(await loadIconPack('missing'),null);});
test('each pack resolves a real glyph; built-in studio references still work',async()=>{await ensureIconPacks(samples);for(const ref of [...samples,'studio:agent']){const glyph=iconData(ref);assert(glyph.available,ref);const box=glyph.viewBox.split(' ').map(Number);assert.equal(box.length,4);assert(box.every(Number.isFinite)&&box[2]>0&&box[3]>0);assert(glyph.body.length>20);}});
test('wide logos retain their view box and coloured artwork retains its fills and gradients',async()=>{await loadIconPack('logos');const glyph=iconData('logos:google');const [,,width,height]=glyph.viewBox.split(' ').map(Number);assert(width>height*2,'wordmark aspect ratio');assert(/fill="#/.test(iconData('logos:redis').body),'brand palette');await loadIconPack('fluent-color');assert(/linearGradient/.test(iconData('fluent-color:agents-24').body),'Fluent gradients');});
test('repeated gradient icons receive unique IDs and all references stay internal',()=>{const a=iconBody('fluent-color:agents-24'),b=iconBody('fluent-color:agents-24');const ids=body=>[...body.matchAll(/\sid="([^"]+)"/g)].map(m=>m[1]);assert(ids(a).length);assert(ids(a).every(id=>!ids(b).includes(id)));for(const body of [a,b])for(const [,id]of body.matchAll(/url\(#([^)]+)\)/g))assert(ids(body).includes(id));});
test('Iconify aliases use their inherited shapes and transformations',async()=>{const pack=await loadIconPack('tabler'),name=Object.keys(pack.aliases)[0];assert(iconData('tabler:'+name).available);assert(iconData('tabler:'+name).body.length);});
test('unknown names and object prototype names use a stable fallback without network requests',()=>{const before=calls.length;for(const ref of ['missing:robot','tabler:missing-icon-name','tabler:constructor','logos:__proto__'])assert(!iconData(ref).available);assert.equal(calls.length,before);});
test('search spans packs, uses multiple words and aliases, and filters a single pack',async()=>{const catalog=await iconCatalog();assert(searchIcons(catalog,'ai agent').items.some(i=>i.reference==='tabler:ai-agent'));assert(searchIcons(catalog,'robot','ph').items.every(i=>i.reference.startsWith('ph:')));assert(searchIcons(catalog,'human').items.some(i=>i.reference==='studio:human'));assert.equal(searchIcons(catalog,'xyz-no-such-icon').total,0);assert(searchIcons(catalog,'FLUENT agents').items.some(i=>i.reference==='fluent-color:agents-24'));});
test('pagination reaches every icon and initial browsing offers useful icons across all packs',async()=>{const catalog=await iconCatalog(),first=searchIcons(catalog,'','',0,96),second=searchIcons(catalog,'','',96,96);assert.equal(first.total,catalog.reduce((sum,p)=>sum+p.names.length,0));for(const pack of iconPacks)assert(first.items.some(i=>i.reference.startsWith(pack.prefix+':')));assert(!first.items.some(a=>second.items.some(b=>a.reference===b.reference)));assert.equal(searchIcons(catalog,'','logos',0,5000).items.length,catalog.find(p=>p.prefix==='logos').count);});
test('Mermaid uses the same seven local packs and loaders',async()=>{const registrations=mermaidIconPacks();assert.equal(registrations.length,7);assert(registrations.find(p=>p.name==='studio').icons);for(const entry of registrations.filter(p=>p.loader))assert.equal((await entry.loader()).prefix,entry.name);});
test('standard numeric icon names save, export and retain portable fallbacks',()=>{const model=emptyModel();model.nodes.push({id:'Brand',shape:'icon',icon:'logos:500px',label:'Brand',x:0,y:0,width:150,height:100,parentId:null});validateModel(model);const native=toMermaid(model),portable=toMermaid(model,{portable:true});assert(native.includes('icon: "logos:500px"'));assert(!portable.includes('@{'));assert(portable.includes('Brand["Brand"]'));assert(portable.includes('"icon":"logos:500px"'));});
