// Real pointer, property, file and download scenarios. Serve the repo first.
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
let playwright;try{playwright=require('playwright');}catch{playwright=require('/opt/codex/runtimes/cua/lib/node_modules/playwright');}
const artifact=name=>path.join(__dirname,'artifacts',name),base=process.env.DIAGRAM_URL||'http://127.0.0.1:8000',output=artifact('zones-native-results.json');
(async()=>{
 const browser=await playwright.chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||(fs.existsSync('/usr/bin/chromium')?'/usr/bin/chromium':undefined),args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:2000,height:1350},acceptDownloads:true}),results=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/viewer.html');await page.waitForFunction(()=>!document.querySelector('#btn-new').disabled);let serial=0;
 async function snapshot(file){const d=page.waitForEvent('download');await page.locator('#btn-save').click();const target=file||artifact('zone-snapshot-')+(++serial)+'.json';await(await d).saveAs(target);const m=JSON.parse(fs.readFileSync(target));if(!file)fs.unlinkSync(target);await page.waitForTimeout(180);return m;}
 async function test(name,fn){try{await fn();assert(await page.locator('#error-banner').isHidden());results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.message});await page.screenshot({path:artifact('zones-native-failure.png')});fs.writeFileSync(output,JSON.stringify({results,errors},null,2));throw e;}}
 async function point(x,y){return page.locator('#world').evaluate((el,p)=>{const m=el.getScreenCTM();return{x:m.a*p.x+m.e,y:m.d*p.y+m.f};},{x,y});}
 async function click(x,y){const p=await point(x,y);await page.mouse.click(p.x,p.y);}
 async function hierarchy(){if(await page.locator('#btn-hierarchy').getAttribute('aria-expanded')!=='true')await page.locator('#btn-hierarchy').click();}
 async function select(id,extend=false){await hierarchy();await page.locator(`[data-tree-id="${id}"] .tree-object`).click({modifiers:extend?['Shift']:[]});}
 async function multi(ids){await select(ids[0]);for(const id of ids.slice(1))await select(id,true);}
 async function id(){return(await page.locator('#properties .object-id').innerText()).split(' · ')[1];}
 async function field(name,value){await page.locator('#property-'+name).fill(String(value));await page.locator('#property-'+name).press('Tab');}
 async function zone(name,x,y,width,height){await page.locator('[data-tool=zone]').click();await click(x,y);await field('label',name);await field('width',width);await field('height',height);return id();}
 async function node(name,x,y,shape='rectangle'){await page.locator('[data-tool=node]').click();await click(x,y);await field('label',name);await page.locator('#property-shape').selectOption(shape);return id();}
 async function edge(id){await hierarchy();const m=await snapshot();await page.locator('#hierarchy-flows button').nth(m.edges.findIndex(e=>e.id===id)).click();}
 async function connect(a,b,label,sourceSide='east',targetSide='west',style='normal'){await page.locator('[data-tool=connect]').click();for(const n of [a,b])await page.locator(`.diagram-node[data-object-id="${n}"]`).click();await field('label',label);await page.locator('#property-source-attachment').selectOption(sourceSide);await page.locator('#property-target-attachment').selectOption(targetSide);await page.locator('#property-line-style').selectOption(style);return id();}
 async function drag(locator,dx,dy,cancel=false){const b=await locator.boundingBox(),s=await page.locator('#world').evaluate(el=>el.getScreenCTM().a),x=b.x+b.width/2,y=b.y+b.height/2;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+dx*s,y+dy*s,{steps:12});if(cancel)await page.keyboard.press('Escape');await page.mouse.up();}
 async function open(file){await page.locator('#file-input').setInputFiles(file);await page.waitForFunction(()=>!document.querySelector('#btn-new').disabled);}
 const objects=m=>[...m.nodes,...m.zones],obj=(m,id)=>objects(m).find(n=>n.id===id),copy=x=>JSON.parse(JSON.stringify(x));
 const comparable=list=>list.map(n=>{const item=copy(n);for(const key of ['description','notes'])if(!item[key])delete item[key];return item;}).sort((a,b)=>a.id.localeCompare(b.id));
 function descendants(m,id){const ids=new Set([id]);let changed=true;while(changed){changed=false;for(const n of objects(m))if(ids.has(n.parentId)&&!ids.has(n.id)){ids.add(n.id);changed=true;}}return ids;}
 function rigid(a,b,id){const root=obj(a,id),next=obj(b,id),dx=next.x-root.x,dy=next.y-root.y;for(const n of objects(a).filter(n=>descendants(a,id).has(n.id))){const p=obj(b,n.id);assert(Math.abs(p.x-n.x-dx)<1e-5,n.id+' rigid x');assert(Math.abs(p.y-n.y-dy)<1e-5,n.id+' rigid y');assert.equal(p.width,n.width);assert.equal(p.height,n.height);assert.equal(p.parentId,n.parentId);}}
 function inside(m){const header=Math.max(30,(m.settings.fontSize||13)+16);for(const z of m.zones){const p=z.padding||{top:14,right:20,bottom:20,left:20};for(const c of objects(m).filter(n=>n.parentId===z.id)){assert(c.x>=z.x+p.left-1e-5,c.id+' left padding');assert(c.y>=z.y+header+p.top-1e-5,c.id+' title padding');assert(c.x+c.width<=z.x+z.width-p.right+1e-5,c.id+' right padding');assert(c.y+c.height<=z.y+z.height-p.bottom+1e-5,c.id+' bottom padding');}}}
 async function routes(){return page.locator('.diagram-edge .edge-hit').evaluateAll(els=>Object.fromEntries(els.map(el=>[el.parentElement.dataset.objectId,el.getAttribute('d')])));}
 let seed,growth,harvest,climate,bank,trays,daylight,sensor,fan,ready,dispatch,internal,cross,feedback,finalFile;
 await test('build the Aurora greenhouse with three stages and a nested climate room entirely through the UI',async()=>{
  await page.locator('#btn-new').click();seed=await zone('01 · Seed vault',40,60,400,530);growth=await zone('02 · Aurora greenhouse',500,210,440,590);harvest=await zone('03 · Harvest & delivery',1000,130,380,610);
  bank=await node('Seed library',240,185,'cylinder');trays=await node('Sprout trays',240,385,'rounded');daylight=await node('Set daylight',710,300,'rounded');climate=await zone('Climate loop',530,400,340,260);sensor=await node('Read climate',620,475,'circle');fan=await node('Adjust airflow',790,590);ready=await node('Ready?',1190,330,'diamond');dispatch=await node('Pack & dispatch',1190,590,'rounded');
  const m=await snapshot();assert.equal(obj(m,climate).parentId,growth);assert.equal(obj(m,sensor).parentId,climate);assert.equal(obj(m,fan).parentId,climate);assert.equal(obj(m,trays).parentId,seed);assert.equal(obj(m,dispatch).parentId,harvest);inside(m);
 });
 await test('configure unequal padding and fit a nested zone without moving its children',async()=>{await select(climate);for(const [side,value]of [['top',28],['left',30],['right',36],['bottom',24]])await field('padding-'+side,value);const before=await snapshot();await page.locator('#btn-fit-zone').click();const m=await snapshot();assert.deepEqual(m.nodes,before.nodes);assert.deepEqual(obj(m,climate).padding,{top:28,left:30,right:36,bottom:24});inside(m);await select(growth);await page.locator('#btn-fit-zone').click();assert.deepEqual(obj(await snapshot(),climate),obj(m,climate));});
 await test('create forward paths, a dashed feedback loop, fixed waypoints and a displaced label leader',async()=>{
  await connect(bank,trays,'Germinate','south','north');cross=await connect(trays,daylight,'Sprout batch');await page.locator('#btn-add-waypoint').click();await click(465,385);
  await connect(daylight,sensor,'Climate target','south','north');internal=await connect(sensor,fan,'Tune airflow');await page.locator('#btn-add-waypoint').click();await click(710,550);await drag(page.locator(`.edge-label[data-object-id="${internal}"]>rect`),45,-75);assert.equal(await page.locator(`.edge-label[data-object-id="${internal}"] line.edge-label-leader`).count(),1);
  await connect(fan,ready,'Crop check');await connect(ready,dispatch,'Yes · harvest','south','north');feedback=await connect(ready,trays,'Wait · grow again','north','north','dashed');await page.locator('#btn-add-waypoint').click();await click(950,90);
  const m=await snapshot();assert(obj(m,sensor));assert(m.edges.find(e=>e.id===internal).labelPosition);inside(m);
 });
 await test('align the three stage tops with a selected descendant: each group and internal route moves once',async()=>{const before=await snapshot();await multi([seed,growth,climate,harvest]);await page.locator('#btn-align-top').click();const m=await snapshot();assert([seed,growth,harvest].every(id=>obj(m,id).y===obj(m,seed).y));for(const id of [seed,growth,harvest])rigid(before,m,id);const d={x:obj(m,growth).x-obj(before,growth).x,y:obj(m,growth).y-obj(before,growth).y};assert.deepEqual(m.edges.find(e=>e.id===internal).waypoints,before.edges.find(e=>e.id===internal).waypoints.map(p=>({x:p.x+d.x,y:p.y+d.y})));assert.deepEqual(m.edges.find(e=>e.id===cross).waypoints,before.edges.find(e=>e.id===cross).waypoints);assert.deepEqual(m.edges.map(e=>e.labelPosition),before.edges.map(e=>e.labelPosition));inside(m);});
 await test('a complete align action undoes and redoes in one step with identical native routes',async()=>{const aligned=await snapshot(),paths=await routes();await page.locator('#btn-undo').click();assert.notEqual(obj(await snapshot(),growth).y,obj(aligned,growth).y);await page.locator('#btn-redo').click();const m=await snapshot();assert.deepEqual(m.nodes,aligned.nodes);assert.deepEqual(m.zones,aligned.zones);assert.deepEqual(m.edges,aligned.edges);assert.deepEqual(await routes(),paths);});
 await test('fit all selected stages, then distribute the frames with equal gaps',async()=>{await multi([seed,growth,harvest]);const before=await snapshot();await page.locator('#btn-fit-zone').click();let m=await snapshot();assert.deepEqual(m.nodes,before.nodes);const fitted=copy(m);await page.locator('#btn-align-distribute-x').click();m=await snapshot();for(const id of [seed,growth,harvest])rigid(fitted,m,id);const zs=[seed,growth,harvest].map(id=>obj(m,id)).sort((a,b)=>a.x-b.x),gaps=zs.slice(1).map((z,i)=>z.x-zs[i].x-zs[i].width);assert(Math.abs(gaps[0]-gaps[1])<1e-5&&gaps[0]>=24);inside(m);});
 await test('left alignment handles overlapping target frames by translating whole stages down',async()=>{const before=await snapshot();await multi([seed,growth,harvest]);await page.locator('#btn-align-left').click();const m=await snapshot();assert([seed,growth,harvest].every(id=>obj(m,id).x===obj(m,seed).x));for(const id of [seed,growth,harvest])rigid(before,m,id);inside(m);await page.locator('#btn-undo').click();assert.deepEqual((await snapshot()).zones,before.zones);});
 await test('ancestor plus its only selected child cannot align or distribute as two separate objects',async()=>{await multi([growth,climate]);assert(await page.locator('#btn-align-top').isDisabled());assert(await page.locator('#btn-align-distribute-x').isDisabled());await page.locator('#btn-fit-zone').click();assert(await page.locator('#btn-align-top').isDisabled());inside(await snapshot());});
 for(const handle of ['n','s','e','w','nw','ne','sw','se'])await test('native '+handle+' resize clamps at content, fixes opposite sides, preserves routes and supports Escape',async()=>{
  await select(growth);await field('width',obj(await snapshot(),growth).width+80);await field('height',obj(await snapshot(),growth).height+80);await page.locator('#btn-fit').click();await select(growth);const before=await snapshot(),z=obj(before,growth);await drag(page.locator(`[data-resize="${growth}"][data-handle="${handle}"]`),handle.includes('w')?250:-250,handle.includes('n')?250:-250);const m=await snapshot(),n=obj(m,growth);assert.deepEqual(m.nodes,before.nodes);assert.deepEqual(m.edges,before.edges);if(handle.includes('w'))assert(Math.abs(n.x+n.width-z.x-z.width)<1e-5);else assert.equal(n.x,z.x);if(handle.includes('n'))assert(Math.abs(n.y+n.height-z.y-z.height)<1e-5);else assert.equal(n.y,z.y);inside(m);const stable=await snapshot();await select(growth);await drag(page.locator(`[data-resize="${growth}"][data-handle="${handle}"]`),30,40,true);const cancelled=await snapshot();assert.deepEqual(cancelled.nodes,stable.nodes);assert.deepEqual(cancelled.zones,stable.zones);assert.deepEqual(cancelled.edges,stable.edges);await select(growth);await page.locator('#btn-fit-zone').click();
 });
 await test('numeric zone shrink keeps the upper-left anchor and refuses to clip the nested room',async()=>{await select(growth);const before=await snapshot();await field('width',1);await field('height',1);const m=await snapshot();assert.equal(obj(m,growth).x,obj(before,growth).x);assert.equal(obj(m,growth).y,obj(before,growth).y);assert.deepEqual(m.nodes,before.nodes);assert.deepEqual(obj(m,climate),obj(before,climate));inside(m);});
 await test('padding grows only the frame; reducing padding keeps manual room until Fit',async()=>{await select(seed);const before=await snapshot();await field('padding-right',100);const expanded=await snapshot();assert(obj(expanded,seed).width>obj(before,seed).width);assert.deepEqual(expanded.nodes,before.nodes);await field('padding-right',20);assert.equal(obj(await snapshot(),seed).width,obj(expanded,seed).width);await page.locator('#btn-fit-zone').click();assert(obj(await snapshot(),seed).width<obj(expanded,seed).width);});
 await test('zero and fractional padding are exact; invalid input restores the prior project',async()=>{await select(climate);await field('padding-left',0);await field('padding-top',7.5);await page.locator('#btn-fit-zone').click();const before=await snapshot();assert.equal(obj(before,climate).padding.left,0);assert.equal(obj(before,climate).padding.top,7.5);await page.locator('#property-padding-bottom').fill('-5');await page.locator('#property-padding-bottom').press('Tab');assert(await page.locator('#error-banner').isVisible());assert.deepEqual((await snapshot()).zones,before.zones);await page.locator('#dismiss-error').click();await select(climate);for(const [side,value]of [['left',30],['top',28]])await field('padding-'+side,value);await page.locator('#btn-fit-zone').click();inside(await snapshot());});
 await test('dragging a child within its enlarged zone keeps membership, offsets, padding and external waypoints',async()=>{await select(seed);await field('width',obj(await snapshot(),seed).width+240);await page.locator('#btn-fit').click();const before=await snapshot();await select(trays);await drag(page.locator(`.diagram-node[data-object-id="${trays}"]`),80,0);const m=await snapshot();assert.equal(obj(m,trays).parentId,seed);assert.deepEqual(m.edges.find(e=>e.id===cross).waypoints,before.edges.find(e=>e.id===cross).waypoints);inside(m);await page.locator('#btn-undo').click();assert.deepEqual((await snapshot()).nodes,before.nodes);await select(seed);await page.locator('#btn-fit-zone').click();});
 await test('source editing by matching IDs retains padding, selected sizes, leaders and route constraints',async()=>{const before=await snapshot();if(await page.locator('#btn-source').getAttribute('aria-expanded')!=='true')await page.locator('#btn-source').click();const source=await page.locator('#editor').inputValue();await page.locator('#editor').fill(source+'\n%% Keep this greenhouse arrangement\n');await page.locator('#btn-apply').click();await page.waitForFunction(()=>!document.querySelector('#btn-new').disabled);const m=await snapshot();assert.deepEqual(comparable(m.zones),comparable(before.zones));assert.deepEqual(comparable(m.edges),comparable(before.edges));inside(m);});
 await test('explicit auto layout retains padding and manual routes; Undo restores the manual diagram',async()=>{const before=await snapshot();await page.locator('#btn-layout').click();await page.waitForFunction(()=>!document.querySelector('#btn-new').disabled);const m=await snapshot();assert.deepEqual(m.zones.map(z=>z.padding),before.zones.map(z=>z.padding));assert.deepEqual(m.edges.map(e=>e.waypoints),before.edges.map(e=>e.waypoints));inside(m);await page.locator('#btn-undo').click();assert.deepEqual((await snapshot()).zones,before.zones);});
 await test('finish, save and reopen the greenhouse; image exports retain zones and leaders without controls',async()=>{
  await multi([seed,growth,harvest]);await page.locator('#btn-fit-zone').click();await page.locator('#btn-align-top').click();await page.locator('#btn-align-distribute-x').click();
  for(const [id,color]of [[seed,'#e0e7ff'],[growth,'#dcfce7'],[harvest,'#ffedd5'],[climate,'#bbf7d0']]){await select(id);await page.locator('#property-background-color').fill(color);await page.locator('#property-background-color').press('Tab');}
  await page.locator('#font-size').fill('16');await page.locator('#font-size').press('Tab');await multi([seed,growth,harvest]);await page.locator('#btn-fit-zone').click();await page.locator('#btn-align-top').click();await page.locator('#btn-align-distribute-x').click();await page.locator('#btn-fit').click();
  // Manual corridors stay fixed during alignment. Finish the demonstration by
  // editing those corridors through the same controls a user would use.
  const diagram=await snapshot(),seedFrame=obj(diagram,seed),growFrame=obj(diagram,growth),harvestFrame=obj(diagram,harvest),tray=obj(diagram,trays),light=obj(diagram,daylight),decision=obj(diagram,ready),corridor=(seedFrame.x+seedFrame.width+growFrame.x)/2;
  await edge(cross);await page.locator('#btn-reset-route').click();for(const p of [{x:corridor,y:tray.y+tray.height/2},{x:corridor,y:light.y+light.height/2}]){await page.locator('#btn-add-waypoint').click();await click(p.x,p.y);}
  await edge(feedback);await page.locator('#btn-reset-route').click();await page.locator('#property-source-attachment').selectOption('east');await page.locator('#property-target-attachment').selectOption('west');await page.locator('#btn-zoom-out').click();await page.locator('#btn-zoom-out').click();const outsideRight=harvestFrame.x+harvestFrame.width+60,outsideLeft=seedFrame.x-70,above=seedFrame.y-65;
  for(const p of [{x:outsideRight,y:decision.y+decision.height/2},{x:outsideRight,y:above},{x:outsideLeft,y:above},{x:outsideLeft,y:tray.y+tray.height/2}]){await page.locator('#btn-add-waypoint').click();await click(p.x,p.y);}await page.locator('#btn-fit').click();
  finalFile=artifact('zones-aurora-greenhouse.mermaid-project.json');const saved=await snapshot(finalFile),paths=await routes();await open(finalFile);const m=await snapshot();assert.deepEqual(m.nodes,saved.nodes);assert.deepEqual(m.zones,saved.zones);assert.deepEqual(m.edges,saved.edges);assert.deepEqual(await routes(),paths);inside(m);
  for(const format of ['svg','png']){await page.locator('#export-format').selectOption(format);const download=page.waitForEvent('download');await page.locator('#btn-export').click();await(await download).saveAs(artifact('zones-aurora-greenhouse-export.')+format);}const svg=fs.readFileSync(artifact('zones-aurora-greenhouse-export.svg'),'utf8');assert(!/class="[^"]*(resize-handle|waypoint-handle|route-segment-handle)/.test(svg));assert(svg.includes('edge-label-leader'));assert(fs.statSync(artifact('zones-aurora-greenhouse-export.png')).size>1000);
 });
 await multi([seed,growth,harvest]);await page.screenshot({path:artifact('zones-alignment-controls.png')});await select(climate);await page.locator('.zone-padding').evaluate(el=>el.scrollIntoView({block:'center'}));await page.screenshot({path:artifact('zones-padding-controls.png')});
 if(await page.locator('#btn-hierarchy').getAttribute('aria-expanded')==='true')await page.locator('#btn-hierarchy').click();await page.locator('#viewport').click({position:{x:10,y:10}});await page.setViewportSize({width:1800,height:960});await page.locator('#btn-fit').click();await snapshot(finalFile);await page.screenshot({path:artifact('zones-aurora-greenhouse.png')});
 assert.deepEqual(errors,[]);fs.writeFileSync(output,JSON.stringify({passed:results.filter(r=>r.pass).length,total:results.length,results,errors},null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
