import test from 'node:test';import assert from 'node:assert/strict';
import {emptyModel,copy,objectColors,darkenColor,nodeMetrics,textWidth,resizeNode,setNodeContainer,reparent,moveSelection,expandZones,containers,containerContentBox,containerTitleBox,ensureNodeSpacing,ensureLayoutSpacing,dropSelection,dropParents,separateSelection,deleteSelection,validateModel,toMermaid,shapes} from '../core.mjs';
import {resizeObject} from '../editing.mjs';import {overlapsWithGap} from '../geometry.mjs';
import {AvoidLib} from '../vendor/libavoid/dist/index-node.mjs';import {DiagramRouter} from '../routing.mjs';
const node=(id,x=100,y=100,shape='rectangle')=>({id,label:'New Node',shape,parentId:null,x,y,width:120,height:54});
const fixture=()=>{const m=emptyModel();m.nodes=[node('Parent'),node('Child',600,100),node('Outside',1000,300)];return m;};
const contained=(m,c,p)=>{const b=containerContentBox(m,p);assert.ok(c.x>=b.x-1e-6&&c.y>=b.y-1e-6&&c.x+c.width<=b.x+b.width+1e-6&&c.y+c.height<=b.y+b.height+1e-6,'child fits usable shape interior');};
test('default nested zone backgrounds derive from the parent and every title darkens its selected background',()=>{
 const m=emptyModel();m.zones=[{id:'A',label:'Root',parentId:null},{id:'B',label:'Child',parentId:'A'},{id:'C',label:'Nested',parentId:'B'}];let colors=m.zones.map(n=>objectColors(m,n));assert.equal(colors[1].background,darkenColor(colors[0].background,.055));assert.equal(colors[2].background,darkenColor(colors[1].background,.055));m.zones[0].backgroundColor='#dbeafe';m.zones[0].fontColor='#1e40af';colors=m.zones.map(n=>objectColors(m,n));assert.equal(colors[1].background,darkenColor('#dbeafe',.055));assert.equal(colors[2].font,'#1e40af');m.zones[1].backgroundColor='#ffffff';assert.equal(objectColors(m,m.zones[1]).background,'#ffffff');assert.equal(objectColors(m,m.zones[1]).header,'#e8e8e8');assert.equal(darkenColor('#000000'),'#000000');
});
test('short labels wrap and unwrap when circle and diamond dimensions change',()=>{
 for(const shape of ['circle','diamond']){const n={...node('N',0,0,shape),manualSize:{width:shape==='circle'?90:100,height:shape==='circle'?90:180}};const small=nodeMetrics(n),big=nodeMetrics({...n,manualSize:{width:240,height:240}});assert.ok(small.lines.length>1,shape+' wraps New Node');assert.equal(big.lines.length,1,shape+' unwraps New Node');assert.ok(small.width<240,'manual size is no longer fixed to auto width');}
});
test('manual curved-shape labels fit actual outlines across aspect ratios, fonts, multilingual text and empty labels',()=>{
 for(const shape of ['circle','diamond'])for(const font of [10,13,28,48])for(const label of ['New Node','', '中文 🚀\nReview response','LongWordWithoutSpaces'])for(const [w,h]of[[80,60],[100,180],[320,90],[300,300]]){const n={...node('N',0,0,shape),label,manualSize:{width:w,height:h}},r=nodeMetrics(n,font),tw=Math.max(...r.lines.map(l=>textWidth(l,font))),th=r.lines.length*r.lineHeight;if(shape==='circle'){assert.equal(r.width,r.height);assert.ok(Math.hypot(tw+24,th+24)<=r.width-8+1e-5);}else assert.ok((tw+24)/r.width+(th+20)/r.height<=.94+1e-5);}
});
test('every node shape can contain a node with safe interior space, unchanged IDs and shape',()=>{
 for(const shape of shapes){const m=fixture(),p=m.nodes[0],c=m.nodes[1];p.shape=shape;resizeNode(p);reparent(m,c.id,p.id);assert.equal(p.container,true);assert.equal(p.shape,shape);assert.equal(c.parentId,p.id);contained(m,c,p);assert.deepEqual(validateModel(m),m);const before=copy(c);resizeObject(m,p.id,'se',-200,-100);assert.deepEqual(c,before);contained(m,c,p);const stable=copy(m);expandZones(m);assert.deepEqual(m,stable,'valid saved geometry is stable');}
});
test('parent labels and children fit every container shape at maximum font size',()=>{
 for(const shape of shapes){const m=fixture();m.settings.fontSize=48;m.nodes[0].shape=shape;m.nodes[0].label='Notification delivery 中文 service';reparent(m,'Child','Parent');const p=m.nodes[0],box=containerTitleBox(m,p),metrics=nodeMetrics(p,48);assert.ok(metrics.lines.every(line=>textWidth(line,48)<=box.width-32+.01));assert.ok(metrics.lines.length*metrics.lineHeight<=box.height-14+.01);contained(m,m.nodes[1],p);const stable=copy(m);expandZones(m);assert.deepEqual(m,stable);}
});
test('nested parent nodes move descendants once, preserve membership and reject cycles',()=>{
 const m=fixture();reparent(m,'Child','Parent');reparent(m,'Outside','Child');const before=copy(m);moveSelection(m,new Set(['Parent','Child','Outside']),40,25);for(const n of m.nodes){const old=before.nodes.find(o=>o.id===n.id);assert.equal(n.x,old.x+40);assert.equal(n.y,old.y+25);}assert.throws(()=>reparent(m,'Parent','Outside'));assert.deepEqual(validateModel(m),m);
});
test('dropping into and out of a parent node changes membership without its previous parent chasing it',()=>{
 const m=fixture();setNodeContainer(m,'Parent',true);const refs=copy(containers(m)),p=m.nodes[0],c=m.nodes[1],b=containerContentBox(m,p);c.x=b.x;c.y=b.y;dropSelection(m,new Set(['Child']),refs);assert.equal(c.parentId,'Parent');const parentBefore=copy(p),oldRefs=copy(containers(m));moveSelection(m,new Set(['Child']),700,0,{expand:false});dropSelection(m,new Set(['Child']),oldRefs);assert.equal(c.parentId,null);assert.ok(!p.container,'last child release returns parent to an ordinary node');assert.equal(p.x+p.width/2,parentBefore.x+parentBefore.width/2);assert.equal(p.y+p.height/2,parentBefore.y+parentBefore.height/2);
});
test('drop clearance uses the intended node parent before adoption and clears the former body on exit',()=>{
 const m=fixture();setNodeContainer(m,'Parent',true);const p=m.nodes[0],c=m.nodes[1],refs=copy(containers(m)),box=containerContentBox(m,p);c.x=box.x+10;c.y=box.y+10;const location={x:c.x,y:c.y},before=copy(p),parents=dropParents(m,new Set(['Child']),refs);dropSelection(m,new Set(['Child']),refs,parents,{expand:false});separateSelection(m,new Set(['Child']));expandZones(m);assert.equal(c.parentId,'Parent');assert.equal(c.x,location.x);assert.equal(c.y,location.y);assert.deepEqual(p,before,'parent is stable when the child already fits');
 c.x=p.x+p.width-20;c.y=p.y+p.height-20;const exited=dropParents(m,new Set(['Child']),copy(containers(m)));dropSelection(m,new Set(['Child']),containers(m),exited,{expand:false});separateSelection(m,new Set(['Child']));assert.equal(c.parentId,null);assert.ok(!overlapsWithGap(p,c),'unrelated former parent retains clearance');
});
test('node clearance ignores ancestors while keeping unrelated objects away from a parent body',()=>{
 const m=fixture();reparent(m,'Child','Parent');const p=m.nodes[0],c=m.nodes[1],childBefore=copy(c);ensureNodeSpacing(m);assert.deepEqual(c,childBefore,'parent body is not treated as a collision for its child');m.nodes[2].x=p.x+p.width-5;m.nodes[2].y=p.y+50;ensureNodeSpacing(m,{preferredIds:new Set(['Outside'])});assert.ok(!overlapsWithGap(p,m.nodes[2]));contained(m,c,p);
});
test('deleting or disabling a parent node retains children and removes only incident parent edges',()=>{
 const m=fixture();reparent(m,'Child','Parent');m.edges=[{id:'E',label:'',source:'Parent',target:'Outside',direction:'forward',style:'normal',routing:'orthogonal'}];deleteSelection(m,new Set(['Parent']));assert.ok(m.nodes.some(n=>n.id==='Child'));assert.equal(m.nodes.find(n=>n.id==='Child').parentId,null);assert.equal(m.edges.length,0);const other=fixture();reparent(other,'Child','Parent');setNodeContainer(other,'Parent',false);assert.equal(other.nodes[1].parentId,null);assert.ok(!other.nodes[0].container);
});
test('automatic-layout clearance includes zone borders and moves a compound group rigidly',()=>{
 const m=emptyModel();m.settings.direction='LR';m.zones=[{id:'Z',label:'Services',x:150,y:60,width:300,height:220,parentId:null}];m.nodes=[{...node('Child',180,120),parentId:'Z'},node('Browser',30,120)];ensureLayoutSpacing(m);assert.ok(!overlapsWithGap(m.zones[0],m.nodes[1]));assert.equal(m.nodes[0].x,180);assert.equal(m.nodes[0].y,120);const stable=copy(m);ensureLayoutSpacing(m);assert.deepEqual(m,stable);
});
test('node container structure serializes as nested Mermaid subgraphs with shape annotations',()=>{
 const m=fixture();reparent(m,'Child','Parent');reparent(m,'Outside','Child');const source=toMermaid(m);assert.ok(source.includes('%% diagram-studio-container {"id":"Parent","shape":"rectangle"}'));assert.ok(source.includes('subgraph Parent[')&&source.includes('subgraph Child[')&&source.includes('Outside['));const invalid=copy(m);invalid.nodes[0].parentId='Outside';assert.throws(()=>validateModel(invalid));invalid.nodes[0].parentId=null;invalid.nodes[0].container='yes';assert.throws(()=>validateModel(invalid));
});
await AvoidLib.load(new URL('../vendor/libavoid/dist/libavoid.wasm',import.meta.url).pathname);const router=new DiagramRouter(AvoidLib.getInstance());
test('parent-node interiors are traversable while child nodes remain routing obstacles and parent connections attach',()=>{
 const m=fixture();m.nodes[0].label='Parent service';reparent(m,'Child','Parent');m.nodes.push({...node('Sibling',300,250),parentId:'Parent'});expandZones(m);m.edges=[['Outside','Child'],['Child','Sibling'],['Parent','Outside'],['Parent','Parent']].map(([source,target],i)=>({id:'E'+i,source,target,label:'',direction:'forward',style:'normal',routing:'orthogonal',sourceSide:null,targetSide:null}));const paths=router.route(m);for(const route of paths.values()){assert.ok(route.length>=2);for(let i=1;i<route.length;i++)assert.ok(Math.abs(route[i].x-route[i-1].x)<1e-6||Math.abs(route[i].y-route[i-1].y)<1e-6,'route stays orthogonal');}const p=m.nodes[0],start=paths.get('E2')[0];assert.ok(start.x===p.x||start.x===p.x+p.width||start.y===p.y||start.y===p.y+p.height,'parent endpoint stays on its outline');
});test.after(()=>router.dispose());
test('dropping onto an ordinary node enables containment on every actual shape outline',()=>{
 for(const shape of shapes){const m=fixture(),p=m.nodes[0],c=m.nodes[1];p.shape=shape;resizeNode(p);c.x=p.x+p.width/2-c.width/2;c.y=p.y+p.height/2-c.height/2;const centre={x:c.x+c.width/2,y:c.y+c.height/2},refs=copy([...m.nodes,...m.zones]),parents=dropParents(m,new Set(['Child']),refs);assert.equal(parents.get('Child'),'Parent');dropSelection(m,new Set(['Child']),refs,parents,{expand:false});separateSelection(m,new Set(['Child']));expandZones(m);assert.equal(p.container,true);assert.equal(c.parentId,p.id);assert.equal(p.shape,shape);assert.equal(c.x+c.width/2,centre.x);assert.equal(c.y+c.height/2,centre.y);contained(m,c,p);assert.deepEqual(validateModel(m),m);}
});
test('curved and diamond corners do not trigger containment outside the visible outline',()=>{
 for(const shape of ['circle','diamond','cylinder']){const m=fixture(),p=m.nodes[0],c=m.nodes[1];p.shape=shape;resizeNode(p);c.x=p.x+1-c.width/2;c.y=p.y+1-c.height/2;assert.equal(dropParents(m,new Set(['Child'])).get('Child'),null);}
});
test('the deepest ordinary node wins over its containing zone and dragged descendants cannot become parents',()=>{
 const m=fixture();m.zones=[{id:'Z',label:'Zone',x:0,y:0,width:500,height:400,parentId:null}];const p=m.nodes[0],c=m.nodes[1];p.parentId='Z';c.x=p.x;c.y=p.y;assert.equal(dropParents(m,new Set(['Child'])).get('Child'),'Parent');reparent(m,'Child','Parent');assert.notEqual(dropParents(m,new Set(['Parent'])).get('Parent'),'Child');assert.throws(()=>dropSelection(m,new Set(['Parent']),undefined,new Map([['Parent','Child']])));assert.deepEqual(validateModel(m),m);
});
test('a parent stays enabled until its final child leaves and empty explicit containers and zones remain available',()=>{
 const m=fixture();reparent(m,'Child','Parent');reparent(m,'Outside','Parent');dropSelection(m,new Set(['Child']),[],new Map([['Child',null]]));assert.equal(m.nodes[0].container,true);dropSelection(m,new Set(['Outside']),[],new Map([['Outside',null]]));assert.ok(!m.nodes[0].container);assert.equal(m.nodes[0].width,120);setNodeContainer(m,'Parent',true);dropSelection(m,new Set(['Child']),[],new Map([['Child',null]]));assert.equal(m.nodes[0].container,true,'unrelated explicit empty parent is not collapsed');m.zones=[{id:'Z',label:'Zone',x:0,y:0,width:400,height:300,parentId:null}];reparent(m,'Child','Z');reparent(m,'Child',null);assert.ok(m.zones.some(z=>z.id==='Z'),'empty zone retained');
});
test('ordinary manual size, colors, context and connections survive promotion, save and final-child release',()=>{
 const m=fixture(),p=m.nodes[0];p.manualSize={width:190,height:80};resizeNode(p);p.backgroundColor='#dbeafe';p.notes='Keep me';m.edges=[{id:'E',source:'Parent',target:'Outside',label:'',style:'normal',direction:'forward',routing:'orthogonal'}];reparent(m,'Child','Parent');assert.deepEqual(p.containerSize,{width:190,height:80});const saved=validateModel(JSON.parse(JSON.stringify(m)));reparent(saved,'Child',null);const restored=saved.nodes[0];assert.ok(!restored.container&&!restored.containerSize);assert.deepEqual(restored.manualSize,{width:190,height:80});assert.equal(restored.width,190);assert.equal(restored.height,80);assert.equal(restored.backgroundColor,'#dbeafe');assert.equal(restored.notes,'Keep me');assert.equal(saved.edges[0].source,'Parent');const invalid=copy(m);invalid.nodes[0].containerSize={width:0,height:80};assert.throws(()=>validateModel(invalid));
});
test('moving the only child container to another ordinary node demotes only the former parent',()=>{
 const m=fixture();reparent(m,'Child','Parent');m.nodes.push(node('Nested',900,500));reparent(m,'Nested','Child');reparent(m,'Child','Outside');assert.ok(!m.nodes[0].container);assert.equal(m.nodes.find(n=>n.id==='Outside').container,true);assert.equal(m.nodes.find(n=>n.id==='Child').container,true);assert.equal(m.nodes.find(n=>n.id==='Nested').parentId,'Child');assert.deepEqual(validateModel(m),m);
});
test('deleting the last child collapses its node parent without removing parent connections',()=>{
 const m=fixture();reparent(m,'Child','Parent');m.edges=[{id:'E',source:'Parent',target:'Outside',label:'',style:'normal',direction:'forward',routing:'orthogonal'}];deleteSelection(m,new Set(['Child']));assert.ok(!m.nodes[0].container);assert.equal(m.edges.length,1);assert.equal(m.nodes[0].id,'Parent');
});
