import {emptyModel,validateModel} from '../core.mjs';
const frame=document.getElementById('app'),out=document.getElementById('results'),results=[];
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){for(let i=0;i<300;i++){if(fn())return;await wait(20);}throw new Error('Timed out waiting for the editor');}
await until(()=>frame.contentDocument?.getElementById('loading')?.hidden);
let win=frame.contentWindow,doc=frame.contentDocument;
const $=id=>doc.getElementById(id),assert=(ok,msg)=>{if(!ok)throw new Error(msg);};
async function test(name,fn){try{await fn();results.push({name,pass:true});}catch(err){results.push({name,pass:false,error:err.message,stack:err.stack});if($('file-dialog')?.open)$('file-dialog').close();}out.textContent=JSON.stringify(results,null,2);}
const rect=(id,x,y,parentId=null)=>({id,label:id==='A'?'Source':id==='B'?'Target':id,shape:'rectangle',x,y,width:140,height:60,parentId});
function fixture(){return validateModel({...emptyModel(),nodes:[{...rect('A',50,100),notes:'Original note',description:'Request entry',backgroundColor:'#fff4d6'},rect('B',300,100)],edges:[{id:'E',source:'A',target:'B',label:'Request',direction:'forward',style:'normal',routing:'orthogonal',sourceSide:'east',targetSide:'west',labelPosition:{fraction:.5,offsetAlong:8,offsetNormal:18}}]});}
function diskHandle(name,model){let text=typeof model==='string'?model:JSON.stringify(model,null,2),permission='granted',failure=null,gate=null;const writes=[],closed=[];return{name,writes,closed,text:()=>text,json:()=>JSON.parse(text),external:value=>{text=typeof value==='string'?value:JSON.stringify(value,null,2);},grant:value=>permission=value,fail:value=>failure=value,hold:value=>gate=value,requests:0,
  queryPermission:async()=>permission,async requestPermission(){this.requests++;return permission;},async getFile(){return new win.File([text],name,{type:'application/json'});},async createWritable(){let pending;return{async write(value){writes.push(value);if(gate)await gate.promise;if(failure)throw failure;pending=value;},async close(){if(failure)throw failure;text=pending;closed.push(pending);},async abort(){pending=null;}};}};}
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};};
let chosenOpen=null,chosenSave=null,cancelOpen=false,cancelSave=false,savePickers=0,openPickers=0,clipboardText='',clipboardDenied=false,clipboardGate=null,downloads=[];
const nativeObjectUrls=new WeakMap();
function installAPIs(){
  win.showOpenFilePicker=async()=>{openPickers++;if(cancelOpen)throw new win.DOMException('Cancelled','AbortError');return[chosenOpen];};
  win.showSaveFilePicker=async()=>{savePickers++;if(cancelSave)throw new win.DOMException('Cancelled','AbortError');return chosenSave;};
  Object.defineProperty(win.navigator,'clipboard',{configurable:true,value:{writeText:async text=>{if(clipboardDenied)throw new win.DOMException('Blocked','NotAllowedError');clipboardText=text;},readText:async()=>{if(clipboardGate)await clipboardGate.promise;if(clipboardDenied)throw new win.DOMException('Blocked','NotAllowedError');return clipboardText;}}});
  if(!nativeObjectUrls.has(win.URL))nativeObjectUrls.set(win.URL,win.URL.createObjectURL.bind(win.URL));const create=nativeObjectUrls.get(win.URL);win.URL.createObjectURL=blob=>{downloads.push(blob);return create(blob);};win.HTMLAnchorElement.prototype.click=function(){};
  $('viewport').setPointerCapture=()=>{};$('viewport').hasPointerCapture=()=>false;
}
installAPIs();
function click(id){$(id).click();}
function input(id,value){const n=$(id);n.value=value;n.dispatchEvent(new win.Event('input',{bubbles:true}));}
function change(id,value){const n=$(id);n.value=value;n.dispatchEvent(new win.Event('change',{bubbles:true}));}
function key(key,extra={},target=$('viewport')){target.dispatchEvent(new win.KeyboardEvent('keydown',{key,bubbles:true,cancelable:true,...extra}));}
function command(command,menu='btn-project-menu'){click(menu);const b=doc.querySelector(`#editing-overlay [data-command="${command}"]`);assert(b&&!b.disabled,command+' is available');b.click();}
function pointer(type,x,y,target=$('canvas'),extra={}){target.dispatchEvent(new win.PointerEvent(type,{bubbles:true,cancelable:true,isPrimary:true,button:0,pointerId:2,clientX:x,clientY:y,...extra}));}
function select(id,extend=false){const row=doc.querySelector(`[data-tree-id="${id}"] .tree-object`);assert(row,'hierarchy item '+id);row.dispatchEvent(new win.MouseEvent('click',{bubbles:true,shiftKey:extend}));}
function centre(id){const n=doc.querySelector(`[data-object-id="${id}"] .node-shape`),r=n.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2,n};}
async function discard(){await wait(20);if($('file-dialog').open){const b=[...doc.querySelectorAll('#file-dialog-actions button')].find(b=>b.textContent==='Discard changes');assert(b,'Discard offered');b.click();await wait(20);}}
async function open(model=fixture(),name='working.json'){chosenOpen=diskHandle(name,model);cancelOpen=false;const count=openPickers;click('btn-open');await discard();await until(()=>openPickers>count&&$('loading').hidden&&$('file-name').textContent===name);await wait(20);return chosenOpen;}
async function save(){click('btn-save');await until(()=>$('file-state').textContent!=='Saving…');await wait(20);}
async function copy(){command('copy','btn-edit-menu');await wait(20);assert(clipboardText.includes('diagram-studio-fragment'),'real clipboard payload');return clipboardText;}
async function paste(text=clipboardText){clipboardText=text;command('paste','btn-edit-menu');await wait(20);}
async function snapshot(){command('download-copy');await wait(10);return JSON.parse(await downloads.at(-1).text());}
function clipboardEvent(type,text='',target=$('viewport')){const data=new win.DataTransfer();data.setData('text/plain',text);const event=new win.ClipboardEvent(type,{bubbles:true,cancelable:true,clipboardData:data});target.dispatchEvent(event);return{data,event};}

await test('Open JSON retains a working file; Save changes the original rather than downloading',async()=>{
 const h=await open();assert($('file-info').dataset.connected==='true','working file connected');assert($('file-state').textContent==='Saved','saved baseline');select('A');input('property-label','Updated source');await save();assert(h.json().nodes[0].label==='Updated source','original file updated');assert(downloads.length===0,'Save did not download');assert($('file-state').textContent==='Saved','disk save confirmed');
});
await test('Save remains dirty until close; edits made during the write remain pending',async()=>{
 const h=await open();select('A');input('property-notes','First saved note');const gate=deferred();h.hold(gate);click('btn-save');await until(()=>$('file-state').textContent==='Saving…');assert(h.json().nodes[0].notes==='Original note','disk unchanged while writing');input('property-notes','Second note while saving');gate.resolve();await until(()=>$('file-state').textContent==='Unsaved changes');assert(h.json().nodes[0].notes==='First saved note','snapshot written');h.hold(null);await save();assert(h.json().nodes[0].notes==='Second note while saving','later edit saved separately');
});
await test('Autosave is optional and saves focused label, description and notes typing without splitting Undo',async()=>{
 const h=await open();select('A');input('property-notes','Manual only');await wait(1150);assert(h.closed.length===0,'off by default');await save();command('autosave');await until(()=>$('file-info').dataset.autosave==='true');assert($('file-info').dataset.autosave==='true','autosave enabled');
 for(const [field,value]of[['label','Autosaved source'],['description','Owner: Platform'],['notes','Autosaved notes 中文 🚀']]){select('A');const control=$('property-'+field);control.focus();input(control.id,value.slice(0,4));input(control.id,value);await until(()=>h.json().nodes[0][field]===value);assert(doc.activeElement===control&&control.isConnected,'focused '+field+' remains editable');assert(!$('btn-undo').disabled,'Undo remains available for focused typing');assert($('file-state').textContent==='Saved','saved while focused');click('btn-undo');await until(()=>h.json().nodes[0][field]!==value);click('btn-redo');await until(()=>h.json().nodes[0][field]===value);}
 command('autosave');assert($('file-info').dataset.autosave==='false','autosave disabled');
});
await test('completed drags autosave; cancelled gestures and unconfirmed popover previews stay off disk',async()=>{
 const h=await open();command('autosave');select('A');const p=centre('A'),old=h.text();pointer('pointerdown',p.x,p.y,p.n);pointer('pointermove',p.x+35,p.y+110,$('viewport'));await wait(1200);assert(h.text()===old,'intermediate drag excluded');key('Escape');await wait(1150);assert(h.text()===old,'cancel excluded');
 click('selection-color');input('edit-backgroundColor','#124578');await wait(1150);assert(h.text()===old,'popover preview excluded');key('Escape');await wait(1150);assert(h.text()===old,'cancelled preview excluded');
 const q=centre('A');pointer('pointerdown',q.x,q.y,q.n);pointer('pointermove',q.x+30,q.y+110,$('viewport'));await wait(30);pointer('pointerup',q.x+30,q.y+110,$('viewport'));await until(()=>h.text()!==old);assert(h.json().nodes[0].y>fixture().nodes[0].y,'completed movement saved');command('autosave');
});
await test('Save as switches working file only on success; cancellation retains the original binding',async()=>{
 const h=await open();select('A');input('property-notes','Keep this');cancelSave=true;command('save-as');await wait(40);assert($('file-name').textContent==='working.json'&&$('file-state').textContent==='Unsaved changes','cancel retains binding and edits');cancelSave=false;chosenSave=diskHandle('renamed.json','');command('save-as');await until(()=>$('file-name').textContent==='renamed.json'&&$('file-state').textContent==='Saved');assert(chosenSave.json().nodes[0].notes==='Keep this','new file content');assert(h.json().nodes[0].notes==='Original note','old file unchanged');input('property-notes','Next edit');await save();assert(chosenSave.json().nodes[0].notes==='Next edit','later Save uses renamed file');
});
await test('Download a copy preserves working-file binding, autosave preference and unsaved state',async()=>{
 const h=await open();select('A');input('property-notes','Copy only');const m=await snapshot();assert(m.nodes[0].notes==='Copy only','copy content');assert(h.json().nodes[0].notes==='Original note','original unchanged');assert($('file-info').dataset.connected==='true'&&$('file-state').textContent==='Unsaved changes','copy retains dirty binding');
});
await test('lost permission pauses autosave without prompting; Save retries after permission returns',async()=>{
 const h=await open();h.grant('prompt');command('autosave');await until(()=>$('file-state').textContent==='Autosave paused');assert($('file-info').dataset.autosave==='true','denied access retains browser preference');h.grant('granted');await save();assert($('file-state').textContent==='Saved','clean-file Save can reconnect permission');const requestsBefore=h.requests;h.grant('prompt');select('A');input('property-notes','Permission interrupted');await until(()=>$('file-state').textContent==='Autosave paused');assert(h.requests===requestsBefore,'timer did not prompt');assert(h.json().nodes[0].notes==='Original note','disk retained');assert($('file-notice').textContent.includes('Retry Save'),'retry offered');h.grant('granted');await save();assert(h.json().nodes[0].notes==='Permission interrupted','manual retry saved');command('autosave');
});
await test('write failure retains edits and retries without silently claiming Saved',async()=>{
 const h=await open();h.fail(new Error('Disk full'));select('A');input('property-label','My edit');await save();assert($('file-state').textContent==='Save paused'&&h.json().nodes[0].label==='Source','failure retained disk');assert(doc.querySelector('.diagram-node').textContent.includes('My edit'),'edits still rendered');h.fail(null);[...doc.querySelectorAll('#file-notice button')].find(b=>b.textContent==='Retry Save').click();await until(()=>$('file-state').textContent==='Saved');assert(h.json().nodes[0].label==='My edit','retry persisted');
});
await test('external disk changes pause autosave and offer explicit Overwrite, Save as and Reload',async()=>{
 const h=await open();command('autosave');const external=fixture();external.nodes[0].notes='Changed externally';h.external(external);select('A');input('property-notes','Mine');await until(()=>$('file-state').textContent==='Autosave paused');assert(h.json().nodes[0].notes==='Changed externally','external edit protected');const buttons=[...doc.querySelectorAll('#file-notice button')];assert(['Reload file','Save as…','Overwrite'].every(label=>buttons.some(b=>b.textContent===label)),'all resolutions offered');buttons.find(b=>b.textContent==='Overwrite').click();await until(()=>h.json().nodes[0].notes==='Mine'&&$('file-state').textContent==='Saved');command('autosave');
});
await test('Reload validates changed disk content before replacing the current diagram',async()=>{
 const h=await open();select('A');input('property-label','My source');h.external('not JSON');await save();doc.querySelector('#file-notice button').click();await until(()=>$('file-dialog').open);doc.querySelector('#file-dialog-actions button').click();await wait(80);assert(doc.querySelector('.diagram-node').textContent.includes('My source'),'invalid disk keeps diagram');assert($('file-state').textContent==='Save paused','conflict stays actionable');const valid=fixture();valid.nodes[0].label='Disk source';h.external(valid);doc.querySelector('#file-notice button').click();await until(()=>$('file-dialog').open);doc.querySelector('#file-dialog-actions button').click();await until(()=>$('file-state').textContent==='Saved');assert(doc.querySelector('.diagram-node').textContent.includes('Disk source'),'valid disk loaded');assert($('btn-undo').disabled,'Open/reload starts a new document history');
});
await test('New and Open protect unsaved edits; cancellation and failed parsing keep the current binding',async()=>{
 const h=await open();select('A');input('property-notes','Keep edits');click('btn-new');await until(()=>$('file-dialog').open);[...doc.querySelectorAll('#file-dialog-actions button')].find(b=>b.textContent==='Cancel').click();await wait(40);assert($('file-name').textContent==='working.json'&&doc.querySelector('.diagram-node'),'cancel keeps project');chosenOpen=diskHandle('bad.json','{}');click('btn-open');await discard();await wait(80);assert($('file-name').textContent==='working.json'&&doc.querySelector('.diagram-node'),'failed Open keeps original binding');await save();assert(h.json().nodes[0].notes==='Keep edits','old working file still usable');cancelOpen=true;click('btn-open');await wait(60);assert($('file-name').textContent==='working.json','picker cancellation keeps binding');cancelOpen=false;
});
await test('Save and continue writes the old working file before New and detaches Undo from that file',async()=>{
 const h=await open();select('A');input('property-notes','Before new');click('btn-new');await until(()=>$('file-dialog').open);doc.querySelector('#file-dialog-actions button').click();await until(()=>!doc.querySelector('.diagram-node'));assert(h.json().nodes[0].notes==='Before new','saved before transition');assert($('file-info').dataset.connected==='false','New detached');click('btn-undo');assert(doc.querySelector('.diagram-node'),'New remains undoable');assert($('file-info').dataset.connected==='false','Undo cannot silently reconnect prior file');
});
await test('a queued old save completes against the old file before opening another project',async()=>{
 const h=await open();select('A');input('property-notes','In flight');const gate=deferred();h.hold(gate);click('btn-save');await until(()=>h.writes.length===1);chosenOpen=diskHandle('next.json',fixture());const next=chosenOpen;click('btn-open');await until(()=>$('file-dialog').open);[...doc.querySelectorAll('#file-dialog-actions button')].find(b=>b.textContent==='Discard changes').click();await wait(40);assert($('file-name').textContent==='working.json','switch waits for old write');gate.resolve();await until(()=>$('file-name').textContent==='next.json');assert(h.json().nodes[0].notes==='In flight'&&next.json().nodes[0].notes==='Original note','file generations never cross');
});
await test('Mermaid Open is an import and first Save creates JSON without overwriting the source',async()=>{
 chosenOpen=diskHandle('source.mmd','flowchart LR\n A[Imported]\n B[Target]\n A --> B');const source=chosenOpen;click('btn-open');await discard();await until(()=>$('loading').hidden&&doc.querySelector('.diagram-node')?.textContent.includes('Imported'));assert($('file-info').dataset.connected==='false','source remains detached');chosenSave=diskHandle('imported.json','');await save();assert(chosenSave.json().nodes.some(n=>n.label==='Imported'),'JSON created');assert(source.text().startsWith('flowchart'),'source never overwritten');source.external('flowchart LR\n A[Fresh Mermaid source]\n B[Target]\n A --> B');command('recent');await until(()=>doc.querySelector('[aria-label=\"Open source.mmd\"]'));doc.querySelector('[aria-label=\"Open source.mmd\"]').click();await until(()=>doc.querySelector('.diagram-node')?.textContent.includes('Fresh Mermaid source'));assert($('file-info').dataset.connected==='false','recent Mermaid is still a JSON import, not a writable source');
});
await test('keyboard and Edit-menu copy/paste preserve a section, select it and make one Undo step',async()=>{
 const h=await open();select('A');select('B',true);const event=clipboardEvent('copy');assert(event.event.defaultPrevented,'keyboard copy handled');const text=event.data.getData('text/plain');assert(JSON.parse(text).edges.length===1,'internal connection included');const pasted=clipboardEvent('paste',text);assert(pasted.event.defaultPrevented,'keyboard paste handled');let m=await snapshot();assert(m.nodes.length===4&&m.edges.length===2,'section duplicated');assert(doc.querySelectorAll('.diagram-node.selected').length===2,'pasted nodes selected');assert(m.edges.at(-1).labelPosition.offsetNormal===18,'manual label preserved');click('btn-undo');assert((await snapshot()).nodes.length===2,'one Undo removes whole paste');click('btn-redo');assert((await snapshot()).nodes.length===4,'Redo restores whole paste');select('A');await copy();await paste();assert((await snapshot()).nodes.length===5,'Edit menu uses system clipboard');assert(h.json().nodes.length===2,'copy and paste did not save when autosave off');
});
await test('copying collapsed nested zones includes every child once; boundary edges stay behind',async()=>{
 const m=fixture();m.zones=[{id:'Outer',label:'Outer',x:20,y:20,width:460,height:260,parentId:null},{id:'Inner',label:'Inner',x:35,y:60,width:420,height:200,parentId:'Outer'}];m.nodes.forEach(n=>n.parentId='Inner');m.nodes.push(rect('Outside',600,100));m.edges.push({...m.edges[0],id:'External',target:'Outside'});await open(m);select('Outer');doc.querySelector('[data-tree-id=Outer] .tree-toggle').click();const text=await copy();const f=JSON.parse(text);assert(f.nodes.length===2&&f.zones.length===2&&f.edges.length===1,'collapsed descendants included and boundary excluded');await paste(text);const after=await snapshot();assert(after.nodes.length===5&&after.zones.length===4&&after.edges.length===3,'nested section copied once');const newOuter=after.zones.find(n=>n.id!=='Outer'&&n.parentId===null),newInner=after.zones.find(n=>n.parentId===newOuter.id);assert(after.nodes.filter(n=>n.parentId===newInner.id).length===2,'nesting remapped');
});
await test('edge-only clipboard stays in its source document; cross-document section paste works',async()=>{
 await open();doc.querySelector('#hierarchy-flows button').click();const edgeText=await copy();await paste(edgeText);assert((await snapshot()).edges.length===2,'edge duplicated in source');await open(fixture(),'other.json');await paste(edgeText);assert((await snapshot()).edges.length===1,'edge-only cross-document prevented');assert($('error-message').textContent.includes('endpoint nodes'),'clear guidance');select('A');select('B',true);const section=await copy();await open({...emptyModel(),settings:{...emptyModel().settings,theme:'botanical',fontSize:18}},'destination.json');await paste(section);const m=await snapshot();assert(m.nodes.length===2&&m.edges.length===1,'cross-document paste');assert(m.settings.theme==='botanical'&&m.settings.fontSize===18,'destination inheritance');assert(m.nodes[0].backgroundColor==='#fff4d6','explicit fill retained');
});
await test('ordinary text fields keep native copy/paste and malformed clipboard leaves model untouched',async()=>{
 await open();select('A');const notes=$('property-notes'),copied=clipboardEvent('copy','normal text',notes),pasted=clipboardEvent('paste','normal text',notes);assert(!copied.event.defaultPrevented&&!pasted.event.defaultPrevented,'text clipboard untouched');const before=JSON.stringify(await snapshot());await paste('unrelated clipboard text');assert(JSON.stringify(await snapshot())===before,'invalid clipboard leaves diagram intact');clipboardDenied=true;command('paste','btn-edit-menu');await wait(30);assert($('error-message').textContent.includes('Ctrl/Cmd+V'),'menu permission fallback guidance');clipboardDenied=false;
});
await test('Paste here uses the context point; repeated pastes remain separate and autosave persists the section',async()=>{
 const h=await open();select('A');const text=await copy();const b=$('canvas').getBoundingClientRect(),x=b.x+b.width*.7,y=b.y+b.height*.7;
 $('canvas').dispatchEvent(new win.MouseEvent('contextmenu',{bubbles:true,cancelable:true,clientX:x,clientY:y}));const action=doc.querySelector('#editing-overlay [data-command=paste-here]');assert(action,'Paste here available');action.click();await wait(30);let m=await snapshot();assert(m.nodes.length===3,'context paste');const newNode=m.nodes.at(-1),v=m.settings.view;assert(Math.abs(newNode.x+newNode.width/2-(x-b.x-v.x)/v.scale)<1,'paste centre at pointer');await paste(text);m=await snapshot();assert(m.nodes.length===4&&new Set(m.nodes.map(n=>n.id)).size===4,'repeated paste fresh IDs');command('autosave');await until(()=>h.json().nodes.length===4);click('btn-undo');await until(()=>h.json().nodes.length===3);command('autosave');
});

await test('first focused edit can be undone after autosave even when Open cleared the previous history',async()=>{
 const h=await open();assert($('btn-undo').disabled,'fresh history');command('autosave');await until(()=>$('file-info').dataset.autosave==='true');select('A');const label=$('property-label');label.focus();input('property-label','First focused edit');await until(()=>h.json().nodes[0].label==='First focused edit');assert(!$('btn-undo').disabled&&doc.activeElement===label,'pending session offers Undo without blur');click('btn-undo');await until(()=>h.json().nodes[0].label==='Source');assert($('btn-undo').disabled,'one whole input session undone');command('autosave');
});
await test('failed Save as and external-conflict Save as preserve the original disk file',async()=>{
 const h=await open();select('A');input('property-notes','My changes');chosenSave=diskHandle('failed.json','original destination');chosenSave.fail(new Error('Write blocked'));command('save-as');await until(()=>$('file-state').textContent==='Save paused');assert($('file-name').textContent==='working.json'&&h.json().nodes[0].notes==='Original note','failed Save as keeps connection');chosenSave.fail(null);await save();assert(h.json().nodes[0].notes==='My changes','retry uses original file');const external=fixture();external.nodes[0].notes='External edit';h.external(external);input('property-notes','Conflict changes');await save();chosenSave=diskHandle('separate.json','');command('save-as');await until(()=>$('file-name').textContent==='separate.json');assert(h.json().nodes[0].notes==='External edit','Save as protects external changes');assert(chosenSave.json().nodes[0].notes==='Conflict changes','new file has my changes');
});
await test('a clipboard permission delay cannot paste into a different document opened meanwhile',async()=>{
 await open();select('A');await copy();const gate=deferred();clipboardGate=gate;command('paste','btn-edit-menu');await open(fixture(),'while-reading.json');gate.resolve();clipboardGate=null;await until(()=>$('status').textContent.includes('Paste cancelled'));assert((await snapshot()).nodes.length===2,'stale clipboard read cannot edit newly opened file');
});
await test('keyboard paste reveals a copied section when its original coordinates are offscreen',async()=>{
 await open();select('A');const text=await copy(),target=emptyModel();target.settings.view={x:-4000,y:-4000,scale:1};await open(target,'distant-view.json');clipboardEvent('paste',text);const n=doc.querySelector('.diagram-node.selected'),b=n.getBoundingClientRect(),v=$('canvas').getBoundingClientRect();assert(b.right>v.left&&b.left<v.right&&b.bottom>v.top&&b.top<v.bottom,'pasted node visible');assert((await snapshot()).nodes[0].notes==='Original note','data preserved');
});
await test('a very wide section reveals an actual pasted node rather than an empty bounding-box centre',async()=>{
 const wide=emptyModel();wide.nodes=[rect('A',0,0),rect('B',4000,0)];await open(wide,'wide.json');select('A');select('B',true);const text=await copy(),target=emptyModel();target.settings.view={x:-8000,y:-8000,scale:1};await open(target,'far-empty.json');clipboardEvent('paste',text);const b=$('canvas').getBoundingClientRect();assert([...doc.querySelectorAll('.diagram-node.selected')].some(n=>{const r=n.getBoundingClientRect();return r.right>b.left&&r.left<b.right&&r.bottom>b.top&&r.top<b.bottom;}),'an actual pasted object is visible');const m=await snapshot();assert(m.nodes[1].x-m.nodes[0].x===4000&&m.nodes[1].y===m.nodes[0].y,'relative section layout unchanged');
});
await test('unapplied source draft is protected by New and does not get silently treated as saved JSON',async()=>{
 await open();input('editor','flowchart TD\n Unapplied[Draft]');click('btn-new');await until(()=>$('file-dialog').open);const buttons=[...doc.querySelectorAll('#file-dialog-actions button')];assert(buttons.find(b=>b.textContent==='Save and continue').disabled,'apply source before saving project');buttons.find(b=>b.textContent==='Cancel').click();assert($('source-state').textContent==='Unapplied draft'&&$('editor').value.includes('Unapplied'),'draft retained');input('editor','');click('btn-new');await until(()=>$('file-dialog').open);assert(doc.querySelector('#file-dialog-actions button').disabled,'empty unapplied draft still protected');[...doc.querySelectorAll('#file-dialog-actions button')].find(b=>b.textContent==='Cancel').click();assert($('editor').value===''&&$('source-state').textContent==='Unapplied draft','empty source draft retained');click('btn-discard');await save();
});
await test('browser recovery survives refresh with focused notes and restores detached with autosave off',async()=>{
 await open();select('A');const notes=$('property-notes');notes.focus();input('property-notes','Recovered after refresh 中文 🚀');input('editor','flowchart TD\n Draft[Unapplied draft]');
 const loaded=new Promise(r=>frame.addEventListener('load',r,{once:true}));frame.src='../viewer.html?v=recovery-check';await loaded;win=frame.contentWindow;doc=frame.contentDocument;await until(()=>$('loading').hidden);installAPIs();assert($('file-notice').textContent.includes('Browser recovery available'),'recovery offered');[...doc.querySelectorAll('#file-notice button')].find(b=>b.textContent==='Restore recovery').click();await until(()=>doc.querySelector('[data-tree-id=A]'));select('A');assert($('property-notes').value==='Recovered after refresh 中文 🚀','focused valid notes recovered');assert($('editor').value.includes('Unapplied draft')&&$('source-state').textContent==='Unapplied draft','source draft recovered separately');assert($('file-info').dataset.connected==='false'&&$('file-info').dataset.autosave==='false','recovery has no assumed permission or binding');click('btn-discard');chosenSave=diskHandle('recovered.json','');await save();assert(chosenSave.json().nodes[0].notes==='Recovered after refresh 中文 🚀','recovery can become a working file');
});
await test('connected files keep saving when picker APIs become unavailable',async()=>{
 const h=await open(fixture(),'retained.json');const before=downloads.length;win.showOpenFilePicker=undefined;win.showSaveFilePicker=undefined;
 try{select('A');input('property-notes','Still writing to the original');await save();assert(h.json().nodes[0].notes==='Still writing to the original','Save uses retained handle');assert(downloads.length===before&&$('file-state').textContent==='Saved','no replacement download');command('autosave');input('property-notes','Autosave still works');await until(()=>h.json().nodes[0].notes==='Autosave still works');command('autosave');}finally{installAPIs();}
});
await test('Save only requires the save picker when choosing a new working file',async()=>{
 click('btn-new');await discard();await until(()=>!doc.querySelector('.diagram-node'));chosenSave=diskHandle('save-only.json','');win.showOpenFilePicker=undefined;const before=downloads.length;
 try{await save();assert($('file-name').textContent==='save-only.json'&&$('file-info').dataset.connected==='true','independent save capability');assert(downloads.length===before&&chosenSave.json().nodes.length===0,'native Save did not need Open');}finally{installAPIs();}
});
await test('unsupported browsers retain Open and Save download fallback with autosave unavailable',async()=>{
 click('btn-new');await discard();await until(()=>!doc.querySelector('.diagram-node'));win.showOpenFilePicker=undefined;win.showSaveFilePicker=undefined;const f=fixture(),transfer=new win.DataTransfer();transfer.items.add(new win.File([JSON.stringify(f)],'fallback.json',{type:'application/json'}));$('file-input').files=transfer.files;$('file-input').dispatchEvent(new win.Event('change',{bubbles:true}));await until(()=>$('file-name').textContent==='fallback.json');assert($('file-info').dataset.connected==='false','fallback Open is detached');select('A');input('property-notes','Fallback save');const previous=downloads.length;await save();assert(downloads.length===previous+1,'Save downloaded JSON');assert($('file-state').textContent==='Downloaded copy','copy status explicit');click('btn-project-menu');assert(!doc.querySelector('[data-command=autosave]').disabled,'browser preference remains available');key('Escape');await save();
});

await test('a blocked direct-save picker degrades to a downloaded copy in the same action',async()=>{
 installAPIs();click('btn-new');await discard();await until(()=>!doc.querySelector('.diagram-node'));win.showSaveFilePicker=async()=>{throw new win.DOMException('Feature policy blocked','SecurityError');};const before=downloads.length;click('btn-save');await until(()=>downloads.length>before);assert($('file-state').textContent==='Downloaded copy'&&$('status').textContent.includes('Click Save again'),'fallback offers a retry');assert(!$('error-banner').hidden? !$('error-message').textContent.includes('Feature policy blocked'):true,'no raw security error');
});
await test('a temporary blocked picker can reconnect on the next Save without refreshing',async()=>{
 installAPIs();chosenSave=diskHandle('retry-without-refresh.json','');const before=downloads.length;await save();assert($('file-info').dataset.connected==='true'&&$('file-state').textContent==='Saved','next click retries native picker');assert(downloads.length===before&&$('file-name').textContent==='retry-without-refresh.json','new working file connected');
});
await test('blocked Save as retains a connected file, unsaved edits, and later native saving',async()=>{
 const h=await open();select('A');input('property-notes','Retain my working file');win.showSaveFilePicker=async()=>{throw new win.DOMException('Temporarily blocked','SecurityError');};const before=downloads.length;command('save-as');await until(()=>downloads.length===before+1);assert($('file-name').textContent==='working.json'&&$('file-info').dataset.connected==='true'&&$('file-state').textContent==='Unsaved changes','copy cannot claim original file saved');assert(h.json().nodes[0].notes==='Original note','original disk remains unchanged');await save();assert(h.json().nodes[0].notes==='Retain my working file'&&downloads.length===before+1,'Save still writes original handle');installAPIs();chosenSave=diskHandle('retry-save-as.json','');command('save-as');await until(()=>$('file-name').textContent==='retry-save-as.json'&&$('file-state').textContent==='Saved');assert(chosenSave.json().nodes[0].notes==='Retain my working file','Save as can retry without refreshing');
});
await test('autosave preference survives New, another file, browser refresh and recovery without storing it in JSON',async()=>{
 const initialLoad=new Promise(r=>frame.addEventListener('load',r,{once:true}));frame.src='../viewer.html?v=additional-refinements';await initialLoad;win=frame.contentWindow;doc=frame.contentDocument;await until(()=>$('loading').hidden);installAPIs();await open();command('autosave');assert($('file-info').dataset.autosave==='true','enabled');click('btn-new');await discard();await until(()=>!doc.querySelector('.diagram-node'));assert($('file-info').dataset.autosave==='true'&&$('file-info').dataset.connected==='false','New retains preference without a handle');
 const h=await open(fixture(),'preference.json');select('A');input('property-notes','Automatically saved in the next document');await until(()=>h.json().nodes[0].notes.includes('next document'));assert(!('autosave' in h.json().settings),'preference excluded from JSON');
 const loaded=new Promise(r=>frame.addEventListener('load',r,{once:true}));frame.src='../viewer.html?v=preference-refresh';await loaded;win=frame.contentWindow;doc=frame.contentDocument;await until(()=>$('loading').hidden);installAPIs();assert($('file-info').dataset.autosave==='true','refresh reads browser preference');assert($('file-info').dataset.connected==='false','refresh cannot assume file access');command('autosave');assert($('file-info').dataset.autosave==='false','off choice stored');
});
await test('Recent files opens the current disk file, deduplicates handles and keeps cancelled or invalid imports out',async()=>{
 const h=await open(fixture(),'recent-live.json');await open(fixture(),'other-recent.json');h.external({...fixture(),nodes:[{...fixture().nodes[0],notes:'Fresh content from disk'},fixture().nodes[1]]});command('recent');await until(()=>$('file-dialog').open&&doc.querySelector('[aria-label="Open recent-live.json"]'));doc.querySelector('[aria-label="Open recent-live.json"]').click();await until(()=>$('file-name').textContent==='recent-live.json');select('A');assert($('property-notes').value==='Fresh content from disk','recent uses disk content');assert($('file-info').dataset.connected==='true','recent reconnects working file');
 select('A');input('property-notes','Dirty before recent open');command('recent');await until(()=>$('file-dialog').open);assert(doc.querySelectorAll('[aria-label="Open recent-live.json"]').length===1,'same handle deduplicated');doc.querySelector('[aria-label="Open other-recent.json"]').click();await until(()=>$('file-dialog-title').textContent==='Unsaved changes');[...doc.querySelectorAll('#file-dialog-actions button')].find(b=>b.textContent==='Cancel').click();assert($('file-name').textContent==='recent-live.json'&&$('property-notes').value==='Dirty before recent open','cancel retains current diagram');await save();
 chosenOpen=diskHandle('invalid-recent.json','invalid JSON');click('btn-open');await wait(50);command('recent');await until(()=>$('file-dialog').open);assert(!doc.querySelector('[aria-label="Open invalid-recent.json"]'),'invalid file excluded');doc.querySelector('[aria-label="Remove other-recent.json from recent files"]').click();await until(()=>!doc.querySelector('[aria-label="Open other-recent.json"]'));[...doc.querySelectorAll('#file-dialog-actions button')].find(b=>b.textContent==='Close').click();
});
await test('Recent browser copies persist in IndexedDB across refresh and reopen as detached projects',async()=>{
 const f=fixture(),transfer=new win.DataTransfer();transfer.items.add(new win.File([JSON.stringify(f)],'persisted-copy.json',{type:'application/json'}));$('file-input').files=transfer.files;$('file-input').dispatchEvent(new win.Event('change',{bubbles:true}));await until(()=>$('file-name').textContent==='persisted-copy.json');await wait(50);
 const loaded=new Promise(r=>frame.addEventListener('load',r,{once:true}));frame.src='../viewer.html?v=recent-refresh';await loaded;win=frame.contentWindow;doc=frame.contentDocument;await until(()=>$('loading').hidden);installAPIs();command('recent');await until(()=>doc.querySelector('[aria-label="Open persisted-copy.json"]'));const choose=doc.querySelector('[aria-label="Open persisted-copy.json"]');assert(choose.textContent.includes('Browser copy'),'copy distinguished');choose.click();await until(()=>$('file-name').textContent==='persisted-copy.json');assert($('file-info').dataset.connected==='false','copy never claims disk binding');select('A');assert($('property-description').value==='Request entry','content restored');
});
await test('description mode is selectable on nodes and zones, wraps above children, survives clipboard and SVG export',async()=>{
 const m=fixture();m.zones=[{id:'Z',label:'Stable zone name',description:'Zone ownership and operational context for request processing\nDetailed responsibilities shown above its children',parentId:null,x:20,y:50,width:450,height:200}];m.nodes[0].parentId='Z';m.nodes[1].parentId='Z';await open(m,'description.json');select('A');$('property-show-description').checked=true;$('property-show-description').dispatchEvent(new win.Event('change',{bubbles:true}));assert(doc.querySelector('.diagram-node[data-object-id=A] text').textContent.includes('Request entry'),'node description rendered');assert($('property-label').value==='Source','label retained');input('property-description','Detailed request processing with whole words\nSecond paragraph');await save();assert(chosenOpen.json().nodes[0].showDescription===true,'toggle persisted');const pasted=clipboardEvent('copy').data.getData('text/plain');clipboardEvent('paste',pasted);assert((await snapshot()).nodes.at(-1).showDescription===true,'clipboard preserves mode');click('btn-undo');select('Z');$('property-show-description').checked=true;$('property-show-description').dispatchEvent(new win.Event('change',{bubbles:true}));const title=doc.querySelector('.zone-title[data-object-id=Z]');assert([...title.querySelectorAll('tspan')].map(t=>t.textContent).join(' ').includes('operational context')&&title.querySelectorAll('tspan').length>1,'zone description wrapped');assert(doc.querySelector('[data-tree-id=Z] .tree-object').textContent.includes('Stable zone name'),'hierarchy label retained');const saved=await snapshot(),z=saved.zones[0],a=saved.nodes[0];assert(a.y>=z.y+doc.querySelector('.diagram-zone[data-object-id=Z] .zone-header').height.baseVal.value,'child clears description header');click('btn-undo');assert(!(await snapshot()).zones[0].showDescription,'toggle undone');click('btn-redo');assert((await snapshot()).zones[0].showDescription,'toggle redone');select('A');$('property-show-description').checked=false;$('property-show-description').dispatchEvent(new win.Event('change',{bubbles:true}));assert(doc.querySelector('.diagram-node[data-object-id=A] text').textContent==='Source','label restored');
 command('export');doc.querySelector('#editing-flyout [data-command=export-svg]').click();await until(()=>downloads.at(-1).type.startsWith('image/svg+xml'));const svg=await downloads.at(-1).text();assert(svg.includes('operational context'),'export uses description display');
});
await test('recent files refresh across tabs and concurrent IndexedDB updates preserve both entries',async()=>{
 const {createRecentFiles}=await import('../recent-files.mjs');const a=createRecentFiles(),b=createRecentFiles();await Promise.all([a.ready,b.ready]);await Promise.all([a.remember({name:'parallel-a.json',content:JSON.stringify(fixture())}),b.remember({name:'parallel-b.json',content:JSON.stringify(fixture())})]);command('recent');await until(()=>$('file-dialog').open);assert(doc.querySelector('[aria-label="Open parallel-a.json"]')&&doc.querySelector('[aria-label="Open parallel-b.json"]'),'both tabs preserved and discovered by the open editor');[...doc.querySelectorAll('#file-dialog-actions button')].find(b=>b.textContent==='Close').click();await a.refresh();await a.remove(a.list().find(r=>r.name==='parallel-a.json').id);await b.refresh();assert(b.list().some(r=>r.name==='parallel-b.json')&&!b.list().some(r=>r.name==='parallel-a.json'),'deletion keeps other tab entry');
});
out.dataset.complete='true';out.dataset.passed=String(results.every(r=>r.pass));out.textContent=JSON.stringify({passed:results.filter(r=>r.pass).length,total:results.length,results},null,2);
