const frame=document.getElementById('app'),out=document.getElementById('results'),results=[];
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){for(let i=0;i<250;i++){if(fn())return;await wait(20);}throw new Error('Timed out waiting for editor');}
await until(()=>frame.contentDocument?.getElementById('loading')?.hidden);
const win=frame.contentWindow,doc=frame.contentDocument,$=id=>doc.getElementById(id);let blobs=[];
const create=win.URL.createObjectURL.bind(win.URL);win.URL.createObjectURL=blob=>{blobs.push(blob);return create(blob);};
// Exercise the real export handlers without generating repeated OS downloads in this test page.
const anchorClick=win.HTMLAnchorElement.prototype.click;
win.HTMLAnchorElement.prototype.click=function(){if(!this.download)anchorClick.call(this);};
const fetchLocal=win.fetch.bind(win);win.fetch=(url,...args)=>{if(new URL(url,win.location.href).origin!==win.location.origin)throw new Error('External network access unavailable');return fetchLocal(url,...args);};
function assert(ok,message){if(!ok)throw new Error(message);}
async function test(name,fn){try{await fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}out.textContent=JSON.stringify(results,null,2);}
function click(id){$(id).click();}
function input(id,value){$(id).value=value;$(id).dispatchEvent(new win.Event('input',{bubbles:true}));}
function change(id,value){$(id).value=value;$(id).dispatchEvent(new win.Event('change',{bubbles:true}));}
function key(key,extra={}){$('viewport').dispatchEvent(new win.KeyboardEvent('keydown',{key,bubbles:true,...extra}));}
async function saved(){const previous=blobs.length;click('btn-save');assert(blobs.length>previous,'save produced a project blob');return JSON.parse(await blobs.at(-1).text());}
async function apply(source){input('editor',source);click('btn-apply');await until(()=>$('loading').hidden);}
function hitNode(id,shiftKey=false){const n=doc.querySelector(`.diagram-node[data-object-id="${id}"] .node-shape`),b=n.getBoundingClientRect();n.dispatchEvent(new win.PointerEvent('pointerdown',{bubbles:true,isPrimary:true,button:0,pointerId:1,clientX:b.x+b.width/2,clientY:b.y+b.height/2,shiftKey}));$('viewport').dispatchEvent(new win.PointerEvent('pointerup',{bubbles:true,isPrimary:true,button:0,pointerId:1,clientX:b.x+b.width/2,clientY:b.y+b.height/2}));}
// Pointer capture needs a native pointer in normal use. Synthetic gestures in this harness
// use an inert capture implementation; native capture and dragging are also tested via the UI.
const viewport=$('viewport');viewport.setPointerCapture=()=>{};viewport.hasPointerCapture=()=>false;
function pointer(type,x,y,target=$('canvas'),extra={}){target.dispatchEvent(new win.PointerEvent(type,{bubbles:true,isPrimary:true,button:0,pointerId:2,clientX:x,clientY:y,...extra}));}
const source='flowchart LR\n subgraph Outer[Outer zone]\n subgraph Inner[Inner zone]\n A[Alpha]\n B(Beta)\n end\n end\n C[(Database)]\n A one@-->|reads| B\n B two@--> C';
await test('source import replaces structure and preserves nested hierarchy',async()=>{await apply(source);const m=await saved();assert(m.nodes.length===3&&m.edges.length===2&&m.zones.length===2,'all objects');assert(m.nodes.find(n=>n.id==='A').parentId==='Inner','nested membership');});
await test('dragging the title overlay moves its whole zone once and undo restores it',async()=>{
 const before=await saved(),backing=doc.querySelector('.zone-title[data-object-id="Outer"] .zone-label-backing'),b=backing.getBoundingClientRect();
 const opacity=Number(win.getComputedStyle(backing).fillOpacity);assert(opacity>0&&opacity<1,'live title backing is translucent');
 pointer('pointerdown',b.x+b.width/2,b.y+b.height/2,backing);pointer('pointermove',b.x+b.width/2+40,b.y+b.height/2+25,viewport);await wait(40);pointer('pointerup',b.x+b.width/2+40,b.y+b.height/2+25,viewport);
 const after=await saved(),dx=40/before.settings.view.scale,dy=25/before.settings.view.scale;
 for(const old of [...before.zones,...before.nodes.filter(n=>n.parentId==='Inner')]){const moved=[...after.zones,...after.nodes].find(n=>n.id===old.id);assert(Math.abs(moved.x-old.x-dx)<.01&&Math.abs(moved.y-old.y-dy)<.01,'descendant moved once: '+old.id);}
 assert(JSON.stringify(after.nodes.find(n=>n.id==='C'))===JSON.stringify(before.nodes.find(n=>n.id==='C')),'external node stays fixed');
 click('btn-undo');assert(JSON.stringify(await saved())===JSON.stringify(before),'undo restores full geometry and view');key('Escape');
});
await test('invalid drafts preserve diagram and history, and typing never relayouts',async()=>{const before=await saved();input('editor','flowchart TD\n A[broken');assert(JSON.stringify((await saved()).nodes)===JSON.stringify(before.nodes),'typing leaves nodes');click('btn-apply');await until(()=>$('loading').hidden);assert(!$('error-banner').hidden,'error shown');assert($('editor').value.includes('broken'),'draft retained');assert(JSON.stringify((await saved()).nodes)===JSON.stringify(before.nodes),'invalid source leaves valid diagram');click('btn-discard');});
await test('adding and editing a node preserves ID and updates generated source',async()=>{doc.querySelector('[data-tool="node"]').click();const b=$('canvas').getBoundingClientRect();pointer('pointerdown',b.x+80,b.y+180);change('property-label','New decision "quoted" 中文');change('property-shape','diamond');const m=await saved(),n=m.nodes.find(n=>n.id==='Node1');assert(n?.shape==='diamond'&&n.label.includes('中文'),'new node properties');assert($('editor').value.includes('Node1{'),'generated shape');});
await test('shape labels fit measured text, including long and wide glyphs',async()=>{change('property-label','MMMMMMMMMMMMMMMMMMMMMMMM\n中文中文中文中文中文中文中文');for(const shape of ['rectangle','rounded','diamond','circle','cylinder']){change('property-shape',shape);const node=doc.querySelector('[data-object-id="Node1"]'),shapeBox=node.querySelector('.node-shape').getBBox(),text=node.querySelector('text').getBBox();assert(text.x>=shapeBox.x&&text.y>=shapeBox.y&&text.x+text.width<=shapeBox.x+shapeBox.width&&text.y+text.height<=shapeBox.y+shapeBox.height,'text fits '+shape);}});
await test('parent changes visibly relocate objects and deleting zones retains contents',async()=>{const before=await saved(),original=before.nodes.find(n=>n.id==='Node1');change('property-parent-zone','Inner');let m=await saved(),n=m.nodes.find(n=>n.id==='Node1');assert(n.parentId==='Inner','reparent');assert(n.x!==original.x||n.y!==original.y,'parent change moves the node');assert(!doc.getElementById('btn-group')&&!doc.getElementById('btn-ungroup'),'group commands removed');key('Escape');const row=doc.querySelector('[data-tree-id="Inner"] .tree-object');row.click();click('btn-delete');m=await saved();assert(!m.zones.some(z=>z.id==='Inner'),'zone removed');assert(m.nodes.filter(n=>n.parentId==='Outer').length===3,'contents retained');click('btn-undo');});
await test('multi-selection alignment, distribution and grid nudges are undoable',async()=>{key('Escape');hitNode('A');hitNode('B',true);hitNode('Node1',true);change('alignment','left');let m=await saved(),selected=m.nodes.filter(n=>['A','B','Node1'].includes(n.id));assert(selected.every(n=>Math.abs(n.x-selected[0].x)<.01),'aligned');change('alignment','distribute-y');m=await saved();const arranged=m.nodes.filter(n=>['A','B','Node1'].includes(n.id)).sort((a,b)=>a.y-b.y);const gaps=arranged.slice(1).map((n,i)=>n.y-(arranged[i].y+arranged[i].height));assert(Math.abs(gaps[0]-gaps[1])<.01,'distributed');$('snap-grid').checked=true;$('snap-grid').dispatchEvent(new win.Event('change',{bubbles:true}));m=await saved();key('ArrowRight');const nudged=await saved();assert(nudged.nodes.find(n=>n.id==='A').x===m.nodes.find(n=>n.id==='A').x+20,'grid nudge');click('btn-undo');assert((await saved()).nodes.find(n=>n.id==='A').x===m.nodes.find(n=>n.id==='A').x,'undo nudge');click('btn-redo');assert((await saved()).nodes.find(n=>n.id==='A').x===m.nodes.find(n=>n.id==='A').x+20,'redo nudge');});
await test('zone creation, resizing, naming and deletion retain contents and title bounds',async()=>{key('Escape');doc.querySelector('[data-tool="zone"]').click();const b=$('canvas').getBoundingClientRect();pointer('pointerdown',b.x+120,b.y+220);change('property-label','A zone title that must stay inside its resized box');change('property-width','160');let m=await saved(),z=m.zones.find(z=>z.id==='Zone1');assert(z&&z.width>160,'title expands minimum size');assert(Number($('property-width').value)===Math.round(z.width),'inspector shows actual constrained size');change('property-parent-zone','Outer');assert((await saved()).zones.find(z=>z.id==='Zone1').parentId==='Outer','nested new zone');click('btn-delete');assert(!(await saved()).zones.some(z=>z.id==='Zone1'),'zone deleted');click('btn-undo');assert((await saved()).zones.some(z=>z.id==='Zone1'),'undo zone deletion');click('btn-delete');});
await test('edge properties, endpoints, loops and parallel connections update without relayout',async()=>{key('Escape');const edge=doc.querySelector('[data-object-id="one"] .edge-hit');pointer('pointerdown',1,1,edge);const before=(await saved()).nodes;change('property-label','Updated edge');change('property-direction','both');change('property-line-style','dashed');change('property-target','A');let m=await saved(),e=m.edges.find(e=>e.id==='one');assert(e.target==='A'&&e.direction==='both'&&e.style==='dashed','edited loop');assert(JSON.stringify(m.nodes)===JSON.stringify(before),'nodes stayed put');change('property-target','B');change('property-routing','straight');assert(doc.querySelector('[data-edge-id="one"]').getAttribute('d').split(' L').length===2,'straight connection');change('property-routing','orthogonal');});
await test('source application retains manual centres and unsupported imports do not replace the diagram',async()=>{const before=await saved();const evolved=$('editor').value.replace('Alpha','Changed alpha')+'\n Extra[Extra node]\n';await apply(evolved);const after=await saved();const a=before.nodes.find(n=>n.id==='A'),b=after.nodes.find(n=>n.id==='A');assert(Math.abs(a.x+a.width/2-b.x-b.width/2)<.01&&Math.abs(a.y+a.height/2-b.y-b.height/2)<.01,'manual centre retained');assert(after.nodes.some(n=>n.id==='Extra'),'new source node');await apply('sequenceDiagram\n A->>B: unsupported');assert(!$('error-banner').hidden,'unsupported error');assert((await saved()).nodes.length===after.nodes.length,'last diagram retained');click('btn-discard');});
await test('layout preferences and draft edits preserve positions; explicit layout is undoable',async()=>{const before=await saved();change('direction','BT');change('layout-mode','hierarchical');assert(JSON.stringify((await saved()).nodes)===JSON.stringify(before.nodes),'preferences do not relayout');input('editor',$('editor').value+'%% Keep this draft\n');const draft=$('editor').value;click('btn-layout');await until(()=>$('loading').hidden);assert($('editor').value===draft,'layout preserves draft');const laidOut=await saved();assert(JSON.stringify(laidOut.nodes)!==JSON.stringify(before.nodes),'explicit layout changed positions');click('btn-undo');assert(JSON.stringify((await saved()).nodes)===JSON.stringify(before.nodes),'undo restores arrangement');assert($('editor').value===draft,'undo preserves draft');click('btn-discard');});
await test('cancelled node drag restores model and creates no history entry',async()=>{key('Escape');const before=await saved(),n=doc.querySelector('[data-object-id="A"] .node-shape'),b=n.getBoundingClientRect();pointer('pointerdown',b.x+20,b.y+10,n);pointer('pointermove',b.x+100,b.y+70,viewport);await wait(40);key('Escape');const after=await saved();assert(JSON.stringify(after)===JSON.stringify(before),'cancel restored full model');});
await test('save/open restores exact geometry and settings without relayout',async()=>{const original=await saved();key('Escape');hitNode('A');key('ArrowDown',{shiftKey:true});const transfer=new win.DataTransfer();transfer.items.add(new win.File([JSON.stringify(original)],'saved.json',{type:'application/json'}));$('file-input').files=transfer.files;$('file-input').dispatchEvent(new win.Event('change',{bubbles:true}));await until(()=>$('loading').hidden);assert(!$('counts').textContent.includes('Unsaved changes'),'opened saved project starts clean');assert(JSON.stringify(await saved())===JSON.stringify(original),'project fully restored');});
await test('SVG, PNG and Mermaid exports use the current model and exclude handles',async()=>{for(const format of ['svg','png','mermaid']){$('export-format').value=format;let length=blobs.length;click('btn-export');await until(()=>blobs.length>length);if(format==='png')await until(()=>blobs.at(-1).type==='image/png');const blob=blobs.at(-1);if(format==='png'){assert(blob.size>1000,'PNG contains image');const bytes=new Uint8Array(await blob.arrayBuffer());assert(bytes.slice(0,8).join(',')==='137,80,78,71,13,10,26,10','PNG signature');}else{const text=await blob.text();assert(format==='svg'?text.includes('viewBox=')&&!text.includes('editor-only'):text.includes('flowchart BT'),'valid export '+format);}}});
await test('deleting nodes removes incident edges in one undoable action',async()=>{key('Escape');hitNode('B');const before=await saved();click('btn-delete');let m=await saved();assert(!m.nodes.some(n=>n.id==='B')&&!m.edges.some(e=>e.source==='B'||e.target==='B'),'node and edges deleted');click('btn-undo');m=await saved();assert(JSON.stringify(m.nodes)===JSON.stringify(before.nodes)&&JSON.stringify(m.edges)===JSON.stringify(before.edges),'undo restores nodes and edges');});
await test('dragging handles creates parallel edges and self-loops, then reconnects an endpoint',async()=>{await apply('flowchart LR\n A[Alpha]\n B[Beta]\n C[(Database)]\n A base@--> B\n B next@--> C');click('btn-layout');await until(()=>$('loading').hidden);click('btn-fit');const centre=id=>{const b=doc.querySelector(`.diagram-node[data-object-id="${id}"] .node-shape`).getBoundingClientRect();return{x:b.x+b.width/2,y:b.y+b.height/2};};async function connect(target){doc.querySelector('[data-tool="connect"]').click();const source=doc.querySelector('.diagram-node[data-object-id="A"]');const sb=source.getBoundingClientRect();pointer('pointermove',sb.x+sb.width/2,sb.y+sb.height/2,source);const handle=doc.querySelector('[data-connect="A"][data-side="east"]'),b=handle.getBoundingClientRect(),p=centre(target);pointer('pointerdown',b.x+b.width/2,b.y+b.height/2,handle);pointer('pointermove',p.x,p.y,viewport);await wait(25);pointer('pointerup',p.x,p.y,viewport);}await connect('B');await connect('A');let m=await saved();assert(m.edges.filter(e=>e.source==='A'&&e.target==='B').length===2,'parallel edge created');const loop=m.edges.find(e=>e.source==='A'&&e.target==='A');assert(loop&&doc.querySelector(`[data-edge-id="${loop.id}"]`).getAttribute('d').split(' L').length>=4,'self-loop route');key('Escape');const path=doc.querySelector('[data-object-id="Edge1"] .edge-hit');pointer('pointerdown',1,1,path);const handle=doc.querySelector('[data-reconnect="Edge1"][data-end="target"]'),b=handle.getBoundingClientRect(),p=centre('C');pointer('pointerdown',b.x+b.width/2,b.y+b.height/2,handle);pointer('pointermove',p.x,p.y,viewport);await wait(25);pointer('pointerup',p.x,p.y,viewport);m=await saved();assert(m.edges.find(e=>e.id==='Edge1').target==='C','drag endpoint reattached');});
await test('parallel edge attachments and reconnect handles remain separate after moving and reshaping nodes',async()=>{
 await apply('flowchart LR\n A[Left]\n B[(Right)]\n A one@--> B\n A two@--> B\n A three@--> B');click('btn-layout');await until(()=>$('loading').hidden);click('btn-fit');
 const points=id=>doc.querySelector(`[data-edge-id="${id}"]`).getAttribute('d').match(/-?\d+(?:\.\d+)?(?:e[+-]?\d+)?/gi).map(Number);
 const check=()=>{const lines=['one','two','three'].map(points),sources=lines.map(p=>p[0]+','+p[1]),targets=lines.map(p=>p.at(-2)+','+p.at(-1));assert(new Set(sources).size===3&&new Set(targets).size===3,'separate source and destination arrow tips');};check();
 hitNode('A');change('property-shape','circle');key('ArrowDown',{shiftKey:true});check();
 const line=doc.querySelector('[data-object-id="one"] .edge-hit');pointer('pointerdown',1,1,line);
 const path=points('one'),handle=doc.querySelector('[data-reconnect="one"][data-end="target"]');assert(Math.abs(Number(handle.getAttribute('cx'))-path.at(-2))<.001&&Math.abs(Number(handle.getAttribute('cy'))-path.at(-1))<.001,'reconnect handle follows the spaced endpoint');
 click('btn-undo');check();
});
await test('pending node, edge, and zone labels commit before canvas actions and saving',async()=>{
 hitNode('A');input('property-label','Renamed before clicking away');const b=$('canvas').getBoundingClientRect();pointer('pointerdown',b.x+5,b.y+150);pointer('pointerup',b.x+5,b.y+150,viewport);assert((await saved()).nodes.find(n=>n.id==='A').label==='Renamed before clicking away','canvas click retains typing');
 const line=doc.querySelector('[data-object-id="one"] .edge-hit');pointer('pointerdown',1,1,line);input('property-label','Edge draft saved');assert((await saved()).edges.find(e=>e.id==='one').label==='Edge draft saved','Save commits edge typing');
 click('btn-new');doc.querySelector('[data-tool="zone"]').click();pointer('pointerdown',b.x+80,b.y+100);input('property-label','Zone draft retained');doc.querySelector('[data-tool="node"]').click();assert((await saved()).zones[0].label==='Zone draft retained','tool change retains zone typing');key('Escape');
});
await test('New clears the canvas and source draft as one undoable action',async()=>{
 const before=await saved();input('editor','An unapplied draft');click('btn-new');const empty=await saved();assert(!empty.nodes.length&&!empty.edges.length&&!empty.zones.length,'empty canvas');assert($('editor').value==='flowchart TD\n','fresh Mermaid');click('btn-undo');assert(JSON.stringify((await saved()).zones)===JSON.stringify(before.zones),'Undo restores prior project');click('btn-redo');assert(!(await saved()).zones.length,'Redo restores empty canvas');
});
await test('new objects inherit the innermost containing zone and move with it',async()=>{
 const b=$('canvas').getBoundingClientRect();doc.querySelector('[data-tool="zone"]').click();pointer('pointerdown',b.x+40,b.y+80);change('property-label','Outer');doc.querySelector('[data-tool="zone"]').click();pointer('pointerdown',b.x+60,b.y+130);change('property-label','Inner');doc.querySelector('[data-tool="node"]').click();pointer('pointerdown',b.x+140,b.y+220);
 const before=await saved();assert(before.zones.find(z=>z.id==='Zone2').parentId==='Zone1','new zone is nested');assert(before.nodes[0].parentId==='Zone2','new node belongs to inner zone');
 const header=doc.querySelector('.zone-title[data-object-id="Zone1"] rect'),hb=header.getBoundingClientRect();pointer('pointerdown',hb.x+hb.width/2,hb.y+hb.height/2,header);pointer('pointermove',hb.x+hb.width/2+40,hb.y+hb.height/2+30,viewport);await wait(30);pointer('pointerup',hb.x+hb.width/2+40,hb.y+hb.height/2+30,viewport);
 const moved=await saved();assert(Math.abs(moved.nodes[0].x-before.nodes[0].x-40)<.001&&Math.abs(moved.nodes[0].y-before.nodes[0].y-30)<.001,'nested contents move once');click('btn-undo');
});
await test('fresh source fits the viewport while edits to existing IDs preserve the view',async()=>{
 await apply('flowchart LR\n Fresh[Fresh start]');let m=await saved();assert(m.settings.view.scale>1,'fresh diagram fits at readable zoom');const view=JSON.stringify(m.settings.view);await apply($('editor').value.replace('Fresh start','Edited start'));assert(JSON.stringify((await saved()).settings.view)===view,'existing-ID edits preserve pan and zoom');
});
await test('the dot grid follows world coordinates at different zooms and after panning',async()=>{
 click('btn-zoom-out');const m=await saved(),v=m.settings.view,style=$('viewport').style,spacing=parseFloat(style.backgroundSize),positions=style.backgroundPosition.split(' ').map(parseFloat);assert(spacing>=10,'grid remains readable');assert(Math.abs(spacing/(20*v.scale)-Math.round(spacing/(20*v.scale)))<.001,'grid spacing is a whole number of snap steps');assert(Math.abs(positions[0]+spacing/2-v.x)<.001&&Math.abs(positions[1]+spacing/2-v.y)<.001,'dot origin matches world origin');
 const b=$('canvas').getBoundingClientRect();doc.querySelector('[data-tool="pan"]').click();pointer('pointerdown',b.x+100,b.y+200);pointer('pointermove',b.x+135,b.y+225,viewport);await wait(30);pointer('pointerup',b.x+135,b.y+225,viewport);const after=await saved(),p=$('viewport').style.backgroundPosition.split(' ').map(parseFloat);assert(Math.abs(p[0]+spacing/2-after.settings.view.x)<.001&&Math.abs(p[1]+spacing/2-after.settings.view.y)<.001,'panning carries the grid');key('Escape');
});
async function openFixture(model){const transfer=new win.DataTransfer();transfer.items.add(new win.File([JSON.stringify(model)],'fixture.json',{type:'application/json'}));$('file-input').files=transfer.files;$('file-input').dispatchEvent(new win.Event('change',{bubbles:true}));await until(()=>$('loading').hidden);}
function screenPoint(x,y){const b=$('canvas').getBoundingClientRect(),v=$('world').getAttribute('transform').match(/-?\d+(?:\.\d+)?(?:e[+-]?\d+)?/gi).map(Number);return{x:b.x+v[0]+x*v[2],y:b.y+v[1]+y*v[2]};}
async function dragNode(id,x,y){const node=doc.querySelector(`.diagram-node[data-object-id="${id}"] .node-shape`),b=node.getBoundingClientRect(),p=screenPoint(x,y);pointer('pointerdown',b.x+b.width/2,b.y+b.height/2,node);pointer('pointermove',p.x,p.y,viewport);await wait(30);pointer('pointerup',p.x,p.y,viewport);}
const rect=(id,x,y,parentId=null)=>({id,label:id,shape:'rectangle',x,y,width:120,height:54,parentId});
await test('Connect uses source/target clicks with contextual handles and a crosshair cursor',async()=>{
 click('btn-new');const m=await saved();m.nodes=[rect('A',60,100),rect('B',380,100)];await openFixture(m);doc.querySelector('[data-tool="connect"]').click();assert(!doc.querySelectorAll('[data-connect]').length,'no blanket highlighting');assert(win.getComputedStyle(doc.querySelector('.diagram-node')).cursor==='crosshair','node cursor indicates connecting');hitNode('A');assert(doc.querySelectorAll('[data-connect="A"]').length===4&&!doc.querySelector('[data-connect="B"]'),'only source handles');hitNode('B');let after=await saved();assert(after.edges.length===1&&after.edges[0].source==='A'&&after.edges[0].target==='B','clicks create edge');click('btn-undo');assert(!(await saved()).edges.length,'one undo removes connection');hitNode('A');key('Escape');assert(!(await saved()).edges.length,'Escape cancels pending source');key('Escape');
});
await test('dragging nodes into, between, and out of zones updates canvas and hierarchy atomically',async()=>{
 click('btn-new');const m=await saved();m.zones=[{id:'Outer',label:'Outer',x:30,y:40,width:400,height:400,parentId:null},{id:'Inner',label:'Inner',x:60,y:90,width:260,height:190,parentId:'Outer'}];m.nodes=[rect('A',510,100)];await openFixture(m);await dragNode('A',180,180);let after=await saved();assert(after.nodes[0].parentId==='Inner','drop adopts inner zone');assert(doc.querySelector('[data-tree-id="A"]').style.paddingLeft==='30px','hierarchy shows nested depth');const contained=JSON.stringify(after);await dragNode('A',360,350);after=await saved();assert(after.nodes[0].parentId==='Outer','drop releases inner and adopts outer');await dragNode('A',600,450);after=await saved();assert(after.nodes[0].parentId===null,'outside drop releases parent');click('btn-undo');assert((await saved()).nodes[0].parentId==='Outer','Undo restores membership and position');click('btn-undo');assert(JSON.stringify(await saved())===contained,'next Undo restores nested placement');
});
await test('zone drops adopt their intended parent even when node clearance shifts the contents',async()=>{
 click('btn-new');const m=await saved();m.zones=[{id:'Azone',label:'A zone',x:20,y:40,width:260,height:240,parentId:null},{id:'Bzone',label:'B zone',x:400,y:40,width:260,height:240,parentId:null}];m.nodes=[rect('A',70,100,'Azone'),rect('B',450,100,'Bzone')];await openFixture(m);const header=doc.querySelector('.zone-title[data-object-id="Azone"] rect'),r=header.getBoundingClientRect(),p=screenPoint(530,160),start=screenPoint(150,160);pointer('pointerdown',r.x+r.width/2,r.y+r.height/2,header);pointer('pointermove',r.x+r.width/2+p.x-start.x,r.y+r.height/2+p.y-start.y,viewport);await wait(30);assert(doc.querySelector('.diagram-zone[data-object-id="Bzone"]').classList.contains('drop-target'),'destination is highlighted');pointer('pointerup',r.x+r.width/2+p.x-start.x,r.y+r.height/2+p.y-start.y,viewport);let after=await saved();assert(after.zones.find(z=>z.id==='Azone').parentId==='Bzone','zone adopts target');assert(after.nodes[0].parentId==='Azone'&&doc.querySelector('[data-tree-id="A"]').style.paddingLeft==='30px','descendant hierarchy retained');click('btn-undo');assert((await saved()).zones[0].parentId===null,'zone drop Undo');
});
await test('node dragging, creation and shape growth maintain minimum spacing',async()=>{
 click('btn-new');const m=await saved();m.nodes=[rect('A',80,100),rect('B',350,100)];await openFixture(m);const fixed=JSON.stringify(m.nodes[0]);await dragNode('B',200,127);let after=await saved(),a=after.nodes[0],b=after.nodes[1];const separated=(a,b)=>a.x+a.width+24<=b.x+.001||b.x+b.width+24<=a.x+.001||a.y+a.height+24<=b.y+.001||b.y+b.height+24<=a.y+.001;assert(separated(a,b),'drag cannot close gap');assert(JSON.stringify(a)===fixed,'stationary node unchanged');doc.querySelector('[data-tool="node"]').click();const p=screenPoint(140,127);pointer('pointerdown',p.x,p.y);change('property-shape','diamond');after=await saved();for(let i=0;i<after.nodes.length;i++)for(let j=i+1;j<after.nodes.length;j++)assert(separated(after.nodes[i],after.nodes[j]),'creation and growth keep clearance');
});
await test('descriptions, notes and size typing commit, survive source changes, Undo and project reopening',async()=>{
 click('btn-new');const b=$('canvas').getBoundingClientRect();doc.querySelector('[data-tool="zone"]').click();pointer('pointerdown',b.x+40,b.y+60);input('property-description','Private order processing');input('property-notes','Owner: Commerce\n中文 🚀');click('btn-save');let m=JSON.parse(await blobs.at(-1).text());assert(m.zones[0].description==='Private order processing'&&m.zones[0].notes.includes('中文'),'both context fields saved');input('property-width','420');pointer('pointerdown',b.x+600,b.y+450);pointer('pointerup',b.x+600,b.y+450,viewport);m=await saved();assert(m.zones[0].width===420,'size typing survives canvas click');click('btn-undo');assert((await saved()).zones[0].width===280,'size is undoable');doc.querySelector('[data-tree-id="Zone1"] .tree-object').click();input('property-description','Revised description');click('btn-save');m=JSON.parse(await blobs.at(-1).text());click('btn-undo');assert((await saved()).zones[0].description==='Private order processing','metadata Undo');await openFixture(m);assert($('counts').textContent.includes('1 zones'),'project restored');assert((await saved()).zones[0].description==='Revised description','metadata restored');await apply('flowchart TD\n subgraph Zone1[Renamed zone]\n X[New node]\n end');m=await saved();assert(m.zones[0].description==='Revised description'&&m.zones[0].notes.includes('Commerce'),'matching IDs preserve metadata on source apply');click('btn-layout');await until(()=>$('loading').hidden);m=await saved();assert(m.zones[0].description==='Revised description'&&m.zones[0].notes.includes('Commerce'),'automatic layout preserves context');
});
await test('older crowded projects are repaired on open and marked for saving',async()=>{
 click('btn-new');const m=await saved();m.nodes=[rect('A',80,100),rect('B',80,100)];await openFixture(m);assert($('counts').textContent.includes('Unsaved changes'),'repair is marked as an edit');assert($('status').textContent.includes('24-unit gap'),'repair explained');const after=await saved(),a=after.nodes[0],b=after.nodes[1];assert(a.x+a.width+24<=b.x+.001||b.x+b.width+24<=a.x+.001||a.y+a.height+24<=b.y+.001||b.y+b.height+24<=a.y+.001,'old overlap repaired');
});
await test('hierarchy selection, collapse and connection rows stay synchronized with the diagram',async()=>{
 await apply('flowchart LR\n subgraph Z[Services]\n A[API]\n B[(Store)]\n end\n A edge@--> B');const toggle=doc.querySelector('[data-tree-id="Z"] .tree-toggle');toggle.click();assert(!doc.querySelector('[data-tree-id="A"]'),'collapse hides descendants');doc.querySelector('[data-tree-id="Z"] .tree-toggle').click();doc.querySelector('[data-tree-id="A"] .tree-object').click();assert(doc.querySelector('.diagram-node[data-object-id="A"]').classList.contains('selected'),'tree selects canvas');assert($('property-label').value==='API','inspector follows selection');$('hierarchy-flows').querySelector('button').click();assert(doc.querySelector('.diagram-edge').classList.contains('selected'),'flow selects edge');assert($('property-source').value==='A'&&$('property-target').value==='B','flow properties');
});
await test('all loaded runtime resources are local; external access is blocked by policy',()=>{const resources=win.performance.getEntriesByType('resource').map(r=>r.name);assert(resources.every(name=>new URL(name).origin===win.location.origin||name.startsWith('blob:')),'only same-origin resources');const policy=doc.querySelector('meta[http-equiv="Content-Security-Policy"]').content;assert(policy.includes("connect-src 'self'")&&policy.includes("script-src 'self'")&&policy.includes("font-src 'self'"),'local resource policy');assert(!$('editor').disabled&&!$('btn-new').disabled&&!$('direction').disabled,'controls enabled after startup');});
await test('eight resize handles resize nodes from corners and sides, reroute, cancel and undo one whole gesture',async()=>{
 click('btn-new');const m=await saved();m.nodes=[rect('A',100,100),rect('B',500,100)];m.edges=[{id:'E',source:'A',target:'B',label:'Signal',style:'normal',direction:'forward',routing:'orthogonal',sourceSide:'east',targetSide:'west'}];await openFixture(m);hitNode('A');assert(doc.querySelectorAll('[data-resize="A"]').length===8&&!doc.querySelector('[data-connect]'),'unambiguous resize controls');
 const before=await saved(),oldPath=doc.querySelector('[data-edge-id="E"]').getAttribute('d'),handle=doc.querySelector('[data-resize="A"][data-handle="nw"]'),r=handle.getBoundingClientRect();pointer('pointerdown',r.x+4,r.y+4,handle);pointer('pointermove',r.x+4-40,r.y+4-30,viewport);await wait(30);pointer('pointerup',r.x+4-40,r.y+4-30,viewport);let after=await saved(),a=after.nodes[0];assert(a.x===60&&a.y===70&&a.width===160&&a.height===84,'northwest anchors southeast');assert(a.manualSize&&doc.querySelector('[data-edge-id="E"]').getAttribute('d')!==oldPath,'resizing reroutes');click('btn-undo');assert(JSON.stringify(await saved())===JSON.stringify(before),'one Undo restores whole resize');click('btn-redo');assert((await saved()).nodes[0].width===160,'Redo restores resize');
 const stable=await saved(),east=doc.querySelector('[data-resize="A"][data-handle="e"]'),er=east.getBoundingClientRect();pointer('pointerdown',er.x+4,er.y+4,east);pointer('pointermove',er.x+100,er.y+4,viewport);await wait(30);key('Escape');assert(JSON.stringify(await saved())===JSON.stringify(stable),'Escape restores dimensions and manual preference');assert(!doc.querySelector('.alignment-guides'),'cancel removes guides');
});
await test('resize handles keep an eight-pixel target at every zoom and color swatches follow typed hex',async()=>{
 hitNode('A');for(const zoom of ['btn-zoom-out','btn-zoom-out','btn-zoom-in']){click(zoom);const r=doc.querySelector('[data-resize="A"][data-handle="se"]').getBoundingClientRect();assert(Math.abs(r.width-8)<.01&&Math.abs(r.height-8)<.01,'zoom-independent resize target');}input('property-background-color','#ffedd5');assert(doc.querySelector('[aria-label="Background color picker"]').value==='#ffedd5','typed hex updates swatch immediately');click('btn-save');
});
await test('numeric node sizing fits labels, links circle dimensions, stops at neighbours and resets to the label',async()=>{
 click('btn-new');const m=await saved();m.nodes=[rect('A',100,100),rect('B',400,100)];await openFixture(m);hitNode('A');input('property-width','1000');click('btn-save');let after=JSON.parse(await blobs.at(-1).text());assert(Math.abs(after.nodes[0].width-276)<.001&&after.nodes[1].x===400&&after.nodes[0].x===100,'growth stops at neighbour without moving objects');assert(Number($('property-width').value)===276,'inspector shows constrained width');click('btn-undo');change('property-parent-zone','');change('property-shape','circle');change('property-width','210');after=await saved();assert(after.nodes[0].width===after.nodes[0].height,'circle dimensions linked');doc.querySelector('#properties button').click();assert(!(await saved()).nodes[0].manualSize,'Fit to label clears manual preference');
});
await test('subtle side guides appear for move and resize, disappear on release and never export',async()=>{
 click('btn-new');const m=await saved();m.nodes=[rect('A',100,100),rect('B',100,300)];m.zones=[{id:'Z',label:'Aligned zone',x:100,y:420,width:240,height:150,parentId:null}];await openFixture(m);const n=doc.querySelector('.diagram-node[data-object-id="A"] .node-shape'),b=n.getBoundingClientRect();pointer('pointerdown',b.x+60,b.y+27,n);pointer('pointermove',b.x+60,b.y+57,viewport);await wait(30);let guides=doc.querySelectorAll('.alignment-guides line');assert(guides.length>=2,'node and zone side guides shown');assert(win.getComputedStyle(guides[0]).pointerEvents==='none','guides do not intercept input');assert([...guides].some(g=>Number(g.getAttribute('y2'))>=570),'zone span is represented');pointer('pointerup',b.x+60,b.y+57,viewport);assert(!doc.querySelector('.alignment-guides'),'release clears guides');
 hitNode('A');const h=doc.querySelector('[data-resize="A"][data-handle="e"]'),r=h.getBoundingClientRect();pointer('pointerdown',r.x+4,r.y+4,h);pointer('pointermove',r.x+34,r.y+4,viewport);await wait(30);assert(doc.querySelector('.alignment-guides line'),'resize shows guides');key('Escape');$('alignment-guides').checked=false;$('alignment-guides').dispatchEvent(new win.Event('change',{bubbles:true}));const nb=doc.querySelector('.diagram-node[data-object-id="A"] .node-shape').getBoundingClientRect();pointer('pointerdown',nb.x+60,nb.y+27,doc.querySelector('.diagram-node[data-object-id="A"] .node-shape'));pointer('pointermove',nb.x+60,nb.y+57,viewport);await wait(30);assert(!doc.querySelector('.alignment-guides'),'toggle hides guides');key('Escape');change('export-format','svg');click('btn-export');assert(!(await blobs.at(-1).text()).includes('alignment-guides'),'guides excluded from SVG');
});
await test('node and zone colors use pickers or hex fields, remain undoable and export their appearance',async()=>{
 click('btn-new');const m=await saved();m.nodes=[rect('A',100,100)];m.zones=[{id:'Z',label:'Workshop',x:50,y:40,width:320,height:200,parentId:null}];await openFixture(m);hitNode('A');assert(doc.querySelectorAll('input[type=color]').length===2,'both color pickers');input('property-background-color','#134e4a');input('property-font-color','#ffffff');click('btn-save');let after=JSON.parse(await blobs.at(-1).text());assert(after.nodes[0].backgroundColor==='#134e4a'&&after.nodes[0].fontColor==='#ffffff','hex fields save');assert(win.getComputedStyle(doc.querySelector('.diagram-node .node-shape')).fill==='rgb(19, 78, 74)','node background applied');assert(win.getComputedStyle(doc.querySelector('.diagram-node text')).fill==='rgb(255, 255, 255)','node font applied');
 doc.querySelector('[data-tree-id="Z"] .tree-object').click();const picker=doc.querySelector('[aria-label="Background color picker"]');picker.value='#312e81';picker.dispatchEvent(new win.Event('input',{bubbles:true}));picker.dispatchEvent(new win.Event('change',{bubbles:true}));change('property-font-color','#fef3c7');after=await saved();assert(after.zones[0].backgroundColor==='#312e81'&&after.zones[0].fontColor==='#fef3c7','picker and zone font saved');change('export-format','svg');click('btn-export');const svg=new win.DOMParser().parseFromString(await blobs.at(-1).text(),'image/svg+xml');assert(svg.querySelector('.diagram-node .node-shape').getAttribute('style').includes('#134e4a'),'node color exported');assert(svg.querySelector('.zone-label').getAttribute('style').includes('#fef3c7')&&svg.querySelector('.zone-label-backing').getAttribute('style').includes('#312e81'),'zone title colors exported');click('btn-undo');assert(!(await saved()).zones[0].fontColor,'font color Undo');change('property-background-color','invalid');assert(!$('error-banner').hidden&&(await saved()).zones[0].backgroundColor==='#312e81','invalid color rolls back');
});
await test('edges have context fields that commit on click-away, survive source and layout, reopen and undo',async()=>{
 await apply('flowchart LR\n A[Observe]\n B[Respond]\n A signal@-->|Alert| B');doc.querySelector('[data-object-id="signal"] .edge-hit').dispatchEvent(new win.PointerEvent('pointerdown',{bubbles:true,isPrimary:true,button:0,pointerId:1}));input('property-description','Urgent incident handover');input('property-notes','Owner: Response team\n中文 🚀');hitNode('A');let m=await saved(),e=m.edges[0];assert(e.description==='Urgent incident handover'&&e.notes.includes('中文'),'edge context committed before selection changes');await apply($('editor').value.replace('Respond','Resolve'));click('btn-layout');await until(()=>$('loading').hidden);m=await saved();assert(m.edges[0].notes===e.notes&&m.edges[0].description===e.description,'source and layout retain edge context');await openFixture(m);doc.querySelector('[data-object-id="signal"] .edge-hit').dispatchEvent(new win.PointerEvent('pointerdown',{bubbles:true,isPrimary:true,button:0,pointerId:1}));assert($('property-notes').value===e.notes,'reopen populates notes');input('property-notes','Updated protocol');click('btn-save');click('btn-undo');assert((await saved()).edges[0].notes===e.notes,'notes are undoable');
});
await test('click-away commits keep hierarchy targets connected until the click selects the intended object',async()=>{
 await apply('flowchart LR\n subgraph Z[Operations]\n A[Observe]\n B[Respond]\n end\n A handoff@--> B');doc.querySelector('[data-tree-id="Z"] .tree-object').click();input('property-font-color','#3730a3');const edgeButton=$('hierarchy-flows').querySelector('button'),r=edgeButton.getBoundingClientRect();pointer('pointerdown',r.x+10,r.y+10,edgeButton);assert(edgeButton.isConnected,'pointerdown commit does not detach the clicked connection');edgeButton.click();assert(propertiesIdentity()==='Edge · handoff','click selects edge after color commit');input('property-notes','Real edge context');click('btn-save');const after=JSON.parse(await blobs.at(-1).text());assert(after.edges[0].notes==='Real edge context'&&!after.zones[0].notes,'notes go to the intended edge');
 input('font-size','30');const notes=$('property-notes'),nr=notes.getBoundingClientRect();pointer('pointerdown',nr.x+10,nr.y+10,notes);assert(notes.isConnected,'font commit retains the next property input');assert((await saved()).settings.fontSize===30,'font changes still commit');
});
function propertiesIdentity(){return $('properties').querySelector('.object-id')?.textContent;}
await test('global text size updates all labels and fit limits while preserving view and manual widths',async()=>{
 click('btn-new');const m=await saved();m.nodes=['rectangle','rounded','diamond','circle','cylinder'].map((shape,i)=>({...rect('N'+i,80+i*400,140),shape,label:'Wide 中文 label\nline two'}));m.zones=[{id:'Z',label:'Workshop delivery',x:40,y:40,width:2100,height:500,parentId:null}];m.nodes.forEach(n=>n.parentId='Z');m.edges=[{id:'E',source:'N0',target:'N1',label:'Next session',style:'normal',direction:'forward',routing:'orthogonal',sourceSide:null,targetSide:null}];await openFixture(m);hitNode('N0');change('property-width','240');const before=await saved(),view=JSON.stringify(before.settings.view);input('font-size','28');click('btn-save');let after=JSON.parse(await blobs.at(-1).text());assert(after.settings.fontSize===28&&JSON.stringify(after.settings.view)===view,'font typing commits without changing zoom');assert(after.nodes[0].manualSize.width===240&&after.nodes[0].width===240,'manual width preserved');for(const t of doc.querySelectorAll('.diagram-node text,.zone-label,.edge-label text'))assert(win.getComputedStyle(t).fontSize==='28px','all labels share font size');for(const n of doc.querySelectorAll('.diagram-node')){const b=n.querySelector('.node-shape').getBBox(),t=n.querySelector('text').getBBox();assert(t.x>=b.x&&t.y>=b.y&&t.x+t.width<=b.x+b.width&&t.y+t.height<=b.y+b.height,'shape contains larger text');}
 await apply($('editor').value);after=await saved();assert(after.settings.fontSize===28&&after.nodes.find(n=>n.id==='N0').manualSize.width===240,'source retains appearance and manual size');click('btn-layout');await until(()=>$('loading').hidden);after=await saved();assert(after.nodes.find(n=>n.id==='N0').width===240,'Auto layout retains manual width');await openFixture(after);assert($('font-size').value==='28','reopen restores toolbar size');change('font-size','48');assert((await saved()).settings.fontSize===48,'maximum font size accepted');click('btn-undo');assert((await saved()).settings.fontSize===28,'font size undoable');const stable=await saved();change('font-size','49');assert(!$('error-banner').hidden&&JSON.stringify(await saved())===JSON.stringify(stable),'out-of-range size rejected without a history edit');change('export-format','svg');click('btn-export');const svg=await blobs.at(-1).text();assert(svg.includes('font-size:28px')&&!svg.includes('resize-handle'),'large-font export excludes resize controls');
});
out.dataset.complete='true';out.dataset.passed=String(results.every(r=>r.pass));out.textContent=JSON.stringify({passed:results.filter(r=>r.pass).length,total:results.length,results},null,2);
