import test from 'node:test';import assert from 'node:assert/strict';
import {emptyModel,copy,moveSelection,arrange,validateModel,History} from '../core.mjs';
import {translateWaypoints,waypointInsertionIndex} from '../waypoints.mjs';
const node=(id,x,y,parentId=null)=>({id,label:id,shape:'rectangle',x,y,width:120,height:54,parentId});
function fixture(){const m=emptyModel();m.nodes=[node('A',50,80),node('B',400,80)];m.edges=[{id:'E',label:'',source:'A',target:'B',routing:'orthogonal',direction:'forward',style:'normal',sourceSide:'east',targetSide:'west',waypoints:[{x:250,y:300},{x:500,y:300}]}];return m;}
test('one endpoint keeps a fixed corridor; both endpoints and self loops translate',()=>{const m=fixture(),points=copy(m.edges[0].waypoints);moveSelection(m,new Set(['A']),30,40);assert.deepEqual(m.edges[0].waypoints,points);moveSelection(m,new Set(['A','B']),20,-10);assert.deepEqual(m.edges[0].waypoints,points.map(p=>({x:p.x+20,y:p.y-10})));m.edges[0].target='A';moveSelection(m,new Set(['A']),10,5);assert.equal(m.edges[0].waypoints[0].x,280);});
test('nested zones and node containers move internal routes once and leave crossing routes fixed',()=>{for(const container of [false,true]){const m=fixture();const z={id:'Z',label:'Zone',x:0,y:0,width:650,height:450,parentId:null};if(container)m.nodes.unshift({...z,shape:'rectangle',container:true});else m.zones.push(z);m.nodes.find(n=>n.id==='A').parentId='Z';m.nodes.find(n=>n.id==='B').parentId='Z';m.nodes.push(node('Outside',900,0));m.edges.push({...copy(m.edges[0]),id:'Cross',target:'Outside'});const before=copy(m);moveSelection(m,new Set(['Z','A']),75,40);assert.deepEqual(m.edges[0].waypoints,before.edges[0].waypoints.map(p=>({x:p.x+75,y:p.y+40})));assert.deepEqual(m.edges[1].waypoints,before.edges[1].waypoints);}});
test('alignment translates waypoints only when the final endpoint translations match',()=>{const m=fixture();m.nodes.push(node('C',-200,0));const before=copy(m);arrange(m,new Set(['A','B','C']),'top');assert.deepEqual(m.edges[0].waypoints,before.edges[0].waypoints.map(p=>({x:p.x,y:p.y-80})));const other=fixture();other.nodes[1].y=150;const original=copy(other.edges[0].waypoints);arrange(other,new Set(['A','B']),'top');assert.deepEqual(other.edges[0].waypoints,original);});
test('resizing endpoints and reconnecting preserve waypoint coordinates',()=>{const m=fixture(),before=copy(m);m.nodes[0].x-=40;m.nodes[0].width+=40;translateWaypoints(before,m);assert.deepEqual(m.edges[0].waypoints,before.edges[0].waypoints);m.edges[0].target='A';translateWaypoints(before,m);assert.deepEqual(m.edges[0].waypoints,before.edges[0].waypoints);});
test('waypoints persist through projects and history; malformed or excessive points are rejected',()=>{const m=fixture();assert.deepEqual(validateModel(JSON.parse(JSON.stringify(m))),m);const h=new History(),before=copy(m);m.edges[0].waypoints[0].x+=30;h.record(before,m);assert.deepEqual(h.undo(m),before);assert.deepEqual(h.redo(before),m);for(const points of [null,{},[{x:NaN,y:0}],[{x:0,y:1e7}],Array(101).fill({x:0,y:0})]){const bad=fixture();bad.edges[0].waypoints=points;assert.throws(()=>validateModel(bad));}m.edges[0].routing='straight';assert.throws(()=>validateModel(m),/orthogonal/);delete m.edges[0].waypoints;assert.doesNotThrow(()=>validateModel(m));});
test('new points insert in route order including inside an existing segment',()=>{const route=[{x:0,y:0},{x:200,y:0},{x:200,y:200},{x:400,y:200}];const points=[{x:100,y:0},{x:200,y:100}];assert.equal(waypointInsertionIndex(route,points,{x:50,y:10}),0);assert.equal(waypointInsertionIndex(route,points,{x:200,y:50}),1);assert.equal(waypointInsertionIndex(route,points,{x:350,y:200}),2);});
