import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyModel,copy,object,items,descendants,arrange,expandZones,fitZonesToContents,zonePadding,containerContentBox,moveSelection,validateModel,History} from '../core.mjs';
import {resizeObject,resizeNodeTo} from '../editing.mjs';
import {overlapsWithGap} from '../geometry.mjs';
const node=(id,x,y,parentId=null)=>({id,label:id,shape:'rectangle',x,y,width:120,height:54,parentId});
const zone=(id,x,y,parentId=null)=>({id,label:id,x,y,width:320,height:300,parentId});
const edge=(id,source,target,waypoints=[])=>({id,label:id,source,target,routing:'orthogonal',style:'normal',direction:'forward',sourceSide:'east',targetSide:'west',waypoints,labelPosition:{fraction:.4,offsetAlong:0,offsetNormal:40}});
function fixture(){const m=emptyModel();m.zones=[zone('Seed',0,0),zone('Growth',500,170),zone('Harvest',1000,90)];m.nodes=[node('A',40,60,'Seed'),node('B',180,160,'Seed'),node('C',550,250,'Growth'),node('D',1040,160,'Harvest'),node('Outside',1450,500)];m.edges=[edge('Internal','A','B',[{x:160,y:120}]),edge('Cross','B','C',[{x:420,y:150}]),edge('Return','D','D',[{x:1230,y:280}])];return m;}
function rigid(before,after,id){const a=object(before,id),b=object(after,id),dx=b.x-a.x,dy=b.y-a.y;for(const child of items(before).filter(n=>descendants(before,id).has(n.id))){const n=object(after,child.id);assert.equal(n.x-child.x,dx,child.id+' horizontal offset');assert.equal(n.y-child.y,dy,child.id+' vertical offset');assert.equal(n.width,child.width);assert.equal(n.height,child.height);assert.equal(n.parentId,child.parentId);}}
function inside(m){for(const z of m.zones){const b=containerContentBox(m,z);for(const c of items(m).filter(n=>n.parentId===z.id)){assert(c.x>=b.x-1e-7);assert(c.y>=b.y-1e-7);assert(c.x+c.width<=b.x+b.width+1e-7);assert(c.y+c.height<=b.y+b.height+1e-7);}}}
for(const [command,axis,size,factor] of [['top','y','height',0],['center-y','y','height',.5],['bottom','y','height',1],['left','x','width',0],['center-x','x','width',.5],['right','x','width',1]])test(command+' aligns whole zones with rigid descendants and clears other frames',()=>{const m=fixture(),before=copy(m);arrange(m,new Set(['Seed','Growth','Harvest']),command);const z=m.zones;assert(z.every(n=>n[axis]+n[size]*factor===z[0][axis]+z[0][size]*factor));for(const n of z)rigid(before,m,n.id);for(let i=0;i<z.length;i++)for(let j=i+1;j<z.length;j++)assert.equal(overlapsWithGap(z[i],z[j]),false);assert.deepEqual(m.nodes.at(-1),before.nodes.at(-1));inside(m);});
for(const command of ['distribute-x','distribute-y'])test(command+' spaces whole groups equally and maintains their internal layout',()=>{const m=fixture(),before=copy(m),axis=command.endsWith('x')?'x':'y',size=axis==='x'?'width':'height';arrange(m,new Set(['Seed','Growth','Harvest']),command);const sorted=[...m.zones].sort((a,b)=>a[axis]-b[axis]),gaps=sorted.slice(1).map((n,i)=>n[axis]-sorted[i][axis]-sorted[i][size]);assert.equal(gaps[0],gaps[1]);assert(gaps[0]>=24);for(const z of m.zones)rigid(before,m,z.id);});
test('selected ancestors and descendants move once; nested frames and node containers remain rigid',()=>{const m=fixture();m.zones.push({...zone('Climate',530,230,'Growth'),width:250,height:170});m.nodes.find(n=>n.id==='C').parentId='Climate';m.nodes.push({...node('Hub',60,80,'Seed'),container:true,width:210,height:180},node('Sensor',90,135,'Hub'));m.nodes.find(n=>n.id==='A').parentId='Hub';expandZones(m);const before=copy(m);arrange(m,new Set(['Seed','Growth','Climate','C','Hub']),'top');rigid(before,m,'Seed');rigid(before,m,'Growth');assert.deepEqual(object(m,'Harvest'),object(before,'Harvest'));inside(m);});
test('sibling nested zones align rigidly while their unselected parent expands without moving other children',()=>{const m=emptyModel();m.zones=[{...zone('Outer',0,0),width:850,height:700},zone('One',30,100,'Outer'),zone('Two',420,320,'Outer')];m.nodes=[node('A',70,160,'One'),node('B',460,400,'Two'),node('Stationary',50,610,'Outer')];const before=copy(m);arrange(m,new Set(['One','Two']),'top');assert.equal(object(m,'One').y,object(m,'Two').y);rigid(before,m,'One');rigid(before,m,'Two');assert.deepEqual(object(m,'Stationary'),object(before,'Stationary'));inside(m);});
test('alignment dodges stationary nodes along the free axis without breaking child offsets',()=>{const m=fixture();m.nodes.push(node('Blocker',540,40));const before=copy(m);arrange(m,new Set(['Seed','Growth']),'top');assert.equal(object(m,'Growth').y,object(m,'Seed').y);assert.equal(overlapsWithGap(object(m,'Growth'),object(m,'Blocker')),false);rigid(before,m,'Growth');assert.deepEqual(object(m,'Blocker'),object(before,'Blocker'));});
test('distribution preserves equal gaps when a stationary object blocks a destination',()=>{const m=fixture();moveSelection(m,new Set(['Growth']),200,-170);moveSelection(m,new Set(['Harvest']),0,-90);m.nodes.push(node('Blocker',540,40));const before=copy(m);arrange(m,new Set(['Seed','Growth','Harvest']),'distribute-x');const zs=[...m.zones].sort((a,b)=>a.x-b.x),gaps=zs.slice(1).map((n,i)=>n.x-zs[i].x-zs[i].width);assert.equal(gaps[0],gaps[1]);assert.equal(overlapsWithGap(object(m,'Growth'),object(m,'Blocker')),false);rigid(before,m,'Growth');assert.deepEqual(object(m,'Blocker'),object(before,'Blocker'));});
test('alignment moves internal waypoints by each final group delta and keeps external corridors and labels',()=>{const m=fixture(),before=copy(m);arrange(m,new Set(['Seed','Growth','Harvest']),'top');const d=object(m,'Harvest').y-object(before,'Harvest').y;assert.deepEqual(object(m,'Return').waypoints,before.edges[2].waypoints.map(p=>({...p,y:p.y+d})));assert.deepEqual(object(m,'Cross').waypoints,before.edges[1].waypoints);assert.deepEqual(m.edges.map(e=>e.labelPosition),before.edges.map(e=>e.labelPosition));});
test('waypoints stay fixed when alignment clearance gives endpoints different final translations',()=>{const m=emptyModel();m.nodes=[node('A',50,80),node('B',400,80),node('C',0,0)];m.edges=[edge('E','A','B',[{x:250,y:300}])];const before=copy(m);arrange(m,new Set(['A','B','C']),'top');assert(m.nodes.every(n=>n.y===0));assert.notEqual(m.nodes[0].x,before.nodes[0].x);assert.deepEqual(m.edges[0].waypoints,before.edges[0].waypoints);});
test('fitting a zone tightens only its frame and preserves children, endpoints, routes and labels',()=>{const m=fixture(),before=copy(m);fitZonesToContents(m,new Set(['Seed']));assert.deepEqual(object(m,'Seed'),{...before.zones[0],x:20,y:16,width:300,height:218});assert.deepEqual(m.nodes,before.nodes);assert.deepEqual(m.edges,before.edges);assert.deepEqual(m.zones.slice(1),before.zones.slice(1));inside(m);});
test('asymmetric padding, zero padding and fractional padding fit exactly beneath the title',()=>{for(const padding of [{top:40,right:60,bottom:30,left:10},{top:0,right:0,bottom:0,left:0},{top:7.5,right:23.25,bottom:10.5,left:6.25}]){const m=fixture();m.zones[0].padding=padding;const before=copy(m.nodes);fitZonesToContents(m,new Set(['Seed']));const b=containerContentBox(m,m.zones[0]);assert.equal(b.x,40);assert.equal(b.y,60);assert.equal(m.zones[0].x,40-padding.left);assert.equal(m.zones[0].width,260+padding.left+padding.right);assert.deepEqual(m.nodes,before);inside(m);}});
test('fit retains unselected nested manual sizes; fitting both depths resolves innermost first',()=>{const m=fixture();m.zones.push({...zone('Climate',530,230,'Growth'),width:500,height:500});object(m,'C').parentId='Climate';expandZones(m);const inner=copy(object(m,'Climate')),before=copy(m.nodes);fitZonesToContents(m,new Set(['Growth']));assert.deepEqual(object(m,'Climate'),inner);fitZonesToContents(m,new Set(['Growth','Climate']));assert(object(m,'Climate').width<inner.width);assert(object(m,'Growth').width<600);assert.deepEqual(m.nodes,before);inside(m);});
test('fitting an inner zone expands ancestors only when needed and never moves their children',()=>{const m=fixture();m.zones.push({...zone('Inner',30,50,'Seed'),width:180,height:130,padding:{top:90,right:90,bottom:90,left:90}});object(m,'A').parentId='Inner';const before=copy(m.nodes);fitZonesToContents(m,new Set(['Inner']));assert.deepEqual(m.nodes,before);inside(m);});
test('empty zones fit at their current position with safe label, header and padding minima',()=>{const m=emptyModel();m.settings.fontSize=48;m.zones=[{...zone('Empty',-40,70),label:'A long empty greenhouse title',width:1600,height:1300,padding:{top:60,right:150,bottom:80,left:150}}];fitZonesToContents(m,new Set(['Empty']));const z=m.zones[0];assert.equal(z.x,-40);assert.equal(z.y,70);assert(z.width>301&&z.width<1600);assert.equal(z.height,205);inside(m);});
test('automatic growth never shrinks manual room and moving content back requires explicit fit',()=>{const m=fixture(),initial=copy(m.zones[0]);moveSelection(m,new Set(['B']),400,300);const expanded=copy(m.zones[0]);assert(expanded.width>initial.width&&expanded.height>initial.height);moveSelection(m,new Set(['B']),-400,-300);assert.deepEqual(m.zones[0],expanded);fitZonesToContents(m,new Set(['Seed']));assert(m.zones[0].width<expanded.width&&m.zones[0].height<expanded.height);});
for(const handle of ['n','s','e','w','nw','ne','sw','se'])test('zone '+handle+' handle clamps to content with fixed opposite sides and children',()=>{const m=fixture(),before=copy(m),z=m.zones[0],right=z.x+z.width,bottom=z.y+z.height;resizeObject(m,'Seed',handle,handle.includes('w')?1000:-1000,handle.includes('n')?1000:-1000);assert.deepEqual(m.nodes,before.nodes);assert.deepEqual(m.edges,before.edges);if(handle.includes('w'))assert.equal(z.x+z.width,right);else assert.equal(z.x,before.zones[0].x);if(handle.includes('n'))assert.equal(z.y+z.height,bottom);else assert.equal(z.y,before.zones[0].y);inside(m);const stable=copy(m);resizeObject(m,'Seed',handle,handle.includes('w')?1000:-1000,handle.includes('n')?1000:-1000);assert.deepEqual(m,stable,'clamped resize is stable on repetition');});
test('numeric zone sizing anchors top-left, respects padding and does not move nested children',()=>{const m=fixture();m.zones[0].padding={top:25,right:33,bottom:41,left:27};expandZones(m);const before=copy(m);resizeNodeTo(m,'Seed',1,1);assert.equal(m.zones[0].x,before.zones[0].x);assert.equal(m.zones[0].y,before.zones[0].y);assert.deepEqual(m.nodes,before.nodes);inside(m);});
test('padding survives project roundtrip and whole-command Undo/Redo without changing legacy defaults',()=>{const m=fixture(),h=new History(),before=copy(m);assert.deepEqual(zonePadding(m.zones[0]),{top:14,right:20,bottom:20,left:20});m.zones[0].padding={top:80,right:0,bottom:33,left:17};fitZonesToContents(m,new Set(['Seed']));h.record(before,m);assert.deepEqual(validateModel(JSON.parse(JSON.stringify(m))),m);assert.deepEqual(h.undo(m),before);assert.deepEqual(h.redo(before),m);});
test('project padding rejects malformed, missing, extra, negative and nonfinite values',()=>{for(const p of [null,[],20,{}, {top:14,right:20,bottom:20}, {top:14,right:20,bottom:20,left:20,extra:0}, {top:-1,right:20,bottom:20,left:20}, {top:NaN,right:20,bottom:20,left:20}, {top:0,right:1001,bottom:20,left:20}]){const m=fixture();m.zones[0].padding=p;assert.throws(()=>validateModel(m),/padding/);}});
test('fractional frames keep exact sizes through repeated rigid moves, expansion checks and fitting',()=>{const m=fixture();m.zones[0].x=10.392638185021;m.zones[0].width=407.7951365983839;const before=copy(m.zones[0]);for(let i=0;i<20;i++){moveSelection(m,new Set(['Seed']),17.738493724,.3485345324);expandZones(m);assert.equal(m.zones[0].width,before.width);assert.equal(m.zones[0].height,before.height);}fitZonesToContents(m,new Set(['Seed']));const fitted=copy(m);for(let i=0;i<20;i++){fitZonesToContents(m,new Set(['Seed']));expandZones(m);}assert.deepEqual(m,fitted);});
