import {build} from 'esbuild';
import {readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';

const prefixes=['tabler','lucide','carbon','ph','fluent-color','logos'];
const root=new URL('../',import.meta.url),destination=new URL('vendor/icons/',root);
await mkdir(destination,{recursive:true});
const catalog=[],manifest=[],notices=['# Bundled icon packs','','These pinned Iconify packs are shipped with the app. Runtime loading uses only app assets.',''];
for(const prefix of prefixes){
 const folder=new URL(`node_modules/@iconify-json/${prefix}/`,root);
 const [raw,info,pkg]=await Promise.all(['icons.json','info.json','package.json'].map(async file=>JSON.parse(await readFile(new URL(file,folder),'utf8'))));
 const content=JSON.stringify(raw)+'\n';
 for(const [name,icon]of Object.entries(raw.icons))if(/<(?:script|foreignObject|image)\b|\son[a-z]+\s*=|(?:href|src)="(?:https?:|\/\/)|url\((?:https?:|\/\/)/i.test(icon.body))throw new Error(`Icon ${prefix}:${name} requires an external or active asset.`);
 await writeFile(new URL(prefix+'.json',destination),content);
 const names=[...Object.keys(raw.icons),...Object.keys(raw.aliases||{})].sort();
 catalog.push({prefix,name:info.name,version:pkg.version,count:names.length,palette:Boolean(info.palette),names});
 let url=info.license.url||'https://raw.githubusercontent.com/carbon-design-system/carbon/main/LICENSE';
 url=url.replace('https://github.com/','https://raw.githubusercontent.com/').replace('/blob/','/');
 const licenseFile=prefix+'-LICENSE.txt';
 try{await readFile(new URL(licenseFile,destination));}catch{
  const response=await fetch(url);if(!response.ok)throw new Error(`Cannot load ${prefix} license: ${response.status}`);
  const text=await response.text();if(text.includes('<!DOCTYPE html>'))throw new Error(`Unexpected ${prefix} license response`);
  await writeFile(new URL(licenseFile,destination),text);
 }
 manifest.push({prefix,package:pkg.name,version:pkg.version,count:names.length,author:info.author,license:info.license,licenseSource:url,source:info.author.url,sha256:createHash('sha256').update(content).digest('hex')});
 notices.push(`- **${info.name} ${pkg.version}** (${names.length.toLocaleString('en')} icons), ${info.author.name} — ${info.license.spdx}: [full license](${licenseFile}), [source](${info.author.url}).`);
}
await writeFile(new URL('catalog.mjs',destination),'// Generated by tools/build-icons.mjs from pinned Iconify packages.\nexport default '+JSON.stringify(catalog)+';\n');
await build({stdin:{contents:"export {getIconData,iconToSVG,replaceIDs} from '@iconify/utils';",resolveDir:root.pathname},bundle:true,format:'esm',platform:'browser',target:'es2022',minify:true,legalComments:'eof',outfile:new URL('iconify-utils.mjs',destination).pathname});
await copyFile(new URL('node_modules/@iconify/utils/license.txt',root),new URL('iconify-utils-LICENSE.txt',destination));
const utility=JSON.parse(await readFile(new URL('node_modules/@iconify/utils/package.json',root)));
notices.push('',`Icon data rendering uses **@iconify/utils ${utility.version}**, MIT: [full license](iconify-utils-LICENSE.txt).`,'','The icon data is unmodified; whitespace is compacted for distribution. The manifest records source versions and SHA-256 hashes. Run `npm run build:icons` to reproduce the assets from package-lock.json. License files are retained for offline rebuilds.','');
await writeFile(new URL('manifest.json',destination),JSON.stringify(manifest,null,2)+'\n');
await writeFile(new URL('README.md',destination),notices.join('\n'));
console.log(`Bundled ${catalog.reduce((sum,p)=>sum+p.count,0).toLocaleString('en')} icons in ${catalog.length} packs.`);
